### PR TITLE
Correctly handle server-initiated WebSocket close

### LINKED ISSUE #581: Closing of websocket by remote server does not trigger the script close handler
When the remote server closes the websocket [like this](https://github.com/loadimpact/k6/blob/d6f9a55ad1ebb131b1d3e65a05ce32bd68c8ab8d/lib/testutils/httpmultibin.go#L92), the `close` handler in the script is not called and the script iteration never finishes executing, it becomes stuck in the websocket handling code. 

The `error` handler is called with an error like `GoError: An unexpected error occured: websocket: close 1006 (abnormal closure): unexpected EOF....`, which is probably also suboptimal.

### PR DESCRIPTION
**Pull request by imiric**
This avoids a hanging behavior when the server closes the WS connection, either via a [control close frame](https://tools.ietf.org/html/rfc6455#section-5.5.1) or by closing the connection prematurely without sending the control frame (deviating from the WS protocol).

If the control close frame is not received but the connection is closed, the error (`close 1006 abnormal closure): unexpected EOF`) will be returned to the user's WS error handler, as it indicates an issue with the server.

The user-specified close handler should be called in either case now.

Closes #581

### CODE REVIEW

File: core/engine_test.go [hunk 1]
```diff
@@ -535,7 +535,7 @@ func TestSentReceivedMetrics(t *testing.T) {
 		{tr(`import ws from "k6/ws";
 			let data = "0123456789".repeat(100);
 			export default function() {
-				ws.connect("WSBIN_URL/ws-echo", null, function (socket) {
+				ws.connect("WSBIN_URL/ws-echo-invalid", null, function (socket) {
```
Comment (imiric) [inline core/engine_test.go]: All of these changes are to indicate this is an "invalid" server implementation, which I left in to avoid refactoring all existing tests that depended on it. But let me know if you prefer a different approach.

File: js/modules/k6/ws/ws.go [hunk 2]
```diff
@@ -454,22 +454,19 @@ func (s *Socket) closeConnection(code int) error {
 
 // Wraps conn.ReadMessage in a channel
 func readPump(conn *websocket.Conn, readChan chan []byte, errorChan chan error, closeChan chan int) {
-	defer func() { _ = conn.Close() }()
```
Comment (imiric) [inline js/modules/k6/ws/ws.go]: This `Close()` seemed redundant since it's already done in `socket.Close()`, and this `*Read*Message` wrapper shouldn't be closing connections anyway IMO.

File: js/modules/k6/ws/ws_test.go [hunk 3]
```diff
@@ -274,7 +275,38 @@ func TestSession(t *testing.T) {
...
+			let closed = false;
+			let res = ws.connect("WSBIN_URL%s", function(socket){
+				socket.on("open", function() {
+					socket.send("test");
+				})
+				socket.on("close", function() {
+					closed = true;
+				})
+			});
+			if (!closed) { throw new Error ("close event not fired"); }
```
Comment (imiric) [inline js/modules/k6/ws/ws_test.go]: I was surprised this check actually works... I would expect `ws.connect()` to return right after the connection is established, since `res` will have the `101 Switching Protocols` response, and the WS handlers to be called "much" later. So I think this test and others like it should fail :)

It seems like we're blocking on `ws.connect()` for the entire duration of the WS connection. Should this be a bug?

File: core/engine_test.go (hunk 1 above)
Comment (MStoykov) [reply core/engine_test.go]: Wasn't just one test that was affected `TestSentReceivedMetrics` (this one) . Why are you using it for all the ws_tests as well ?

File: js/modules/k6/ws/ws_test.go (hunk 3 above)
Comment (MStoykov) [reply js/modules/k6/ws/ws_test.go]: it's literally what the [documentation](https://docs.k6.io/docs/connect-url-params-func) says it will do. This is because ... well we do not have an event loop so there is no other way for you to handle the asynchronous nature of ws except for us to make a mini event loop just for ws and than wait until the connection closes :).

File: js/modules/k6/ws/ws_test.go [hunk 4]
```diff
@@ -274,7 +275,38 @@ func TestSession(t *testing.T) {
...
+			`, tc.endpoint)))
+			assert.NoError(t, err)
+		})
+	}
+
+	assertSessionMetricsEmitted(t, stats.GetBufferedSamples(samples), "", sr("WSBIN_URL/ws-echo-invalid"), 101, "")
```
Comment (MStoykov) [inline js/modules/k6/ws/ws_test.go]: I would expect that you will be checking inside the loop for each of the urls

File: js/modules/k6/ws/ws_test.go (hunk 3 above)
Comment (MStoykov) [reply js/modules/k6/ws/ws_test.go]: Also you are not using `ws-close` anywhere, either remove it or add it here as an additional test

File: js/modules/k6/ws/ws.go [hunk 5]
```diff
@@ -262,9 +262,9 @@ func (*WS) Connect(ctx context.Context, url string, args ...goja.Value) (*WSHTTP
 		case readErr := <-readErrChan:
 			socket.handleEvent("error", rt.ToValue(readErr))
 
-		case readClose := <-readCloseChan:
```
Comment (MStoykov) [inline js/modules/k6/ws/ws.go]: Okay, so correct me if I am wrong, but: 
socket.Close is going to call the `handleEvent("close", ...)` but only with the `GoingAwayClose` code, which might not be the code that it received from the remote end and this is the handling of the remote end.... 
IMO this is clearly wrong. Reading the [relevant RFC](https://tools.ietf.org/html/rfc6455#page-36) I think that what we should do is:
1. handleEvent close with the code that was returned by the server. 
2. send close frame with the same code to the server. 
Here the question is, whether we also handle the second closer as well ? I think that we shouldn't.

File: core/engine_test.go (hunk 1 above)
Comment (imiric) [reply core/engine_test.go]: I thought I had another test failure because of the change, so I decided to update them all and avoid any unexpected effects.

But I just tested and most tests work fine with the fixed server implementation, so I reverted these changes in 2ac9618b, add added a comment to this test explaining this, and a small `FIXME` note, let me know if you agree.

File: js/modules/k6/ws/ws.go [hunk 6]
```diff
@@ -436,7 +436,7 @@ func (s *Socket) closeConnection(code int) error {
 			websocket.FormatCloseMessage(code, ""),
 			time.Now().Add(writeWait),
 		)
-		if err != nil {
+		if err != nil && err != websocket.ErrCloseSent {
```
Comment (MStoykov) [inline js/modules/k6/ws/ws.go]: Why, though ? I mean it's an error. Also IMO if this happens k6 has a bug, as I am pretty sure we should stop sending data after we close the connection

File: js/modules/k6/ws/ws_test.go (hunk 3 above)
Comment (imiric) [reply js/modules/k6/ws/ws_test.go]: D'oh! Should've RTFM...

Thanks, yeah, I assumed it was because of no global event loop. This should be straightforward to fix once that's in.

I pushed 2ac9618b reverting most of the WS URL updates, so now we're using all 4 variants. I don't think we can get rid of either of them for now, unfortunately.

File: js/modules/k6/ws/ws_test.go (hunk 4 above)
Comment (imiric) [reply js/modules/k6/ws/ws_test.go]: Ah, this was a wrong edit, this assert is actually part of the previous test. I'm not asserting any metric emissions in the `server_close_*` tests, didn't think it was necessary.

Will fix this (move this assert above).

File: js/modules/k6/ws/ws.go (hunk 5 above)
Comment (imiric) [reply js/modules/k6/ws/ws.go]: I considered this, but ultimately left it as is since it's not technically against the RFC:

> (When sending a Close frame in response, the endpoint typically echos the status code it received.)

This is poorly defined, but I would interpret it as "MAY"/"SHOULD", so opted against being fully compliant for now, and fixing this specific issue in this PR.

Would it make sense to open an issue and address WS compatibility in another PR?

File: js/modules/k6/ws/ws.go (hunk 6 above)
Comment (imiric) [reply js/modules/k6/ws/ws.go]: Good point, will look into this again. It seems we're sending a close twice, so this shouldn't be needed.

File: js/modules/k6/ws/ws_test.go (hunk 4 above)
Comment (imiric) [reply js/modules/k6/ws/ws_test.go]: Fixed in 58ae5f78.

File: js/modules/k6/ws/ws.go (hunk 6 above)
Comment (imiric) [reply js/modules/k6/ws/ws.go]: So I'm starting to dislike gorilla/websocket...

Take a look at a8980133.

If not explicitly set, `websocket.Conn` [uses a custom close handler](https://github.com/loadimpact/k6/blob/05e8740b88325d15e853f6f37d26b2e9cf76e2e5/vendor/github.com/gorilla/websocket/conn.go#L1062-L1069) that is [called a few layers below `conn.ReadMessage()`](https://github.com/loadimpact/k6/blob/05e8740b88325d15e853f6f37d26b2e9cf76e2e5/vendor/github.com/gorilla/websocket/conn.go#L903).

We can't simply do `conn.SetCloseHandler(socket.closeConnection))` because that introduces race conditions when calling the Goja runtime between the parent `WS.Connect()` goroutine and the `go readPump(...)` (`conn.ReadMessage()`) one. I suppose we could add more synchronization here, but `Connect()` is already overly complicated, and I would instead suggest switching away from gorilla/websocket, for at least a couple of reasons:

- Its API is quite unfriendly, and as we've seen, it can be very easy to write non-compliant clients and servers.
- It doesn't make sense that a close handler is called while reading a message. This seems like a poorly thought-out feature since it forces the user to manually synchronize if specifying a custom close handler, as `ReadMessage()` should always be run in a separate goroutine.

At first glance it seems like [nhooyr/websocket](https://github.com/nhooyr/websocket) might be a good alternative with a saner API that would help us clean up the current implementation.

But let me know if you think there's a better way of avoiding the duplicate close issue than making `websocket.Conn.handleClose` a noop or doing this `err != websocket.ErrCloseSent` check.

Comment (MStoykov) [reply js/modules/k6/ws/ws.go]: Given the fact that in the vast majority of cases (IMO) what gorilla is doing is what should be done and we should've read the docs to begin with, I would consider it not a great design, but not a poor one as well.
 I did take a look at the other lib and while I like it, given it comparisons below I am more inclined to go with the much more performant (apparently, I haven't benchmarked) https://github.com/gobwas/ws . But I agree with both you and the author that the gorilla one is very old and doesn't support a lot of things that it should, just because ... well it needs to be backwards compatible :) 

But in all cases ... I would consider this low prio and would probably want to do it when we have event loops and we are redoing the whole ws api, as I don't want to change some parts of the behaviour and break the current api :). 
Let's create an issue linking to this comments?
cc @na--  @cuonglm

File: js/modules/k6/ws/ws.go (hunk 5 above)
Comment (imiric) [reply js/modules/k6/ws/ws.go]: I added a `readPump()` test in 0f96be17.

This doesn't test the entire flow of k6 sending a close with the same code, but that would involve a more complicated `WS.Connect()` test I'd rather leave after the WS refactor when this is hopefully easier to test.

File: js/modules/k6/ws/ws.go (hunk 6 above)
Comment (imiric) [reply js/modules/k6/ws/ws.go]: Agreed on the priority and leaving the refactor for later.

Let me know if I should create an issue about this.

**Comment by imiric** [comment]
@MStoykov @na-- @cuonglm Let me know if there's anything pending here.

I noticed a slight timing issue when triggering the JS error handler where sometimes the handler is not called even when the server suddenly closes the connection without sending the control frame. The close handler is always called and the test run still ends successfully, but the error handler is sometimes missed.

Should I fix this timing issue here (could take a while) or would it be better to merge this and open a new issue about it?

File: js/modules/k6/ws/ws_test.go [hunk 7]
```diff
@@ -504,3 +539,53 @@ func TestTLSConfig(t *testing.T) {
...
+				continue
+			case <-time.After(time.Second):
+				t.Errorf("Read timed out")
+				break readChans
+			}
+		}
+	}
+
+	// Ensure all close code asserts passed
+	assert.Equal(t, numAsserts, len(closeCodes))
```
Comment (MStoykov) [inline js/modules/k6/ws/ws_test.go]: This is probably good idea to be with [subTests](https://golang.org/pkg/testing/#hdr-Subtests_and_Sub_benchmarks) it will mean that that defer will execute between the different closecodes tests ;).

File: js/modules/k6/ws/ws_test.go [hunk 8]
```diff
@@ -504,3 +539,53 @@ func TestTLSConfig(t *testing.T) {
...
 }
+
+func TestReadPump(t *testing.T) {
+	var closeCode int
+	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+		conn, err := (&websocket.Upgrader{}).Upgrade(w, r, w.Header())
+		assert.NoError(t, err)
+		closeMsg := websocket.FormatCloseMessage(closeCode, "")
+		_ = conn.WriteControl(websocket.CloseMessage, closeMsg, time.Now().Add(time.Second))
+	}))
```
Comment (MStoykov) [inline js/modules/k6/ws/ws_test.go]: You could've used the httpmultibin and added a custom handler as we do in https://github.com/loadimpact/k6/blob/4f04c7fa523ca46c9d48b3407d82d3edf33815cb/js/modules/k6/http/request_test.go#L157-L172 . This approach is definitely faster, and is okay this time, but if you didn't know you could I am sharing it for future cases ;)

File: js/modules/k6/ws/ws_test.go [hunk 9]
```diff
@@ -504,3 +539,53 @@ func TestTLSConfig(t *testing.T) {
 	})
 	assertSessionMetricsEmitted(t, stats.GetBufferedSamples(samples), "", sr("WSSBIN_URL/ws-close"), 101, "")
 }
+
+func TestReadPump(t *testing.T) {
+	var closeCode int
```
Comment (MStoykov) [inline js/modules/k6/ws/ws_test.go]: I don't like this shared variable

File: js/modules/k6/ws/ws_test.go (hunk 8 above)
Comment (imiric) [reply js/modules/k6/ws/ws_test.go]: Thanks, I'm aware of `httpmultibin` (I rewrote the WS handlers in d34bce5a4 ;)), but I prefer not using it here since this is very specific to this particular test, as I needed to modify the close code returned by the server, and I didn't want to pollute or mess around with httpmultibin.

Comment (na--) [reply js/modules/k6/ws/ws_test.go]: I think @MStoykov meant that you can use `httpmultibin`, but define custom _local_ HTTP/WS handlers only in your particular test, no need to pollute the global one. But in any case, this is such a simple test that it wouldn't have made any difference, so I don't think it matters.

File: js/modules/k6/ws/ws_test.go (hunk 9 above)
Comment (imiric) [reply js/modules/k6/ws/ws_test.go]: Meh, I'm ambivalent about it. It's there so each test can alter the close code returned by the server. Yes, we can't parallelize them this way, but these tests run in milliseconds, so it shouldn't be needed.

I could fix this by making the handler a struct with a `closeCode` field and a `Handle` function or creating different endpoints to handle different close codes, but they both seem overkill for this test.

Let me know if you feel strongly about this, and please propose your preferred way of fixing it.

File: js/modules/k6/ws/ws_test.go (hunk 7 above)
Comment (imiric) [reply js/modules/k6/ws/ws_test.go]: Thanks, resolved in ded5fe3b.

File: js/modules/k6/ws/ws_test.go [hunk 10]
```diff
@@ -504,3 +539,55 @@ func TestTLSConfig(t *testing.T) {
...
+
+	closeCodes := []int{websocket.CloseNormalClosure, websocket.CloseGoingAway, websocket.CloseInternalServerErr}
+
+	numAsserts := 0
+	srvURL := "ws://" + srv.Listener.Addr().String()
+
+	// Ensure readPump returns the response close code sent by the server
+	for _, code := range closeCodes {
+		t.Run(strconv.Itoa(code), func(t *testing.T) {
+			closeCode = code
```
Comment (golangcibot) [inline js/modules/k6/ws/ws_test.go]: Using the variable on range scope `code` in function literal (from `scopelint`)

File: js/modules/k6/ws/ws_test.go [hunk 11]
```diff
@@ -504,3 +539,55 @@ func TestTLSConfig(t *testing.T) {
...
+			msgChan := make(chan []byte)
+			errChan := make(chan error)
+			closeChan := make(chan int)
+			go readPump(conn, msgChan, errChan, closeChan)
+
+		readChans:
+			for {
+				select {
+				case responseCode := <-closeChan:
+					assert.Equal(t, code, responseCode)
```
Comment (golangcibot) [inline js/modules/k6/ws/ws_test.go]: Using the variable on range scope `code` in function literal (from `scopelint`)

File: js/modules/k6/ws/ws.go [hunk 12]
```diff
@@ -454,21 +462,19 @@ func (s *Socket) closeConnection(code int) error {
...
-				// Emit the error if it is not CloseNormalClosure
-				// and the error is not  originated from closing the socket ourselves with `CloseGoingAway`
+			if websocket.IsUnexpectedCloseError(
+				err, websocket.CloseNormalClosure, websocket.CloseGoingAway) {
+				// Report an unexpected closure
 				errorChan <- err
 			}
-
-			//CloseGoingAway errors are ignored
+			code := websocket.CloseGoingAway
```
Comment (golangcibot) [inline js/modules/k6/ws/ws.go]: assignments should only be cuddled with other assignments (from `wsl`)

File: js/modules/k6/ws/ws.go [hunk 13]
```diff
@@ -454,21 +462,19 @@ func (s *Socket) closeConnection(code int) error {
...
+			if e, ok := err.(*websocket.CloseError); ok {
```
Comment (golangcibot) [inline js/modules/k6/ws/ws.go]: only one cuddle assignment allowed before if statement (from `wsl`)

File: js/modules/k6/ws/ws_test.go [hunk 14]
```diff
@@ -504,3 +539,55 @@ func TestTLSConfig(t *testing.T) {
 	})
 	assertSessionMetricsEmitted(t, stats.GetBufferedSamples(samples), "", sr("WSSBIN_URL/ws-close"), 101, "")
 }
+
+func TestReadPump(t *testing.T) {
+	var closeCode int
+	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
```
Comment (golangcibot) [inline js/modules/k6/ws/ws_test.go]: assignments should only be cuddled with other assignments (from `wsl`)

File: js/modules/k6/ws/ws_test.go [hunk 15]
```diff
@@ -504,3 +539,55 @@ func TestTLSConfig(t *testing.T) {
...
+		conn, err := (&websocket.Upgrader{}).Upgrade(w, r, w.Header())
+		assert.NoError(t, err)
+		closeMsg := websocket.FormatCloseMessage(closeCode, "")
+		_ = conn.WriteControl(websocket.CloseMessage, closeMsg, time.Now().Add(time.Second))
+	}))
+	defer srv.Close()
```
Comment (golangcibot) [inline js/modules/k6/ws/ws_test.go]: only one cuddle assignment allowed before defer statement (from `wsl`)

File: js/modules/k6/ws/ws_test.go (hunk 9 above)
Comment (MStoykov) [reply js/modules/k6/ws/ws_test.go]: if it runs okay with `go test -race -count 200` I am fine. otherwise I would advice you to use [atomic](https://golang.org/pkg/sync/atomic/)

Comment (imiric) [reply js/modules/k6/ws/ws_test.go]: @MStoykov Yes, `go test -v -race -count 200 -run 'TestReadPump' ./js/modules/k6/ws` passes.

**Comment by imiric** [comment]
Thanks @na--. Hopefully the tests showcase the correct behavior now, whereas previously k6 would hang when the server closed the connection.

And the two differing WS endpoint groups (plain and with `-invalid` suffix) are there because our previous WS test handler (in `httpmultibin`) didn't implement closing according to the WS spec, so instead of removing it and having to possibly rewrite a lot of existing tests, I opted for leaving both the "invalid" ("noncompliant" would probably be a better term) endpoints, and adding new ones that implement closing correctly (hopefully...).

Let me know if you need more details.
