### PR TITLE
Fix break line after password input (loadimpact#1703)

### LINKED ISSUE #1703: There is no new line after `password` prompt for login command
The screenshot shows it very clearly :). 
image

I expect that the reading of the password just swallows the newline as well so it doesn't get printed ?

### PR DESCRIPTION
**Pull request by paroar**
Sorry, I deleted the branch instead of update the PR and now is duplicated. Anyway thanks for the pointers before.

Closes #1703

### CODE REVIEW

File: ui/form.go [hunk 1]
```diff
@@ -65,6 +65,9 @@ func (f Form) Run(r io.Reader, w io.Writer) (map[string]interface{}, error) {
 
 			color.Set(color.FgCyan)
 			s, err := field.GetContents(r)
+			if displayLabel == "Password" {
```
Comment (na--) [inline ui/form.go:68]: This would be better off as a [type assertion](https://tour.golang.org/methods/15), ensuring that `field` is of type `PasswordField`.

**Review by na-- — APPROVED** [review]

**Review by imiric — APPROVED** [review]
Thanks for this!
