### PR TITLE
Fix wrong name tag for HTTP metrics from redirects

### LINKED ISSUE #1474: Wrong name tag for HTTP metrics from redirects
When you make HTTP requests with redirects, the `name` tag in the generated metrics is wrong - it contains the original URL... For example, if you run the following script:
```js
import http from 'k6/http';

export default function () {
    http.get("https://httpbin.test.k6.io/redirect-to?url=https%3A%2F%2Fhttpbin.test.k6.io%2Fanything");
}
```

with `k6 run --out json=results.json script.js`, and then filter the generated metrics with to get the `url` tags with `jq '. | select(.type=="Point" and .metric == "http_reqs") | .data.tags.url' results.json`, you'd get this:
```
"https://httpbin.test.k6.io/redirect-to?url=https%3A%2F%2Fhttpbin.test.k6.io%2Fanything"
"https://httpbin.test.k6.io/anything"
```

which is perfectly fine, but if you get the `name` tag with `jq '. | select(.type=="Point" and .metric == "http_reqs") | .data.tags.name' results.json`, you'd get:
```
"https://httpbin.test.k6.io/redirect-to?url=https%3A%2F%2Fhttpbin.test.k6.io%2Fanything"
"https://httpbin.test.k6.io/redirect-to?url=https%3A%2F%2Fhttpbin.test.k6.io%2Fanything"
```

If we had explicitly specified such a `name` tag, or anything other in the `http.get()` `params`, it would be fine. But in this case, the result of these 2 commands should have been identical...

The consequence of this in the cloud is even worse, since the [`name` tag is used for request grouping](https://k6.io/docs/using-k6/http-requests#url-grouping), it looks like this:
Screenshot_2020-05-29 Test run 739754 - app k6 io

### PR DESCRIPTION
**Pull request by imiric**
Closes #1474

The root cause was reusing the same 'name' tag for all requests processed by a transport. In the case of redirects and digest auth the transport would process more than one request and needs to update the 'name' tag in the same way as 'url' is. For the initial request we need the originally parsed one to be consistent with the credential masking feature (as this gets stripped in the request passed to `RoundTrip()`), and tags for subsequent requests will be dynamically generated.

I'm not sure if this confirms @MStoykov's gut feeling that it will break aggregation somehow, but I'd argue this is the correct approach so we'll have to deal with it. :smile:

I didn't add more tests for this as the current ones are quite thorough.

### CODE REVIEW

File: lib/netext/httpext/transport.go [hunk 1]
```diff
@@ -115,9 +122,28 @@ func (t *transport) measureAndEmitMetrics(unfReq *unfinishedRequest) *finishedRe
...
 		if enabledTags.Has(stats.TagURL) {
-			u := URL{u: unfReq.request.URL, URL: unfReq.request.URL.String()}
-			tags["url"] = u.Clean()
+			// Tag the first request with the original clean URL and
+			// subsequent ones (e.g. part of a redirect chain or digest auth)
+			// with the updated clean URL.
+			if t.origURL != nil && t.numProcReqs == 1 {
+				tags["url"] = t.origURL.Clean()
+			} else {
+				tags["url"] = cleanURL
```
Comment (na--) [inline lib/netext/httpext/transport.go:133]: hmm I might be missing something, but if `t.numProcReqs == 1`, in what would cause `t.origURL.Clean()` be different than `cleanURL`?

Comment (na--) [reply lib/netext/httpext/transport.go:133]: ah, nevermind, I should read the PR description before making stupid comments... :man_facepalming: :sweat_smile:

Comment (imiric) [reply lib/netext/httpext/transport.go:133]: Yeah, sorry, maybe I wasn't clear enough. The thing is that `cleanURL` is based on the current request being processed as received in `RoundTrip()`, which doesn't have the `username:password`, so cleaning it would cause the original URL as it appears in the script to be tagged without the masked credentials (e.g. `https://<host><path>`), which is inconsistent with the current behavior.

**Comment by na--** [comment]
After my initial dumb comment, I'll try to make one that's a bit more informed, albeit in the same direction... :sweat_smile: 

> For the initial request we need the originally parsed one to be consistent with the credential masking feature (as this gets stripped in the request passed to RoundTrip()), and tags for subsequent requests will be dynamically generated.

Looking at this code: https://github.com/loadimpact/k6/blob/5ff4a76a4a08241ce061fcc449be585f7f707e6a/lib/netext/httpext/digest_transport.go#L43-L57

I'm thinking we shouldn't bother with `numProcReqs` and the special handling at all, since this logic is trying to mask something we don't actually do. The current HTTP digest logic actually makes an initial request without authentication, so we should emit it like it happens, not try to mask it. 

We should definitely fix the current dumb digest implementation (https://github.com/loadimpact/k6/issues/800), but we shouldn't try to pretend it doesn't do the stupid things it does...

File: lib/netext/httpext/transport.go (hunk 1 above)
Comment (na--) [reply lib/netext/httpext/transport.go:133]: sorry, somehow missed you replied here before posting https://github.com/loadimpact/k6/pull/1570#issuecomment-662941482

**Comment by imiric** [comment]
@na-- Ah, even better! I thought this request came from stdlib and not from our code. Thanks, will fix.

**Comment by na--** [comment]
Unfortunately, stdlib still doesn't have digest authentication, so we've had to make do with external libraries. The current one is the second attempt IIRC, and it also [sucks](https://github.com/loadimpact/k6/issues/800#issuecomment-632776017). As explained in that issue, we need some substantial refactoring, including a per-VU credential cache or something like that, to fix the issue we currently have of making 2 HTTP requests every time... :disappointed:

**Comment by imiric** [comment]
@na-- Unfortunately, I don't think we can get rid of some wonkiness here. :-/

Besides the digest credential masking, the original URL name is also needed to keep [the metrics aggregatable on the same query params](https://github.com/loadimpact/k6/blob/5ff4a76a4a08241ce061fcc449be585f7f707e6a/js/modules/k6/http/request_test.go#L979). So @MStoykov was right, and this will make subsequent requests not part of this group, but there's a point to be made that they should be aggregated differently since the original query string isn't passed to these later requests anyway. Though the `name` tag seems to be abused for several purposes, so we might want to rethink that at some point.

I got rid of the counter in 4f309411, but some state change is still needed to set this tag for only the first request. Wiping the string after the first pass seems slightly better, but still not great. Let me know.

File: lib/netext/httpext/transport.go [hunk 2]
```diff
@@ -115,9 +118,26 @@ func (t *transport) measureAndEmitMetrics(unfReq *unfinishedRequest) *finishedRe
...
+		}
+
+		if _, ok := tags["name"]; !ok && enabledTags.Has(stats.TagName) {
+			// If a name tag is already set in the script, use it for all requests
+			// processed by this transport. Otherwise, use the original URL name
+			// to preserve any escaped query string arguments, but only for the
+			// first request in the chain.
+			if t.origURLName != "" {
+				tags["name"] = t.origURLName
+				t.origURLName = ""
```
Comment (na--) [inline lib/netext/httpext/transport.go:133]: This still seems strange... if a `name` tag was set by the user in the script, wouldn't it be in the `t.tags` map above? :confused:

Comment (na--) [reply lib/netext/httpext/transport.go:133]: ah, nevermind, "spoke" too soon again - this comment is about the `if _, ok := tags["name"]; !ok` part of the check...

still, I continue to not understand why we need the original URL, when `cleanURL` should suffice :confused:

Comment (imiric) [reply lib/netext/httpext/transport.go:133]: Because otherwise [this test](https://github.com/loadimpact/k6/blob/5ff4a76a4a08241ce061fcc449be585f7f707e6a/js/modules/k6/http/request_test.go#L979) fails.

I'm trying to see if I can clean it again in the transport the same way while preserving the escaped query args, but I'm not functioning on all cylinders today. :-/

Comment (na--) [reply lib/netext/httpext/transport.go:133]: > Because otherwise [this test](https://github.com/loadimpact/k6/blob/5ff4a76a4a08241ce061fcc449be585f7f707e6a/js/modules/k6/http/request_test.go#L979) fails.

Ahhh... welll... :hankey: :sweat_smile: Yeah, I'll have to scratch my head about this some more, but the current version of this PR might be as good as it gets... :disappointed: Not sure why anyone added [this](https://k6.io/docs/using-k6/http-requests#url-grouping) (on the bottom of that section) [funky](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_templates) way of specifying URLs, but now we have to live with it... :sob: It implies a `name` tag, but it doesn't specify it, instead using this weird k6-specific [`URL` struct](https://github.com/loadimpact/k6/blob/80d3b06a28c8612846cfcbe8783100e84015d394/lib/netext/httpext/request.go#L51-L57), which of course we can't propagate in an [`http.RoundTrippter`](https://golang.org/pkg/net/http/#RoundTripper) :sob: And thus, I finally understand the purpose of all of the weird fixes in this PR :sweat_smile: 

Let's discuss this on Monday again, but I'm thinking that if someone uses something like this:
```js
http.get(http.url`http://example.com/posts/${id}`)
```
 we probably should consider it as if they used
```
http.get(`http://example.com/posts/${id}`, {tags: {name: 'http://example.com/posts/${}'}})
```

That is, if there are any redirects in the course of that HTTP request, all of their `name` tags should be 'http://example.com/posts/${}'. Or, said otherwise, https://github.com/loadimpact/k6/issues/1474 is not a bug when the user has explicitly used the `http.url` tagged template.

Comment (imiric) [reply lib/netext/httpext/transport.go]: OK, I think that should be the case in 62f91845. The only wonky thing is the obscure `preq.URL.Name != preq.URL.CleanURL` check, which works when a tagged template string is used.

This does break the masked credentials behavior for digest auth, i.e. the generated `name` tag in these cases won't be `https://****:****@<host>...` anymore, but `https://<host>`. I discussed this with @na-- the other day, so this might be acceptable, and if so we should mention it in the release notes.

File: lib/netext/httpext/transport.go [hunk 3]
```diff
@@ -115,9 +115,17 @@ func (t *transport) measureAndEmitMetrics(unfReq *unfinishedRequest) *finishedRe
...
+		cleanURL := URL{u: unfReq.request.URL, URL: unfReq.request.URL.String()}.Clean()
 		if enabledTags.Has(stats.TagURL) {
-			u := URL{u: unfReq.request.URL, URL: unfReq.request.URL.String()}
-			tags["url"] = u.Clean()
+			tags["url"] = cleanURL
+		}
+
+		if _, ok := tags["name"]; !ok && enabledTags.Has(stats.TagName) {
+			tags["name"] = cleanURL
+		}
```
Comment (MStoykov) [inline lib/netext/httpext/transport.go:125]: I would've really prefered it, if cleanURL is created only if it's needed :D

File: js/modules/k6/http/request_test.go [hunk 4]
```diff
@@ -181,7 +181,7 @@ func TestRequestAndBatch(t *testing.T) {
 			}
 
 			assert.Equal(t, 10, reqsCount)
-			assertRequestMetricsEmitted(t, bufSamples, "GET", sr("HTTPBIN_URL/get"), sr("HTTPBIN_URL/redirect/9"), 200, "")
+			assertRequestMetricsEmitted(t, bufSamples, "GET", sr("HTTPBIN_URL/get"), sr("HTTPBIN_URL/get"), 200, "")
```
[the remark this answers is not in the document]
Comment (na--) [reply js/modules/k6/http/request_test.go:184]: I don't understand the question, sorry.

[the remark this answers is not in the document]
Comment (MStoykov) [reply js/modules/k6/http/request_test.go:184]: I don't think 
```golang
 			assertRequestMetricsEmitted(t, bufSamples, "GET", url, "", 200, "") 
```
should mean 
```golang
 			assertRequestMetricsEmitted(t, bufSamples, "GET", url, url, 200, "") 
```
I also do think that it will be nice if ... I dunno this is 
```golang
 			assertRequestMetricsEmitted(t, bufSamples, expectmetric{
                             method: "GET", 
                             url: url, 
                             name:"",
                             status: 200,
                             whateverThisIs: "",
                        }) 
```
For this PR maybe just write the `name` for the other tests, instead of leaving it `""`

[the remark this answers is not in the document]
Comment (na--) [reply js/modules/k6/http/request_test.go:184]: Ahhh, ok, yeah, `url, ""` is confusing, :+1: :+1: for `url, url,`... A full refactoring of the test can wait for a future PR though :smile:

[the remark this answers is not in the document]
Comment (imiric) [reply js/modules/k6/http/request_test.go:186]: I added the redirect checks in 70144e8f, and while I agree that the `name = url` override is unnecessary, I'd rather leave that change for a follow-up PR.

File: lib/netext/httpext/transport.go (hunk 3 above)
Comment (imiric) [reply lib/netext/httpext/transport.go]: I changed this in 8872f4ab, at the expense of duplication, though I'm not sure it will be more efficient overall, as most of the time both `url` and `name` tags will be provided. We can add additional checks, but I don't want to complicate this too much.

File: js/modules/k6/http/request_test.go [hunk 5]
```diff
@@ -839,9 +841,9 @@ func TestRequestAndBatch(t *testing.T) {
 
 					sampleContainers := stats.GetBufferedSamples(samples)
 					assertRequestMetricsEmitted(t, sampleContainers[0:1], "GET",
-						sr("HTTPBIN_IP_URL/digest-auth/auth/bob/pass"), urlExpected, 401, "")
+						urlRaw, "", 401, "")
```
Comment (MStoykov) [inline js/modules/k6/http/request_test.go:844]:
```suggestion
						urlRaw, urlRaw, 401, "")
```

File: js/modules/k6/http/request_test.go [hunk 6]
```diff
@@ -839,9 +841,9 @@ func TestRequestAndBatch(t *testing.T) {
...
 					assertRequestMetricsEmitted(t, sampleContainers[1:2], "GET",
-						sr("HTTPBIN_IP_URL/digest-auth/auth/bob/pass"), urlExpected, 200, "")
+						urlRaw, "", 200, "")
```
Comment (MStoykov) [inline js/modules/k6/http/request_test.go:846]:
```suggestion
						urlRaw, urlRaw, 200, "")
```

File: js/modules/k6/http/request_test.go [hunk 7]
```diff
@@ -1912,12 +1914,10 @@ func TestDigestAuthWithBody(t *testing.T) {
...
+	urlRaw := tb.Replacer.Replace(
 		"http://HTTPBIN_IP:HTTPBIN_PORT/digest-auth-with-post/auth/testuser/testpwd")
-	expectedName := tb.Replacer.Replace(
-		"http://****:****@HTTPBIN_IP:HTTPBIN_PORT/digest-auth-with-post/auth/testuser/testpwd")
 
 	sampleContainers := stats.GetBufferedSamples(samples)
-	assertRequestMetricsEmitted(t, sampleContainers[0:1], "POST", expectedURL, expectedName, 401, "")
-	assertRequestMetricsEmitted(t, sampleContainers[1:2], "POST", expectedURL, expectedName, 200, "")
+	assertRequestMetricsEmitted(t, sampleContainers[0:1], "POST", urlRaw, "", 401, "")
+	assertRequestMetricsEmitted(t, sampleContainers[1:2], "POST", urlRaw, "", 200, "")
```
Comment (MStoykov) [inline js/modules/k6/http/request_test.go:1922]:
```suggestion
	assertRequestMetricsEmitted(t, sampleContainers[0:1], "POST", urlRaw, urlRaw, 401, "")
	assertRequestMetricsEmitted(t, sampleContainers[1:2], "POST", urlRaw, urlRaw, 200, "")
```

File: js/modules/k6/http/request_test.go [hunk 8]
```diff
@@ -702,7 +704,7 @@ func TestRequestAndBatch(t *testing.T) {
 						stats.GetBufferedSamples(samples),
 						"GET",
 						sr("HTTPBIN_IP_URL/get"),
-						sr("HTTPBIN_IP_URL/redirect-to?url=HTTPSBIN_URL/set-cookie-and-redirect"),
+						"",
```
Comment (MStoykov) [inline js/modules/k6/http/request_test.go:707]: Can we change to specifying the `name` as well here, see https://github.com/loadimpact/k6/pull/1570/files#r460821904 and the proposed changes below

Comment (imiric) [reply js/modules/k6/http/request_test.go]: Resolved by a780923f.

File: js/modules/k6/http/request_test.go (hunk 7 above)
Comment (imiric) [reply js/modules/k6/http/request_test.go]: Resolved by a780923f.

File: js/modules/k6/http/request_test.go (hunk 6 above)
Comment (imiric) [reply js/modules/k6/http/request_test.go]: Resolved by a780923f.

File: js/modules/k6/http/request_test.go (hunk 5 above)
Comment (imiric) [reply js/modules/k6/http/request_test.go]: Resolved by a780923f.

File: lib/netext/httpext/transport.go (hunk 3 above)
Comment (imiric) [reply lib/netext/httpext/transport.go]: Changed this to check all redirects in e6b65c87.

File: js/modules/k6/http/request_test.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (imiric) [reply js/modules/k6/http/request_test.go:214]: Changed this to check all redirects in e6b65c87.

File: lib/netext/httpext/transport.go [hunk 9]
```diff
@@ -116,8 +116,17 @@ func (t *transport) measureAndEmitMetrics(unfReq *unfinishedRequest) *finishedRe
...
-			u := URL{u: unfReq.request.URL, URL: unfReq.request.URL.String()}
-			tags["url"] = u.Clean()
+			cleanURL := URL{u: unfReq.request.URL, URL: unfReq.request.URL.String()}.Clean()
+			tags["url"] = cleanURL
+		}
+
+		if _, ok := tags["name"]; !ok && enabledTags.Has(stats.TagName) {
+			cleanURL := URL{u: unfReq.request.URL, URL: unfReq.request.URL.String()}.Clean()
+			tags["name"] = cleanURL
+		}
```
Comment (MStoykov) [inline lib/netext/httpext/transport.go:126]: To be honest given the high amount of code that will execute those, I would prefer if we do actually do this in (pseudo code):
```
var urlEnabled = enabledTags.Has(url)...;
var nameToBeSet = <the whole if>;
if urlEnabled || nameToBeSet {
  cleanUrl = ...
  if urlEnabled { 
    tags["url"] cleanURL
  } 
  if name....
```
both are likely to be true always and I would argue it isn't the worst code out there

**Review by MStoykov — APPROVED** [review]
LGTM, I haven't tested it ... but the test look fine. 
I vode tentively for leaving this for v0.29.0 (and merging it early on this time ;) ) just because of the nature of the change and (IMO) low priority of the issue given this has been the case forever and nobody has complained

**Comment by na--** [comment]
We've been delaying this for quite a while, so I vote for v0.28.0. If there's a bug in this, it's unlikely to be worse than the bug that currently exists... The fact that nobody has commented on it probably means that most people use `url` and not `name`, or they just haven't noticed the issue in the cloud tests...

File: lib/netext/httpext/transport.go (hunk 9 above)
Comment (imiric) [reply lib/netext/httpext/transport.go]: Sure, makes sense, see 8ee1d1ca.

**Review by na-- — APPROVED** [review]
LGTM

File: lib/netext/httpext/transport.go [hunk 10]
```diff
@@ -115,9 +115,20 @@ func (t *transport) measureAndEmitMetrics(unfReq *unfinishedRequest) *finishedRe
...
-			u := URL{u: unfReq.request.URL, URL: unfReq.request.URL.String()}
-			tags["url"] = u.Clean()
+		urlEnabled := enabledTags.Has(stats.TagURL)
+		nameEnabled := enabledTags.Has(stats.TagName)
+		if urlEnabled || nameEnabled {
+			cleanURL := URL{u: unfReq.request.URL, URL: unfReq.request.URL.String()}.Clean()
+			if urlEnabled {
+				tags["url"] = cleanURL
+			}
+			if _, ok := tags["name"]; !ok && nameEnabled {
```
Comment (MStoykov) [inline lib/netext/httpext/transport.go:125]: I am pretty sure I am becoming a PITA, but can you move the `_, ok := tags["name"]; !ok` in the above if? or better yet in the `nameEnabled` ;)

Comment (imiric) [reply lib/netext/httpext/transport.go]: > I am pretty sure I am becoming a PITA

Only a bit :)

Is 413d0fe0 what you had in mind? I think I preferred the previous version, but out of curiosity, why is this better?

**Review by na-- — DISMISSED** [review]
Can we (squash+)merge this now? :sweat_smile:

File: lib/netext/httpext/transport.go (hunk 10 above)
Comment (MStoykov) [reply lib/netext/httpext/transport.go]: you could have had `name` set and `url` disabled and you would've stilled cleaned the url and then found out you didn't need it

**Review by MStoykov — APPROVED** [review]

**Comment by imiric** [comment]
Sorry guys, please approve one last time. I wanted to squash the fix separately from the `.gitignore` change, so had to do it manually.

**Review by na-- — APPROVED** [review]

**Review by MStoykov — APPROVED** [review]
No problem @imiric ;)
