### PR TITLE
Fix externally-controlled maxVUs scaling

### LINKED ISSUE #1511: Unable to scale maxVUs down in externally-controlled executor
In v0.26.2 it was possible to scale `maxVUs` arbitrarily using the REST API or the helper `scale -m` command.

On the current `new-schedulers` branch (2f150f2e), it's only possible to scale `maxVUs` up, but not back down, and no errors are returned when attempting to do so.

## Environment

- k6 version: `new-schedulers` (2f150f2e)
- OS and version: Linux
- Docker version and image, if applicable:

## Expected Behavior

- It should be possible to scale `maxVUs` down to the initial `maxVUs` setting.
- Trying to scale `maxVUs` below the initial `maxVUs` setting should return an error. This is a slight breaking change from 1007 in order to allow VU sharing between executors.

## Actual Behavior

`k6 scale -m N` where `N` is below the currently set `maxVUs` value (whether that was the initial value or one scaled up to with `k6 scale -m` previously) is silently ignored, and the executor remains with the previous value.

## Steps to Reproduce the Problem

1. Given the following `script.js`:
```js
import { sleep } from 'k6';

export let options = {
  scenarios: {
    adjustable_at_will: {
      executor: "externally-controlled",
      vus: 0,
      maxVUs: 20,
      duration: "10m",
    },
  }
};

export default function () {
  sleep(1);
}
```
2. Run `k6 run script.js`.
3. In another terminal, run `k6 scale -m 50`. Note the `vus-max: "50"` in the output.
4. Run `k6 scale -m 20`. Note that `vus-max` remains at `50`.
5. Run `k6 scale -m 10`. Note that `vus-max` remains at `50` and no error is returned.

Also, make sure that the behavior of `scale -u` is also consistent, and returns errors in the same way as v0.26.2.

### PR DESCRIPTION
**Pull request by imiric**
Closes #1511

I'm not sure this is the right fix, and the test is a bit hacky, but let me know.

### CODE REVIEW

File: api/v1/status_routes.go [hunk 1]
```diff
@@ -98,8 +98,8 @@ func HandlePatchStatus(rw http.ResponseWriter, r *http.Request, p httprouter.Par
 			if status.VUs.Valid {
 				newConfig.VUs = status.VUs
 			}
-			if updateErr := executor.UpdateConfig(r.Context(), newConfig); err != nil {
-				apiError(rw, "Config update error", updateErr.Error(), http.StatusInternalServerError)
+			if updateErr := executor.UpdateConfig(r.Context(), newConfig); updateErr != nil {
+				apiError(rw, "Config update error", updateErr.Error(), http.StatusBadRequest)
```
Comment (imiric) [inline api/v1/status_routes.go:102]: @MStoykov We need that `errorcheck` linter ;)

Also note the change to a 400 response code here, which is what was expected by the test, and will probably make sense in most cases.

**Comment by imiric** [comment]
Hhmm the `test-prev-golang` failure seems like another flaky occurrence of #1485, though I got a `TestExternallyControlledRun` failure before, but the changes here shouldn't affect it(?).

File: lib/executor/externally_controlled.go [hunk 2]
```diff
@@ -479,6 +479,7 @@ func (rs *externallyControlledRunState) handleConfigChange(oldCfg, newCfg Extern
 				executionState.ReturnVU(rs.vuHandles[i].initVU, false)
 			}
 			rs.vuHandles[i] = nil
+			executionState.ModInitializedVUsCount(-1)
```
Comment (MStoykov) [inline lib/executor/externally_controlled.go:482]: Was *this* the actual issue of not scaling down ?

Comment (imiric) [reply lib/executor/externally_controlled.go:482]: Yes :D `initializedVUs` wasn't decremented anywhere. Though not sure if this is the right approach or place for it :-/

**Comment by imiric** [comment]
Phew, I think `TestExternallyControlledRun` should finally be flake-free :crossed_fingers: See fc48c46e.

I'll see if I can apply this same pattern to other executor tests to stabilize them. We should preferably have something like a `MiniExecutionScheduler` :smile: that would standardize a stable test structure and maybe allow inspection and expose some test helpers.

File: lib/executor/externally_controlled.go (hunk 2 above)
Comment (na--) [reply lib/executor/externally_controlled.go:482]: This should only be done when we're not returning the VU back to the buffer pool though, like this:
```
			if i < rs.startMaxVUs {
				// return the initial planned VUs to the common buffer
				executionState.ReturnVU(rs.vuHandles[i].initVU, false)
			} else {
				executionState.ModInitializedVUsCount(-1)
			}

```

Comment (na--) [reply lib/executor/externally_controlled.go:482]: To demonstrate, use the following options:
```js
export let options = {
    scenarios: {
        extc1: {
            executor: "externally-controlled",
            vus: 5,
            maxVUs: 10,
            duration: "10s",
        },
        const_loop_vus: {
            executor: "constant-vus",
            vus: 10,
            duration: "20s",
            startTime: "10s",
            gracefulStop: "0s",
        },
    },
};
```

see the `00/00 VUs` in the description here:
```
running (14.1s), 00/00 VUs, 139 complete and 15 interrupted iterations
extc1          ✓ [======================================] 05/10 VUs  10s   
const_loop_vus ✗ [======>-------------------------------] 10 VUs     04.1s/20s
```

**Comment by imiric** [comment]
@na-- See 64f30fcd with that change.

Though there are still some inconsistencies:

1. If two executors are started, for example:

```js
import http from 'k6/http';
import { sleep } from 'k6';

export let options = {
  scenarios: {
    adjustable_at_will: {
      executor: 'externally-controlled',
      vus: 0,
      maxVUs: 10,
      duration: '10m',
    },
    constant_vus: {
      executor: 'constant-vus',
      vus: 20,
      duration: '2m',
    },
  }
};

export default function() {
  sleep(0.2);
}
```

2. `k6 status` returns `vus: "20", vus-max: "30"`, taking into account the global counts.
   
3. Yet trying `k6 scale -u 30` will of course error out because of the `10` `maxVUs` configured for the externally-controlled exec. Similarly with `scale -m`, etc.
   

It's somewhat confusing that the API returns the global status, but can only modify externally-controlled parameters. Not sure how big of a problem this would be in practice, though it would be best to avoid any such inconsistencies. Maybe transparently convert any `scale` values to the externally-controlled config (i.e. `-u 30` actually becomes `-u 10`)? Or do you think just documenting this would be enough?

File: lib/executor/externally_controlled_test.go [hunk 3]
```diff
@@ -62,50 +64,71 @@ func TestExternallyControlledRun(t *testing.T) {
...
 	go func() {
 		defer wg.Done()
+		es.MarkStarted()
 		errCh <- executor.Run(ctx, nil)
+		es.MarkEnded()
 		close(doneCh)
 	}()
 
-	updateConfig := func(vus int) {
+	updateConfig := func(vus, maxVUs int, errMsg string) {
```
Comment (MStoykov) [inline lib/executor/externally_controlled_test.go:80]: seems to me that we could change them to `int64` without anything else being changed ?

Comment (imiric) [reply lib/executor/externally_controlled_test.go]: Indeed, thanks. Resolved in d84fe0ee.

I was trying to avoid having to explicitly use `int64()` everytime this is called, and forgot about the transparent `int` conversion.

Comment (MStoykov) [reply lib/executor/externally_controlled_test.go]: it's transparent `const` conversion ;)

**Comment by imiric** [comment]
#1357 strikes again :disappointed:

**Comment by na--** [comment]
hmm I think we should just document this, and fix it in the v2 REST API, whenever that is implemented...

**Comment by imiric** [comment]
OK, I'll mention it in the release notes and the new docs somewhere.
