### PR TITLE
Fix UI panic and login errors on mintty/Windows

### LINKED ISSUE #1559: panic: runtime error: integer divide by zero
Created because of https://community.k6.io/t/warn-0000-error-getting-terminal-size/767

## Environment
- k6 version: v0.27.0
- OS and version: Windows

## Expected Behavior
Running a script with k6 shouldn't panic, ever. 

## Actual Behavior
For some terminals, k6 isn't able to get the current terminal width (needed for the new responsive progressbars) for some unknown reason, so it emits this warning: 
```
 WARN[0000] error getting terminal size error=“The handle is invalid.”
```

then it panics with ` panic: runtime error: integer divide by zero` :disappointed: 

my theory is that this code works as intended and falls back to width of 80: https://github.com/loadimpact/k6/blob/62e1b53391c2b2a8cd9e7af1d6a0cd70bd6227db/cmd/ui.go#L255-L258

but then we zero it out when we suppress the error here: https://github.com/loadimpact/k6/blob/62e1b53391c2b2a8cd9e7af1d6a0cd70bd6227db/cmd/ui.go#L334-L338

### PR DESCRIPTION
**Pull request by imiric**
Closes #1559

Confirmed working on the latest Git Bash (2.27.0) and mintty 3.1.6 on Windows 10 x64 1903.

The "error getting terminal size" warning will still be shown and the progressbars will be static, but at least it doesn't panic :sweat_smile:

### CODE REVIEW

File: cmd/ui.go [hunk 1]
```diff
@@ -331,11 +332,17 @@ func showProgress(
...
 		case <-winch:
 			// More responsive progress bar resizing on platforms with SIGWINCH (*nix)
-			termWidth, _, _ = terminal.GetSize(fd)
+			termWidth, _, err = terminal.GetSize(fd)
+			if err != nil {
+				termWidth = defaultTermWidth
+			}
 		case <-ticker.C:
 			// Default ticker-based progress bar resizing
 			if winch == nil {
```
Comment (na--) [inline cmd/ui.go:341]: Hmm I think that if we fail to get the terminal width initially, we probably shouldn't even attempt to do it again?

Comment (imiric) [reply cmd/ui.go]: Hastily resolved in d17100b0?

File: cmd/ui.go [hunk 2]
```diff
@@ -330,12 +333,20 @@ func showProgress(
 			outMutex.Unlock()
 			return
 		case <-winch:
-			// More responsive progress bar resizing on platforms with SIGWINCH (*nix)
-			termWidth, _, _ = terminal.GetSize(fd)
+			if !errTermGetSize {
+				// More responsive progress bar resizing on platforms with SIGWINCH (*nix)
+				termWidth, _, err = terminal.GetSize(fd)
+				if err != nil {
```
Comment (imiric) [inline cmd/ui.go:339]: Maybe we can ignore checking this `err` if it failed the first time?

File: cmd/ui.go [hunk 3]
```diff
@@ -330,12 +333,20 @@ func showProgress(
...
+					termWidth = defaultTermWidth
+				}
+			}
 		case <-ticker.C:
 			// Default ticker-based progress bar resizing
-			if winch == nil {
-				termWidth, _, _ = terminal.GetSize(fd)
+			if !errTermGetSize && winch == nil {
```
Comment (MStoykov) [inline cmd/ui.go:345]: I still think that instead of here is a check for `winch`, we should
1. just call `ticker.Stop()` if `winch` won't be `nil` 
2. or for there to be 1 channel which is set to either `winch` or `ticker.C` depending on whether `winch` is supported.

Comment (MStoykov) [reply cmd/ui.go:345]: and if we are going to just not get the terminal size after the first error we can just as well set that channel to `nil` after the error and stop the ticker

Comment (imiric) [reply cmd/ui.go:345]: The thing is that we can't stop the ticker as that's what drives the progress bar refresh, so even if `winch != nil` (e.g. on Linux) both channels should be active. The `winch` one just makes the resizing more responsive.
