### PR TITLE
Make DNS resolver configurable

### LINKED ISSUE #726: Unexpected DNS caching
I’d better like to understand K6s behaviour in relation to DNS caching.

I’m trying to run tests against a couple of load balanced K8S clusters. The failover is managed by a traffic manager so once the traffic manager has detected a failure in one of the clusters it will update the DNS records so that traffic only hits the healthy cluster. I’ve tried to reduce the problem, described below.

# Steps to reproduce:

1. Create a performance test to run for 5m against a particular endpoint. E.g., https://gist.github.com/paulgrav/a8b6d77639b0d54774b499c5dfd660c6
2. Ensure that `host.name` points to a CNAME that returns HTML and has a TTL of 60s.
3. Run the test.
4. After one minute, update the CNAME for `host.name` to a domain that doesn’t resolve e.g., `foo.bar.asdf`

# Actual results:

All HTTP calls in the test succeed despite the CNAME record being changed to point to a domain that doesn’t resolve.

# Expected results:

After 60s but before the test ends, there should be some test failures because the HTTP requests fail.

### PR DESCRIPTION
**Pull request by imiric**
This introduces a new composite DNS option (`--dns`, `K6_DNS`, and `dns` in JS options) to allow finer-grained control of k6's DNS resolution.

The sub-options are:
- `ttl`: the cache expiration period per hostname. Note that currently k6 doesn't respect the TTL in the DNS record, as that involves a deeper refactoring of the resolver that's currently in progress.
  Possible values are:
    * `inf`: hosts are cached indefinitely for the duration of `k6 run` (previous default).
    * `0`: the cache is disabled and lookups will be done on each new connection.
    * `3000`, `30s`, `1m`, etc.: cache DNS lookups for the specified period. If no unit is provided, milliseconds are assumed.
  
  Default value: `5m`.

- `select`: strategy to use when selecting an IP if more than one is returned in the response.
  Possible values are:
    * `first`: return the first IP from the response (previous default).
    * `random`: return a random IP from the response.
    * `roundRobin`: rotate the IP returned for each new connection. The current implementation is not stable and could repeat or skip IPs, but this should be good enough in most cases.
  
  Default value: `random`.

- `policy`: IP version preference.
  Possible values are:
    * `preferIPv4`: return an IPv4 address if available, otherwise fall back to IPv6.
    * `preferIPv6`: return an IPv6 address if available, otherwise fall back to IPv4.
    * `onlyIPv4`: only use IPv4 addresses even if an IPv6 address is returned.
    * `onlyIPv6`: only use IPv6 addresses even if an IPv4 address is returned.
    * `any`: no preference, return any address (previous default).

  Default value: `preferIPv4`.

### Usage examples

- CLI: `k6 run --dns='ttl=0,select=roundRobin,policy=onlyIPv4' ...`
- Environment variable: `K6_DNS='ttl=10m,select=first,policy=preferIPv6' k6 run ...`
- JS `options`:
  ```javascript
  export let options = {
    dns: {
      ttl: '1m',
      select: 'random',
      policy: 'any'
    }
  }
  ```

### Breaking changes

As discussed:
- The default `ttl` if unspecified is `5m` instead of the previous `inf` behavior.
- The default `select` if unspecified is `random` instead of the previous `first` behavior.

### Important note

These resolver settings will only be applied on new HTTP/TCP connections. Since DNS lookups are only done before the connection is established, if the test script and server enable HTTP keep-alives, the script might continue to use the established connection to the "old" host even though the DNS record had changed or the TTL expired. I.e. k6 will not actively close the connection or keep track of the TTL in the background, which it arguably shouldn't anyway.

To circumvent this the script will either have to let the connection close by itself after the idle timeout (should we make [`http.Transport.IdleConnTimeout`](https://github.com/golang/go/blob/d277a361231485999cc2b7433e3244e559c7d7da/src/net/http/transport.go#L212) configurable?), or enable the `noConnectionReuse` option to disable keep-alives altogether, which is not ideal...

This PR closes #726 and #738 if used correctly, but is more of a workaround than a proper fix.

### CODE REVIEW

File: lib/options.go [hunk 1]
```diff
@@ -44,6 +45,21 @@ const DefaultScenarioName = "default"
 // nolint: gochecknoglobals
 var DefaultSummaryTrendStats = []string{"avg", "min", "med", "max", "p(90)", "p(95)"}
 
+type DNSConfig struct {
+	TTL null.String `json:"ttl"`
+}
+
+func (c *DNSConfig) Decode(value string) error {
```
Comment (na--) [inline lib/options.go:52]: hmm instead of a custom `Decode()` function, why not implement the [`TextUnmarshaler` interface](https://golang.org/pkg/encoding/#TextUnmarshaler)?

Comment (imiric) [reply lib/options.go]: You prefer `TextUnmarshaler` because it's more widely used?

Done in 5ef75377, but I also had to implement `UnmarshalJSON` for some reason.

**Comment by imiric** [comment]
@na-- @MStoykov please take a look at the latest changes.

From manual functional tests both TTL and strategy seem to work OK, but I can't resolve the config consolidation failure. From digging into it it seems that `cliConf` is modified by `fileConf` on line 232 here:

https://github.com/loadimpact/k6/blob/5ef753777c5231f4f08d8955ce7432b95db34205/cmd/config.go#L232-L236

So when it's applied again on line 236 it actually applies the modified values, not the original ones that were passed to `getConsolidatedConfig()`.

If I'm not mistaken, to make this work we need a deep copy of the original `cliConf` which can then override everything else, but I didn't want to open that can of worms here as it can impact potentially everything depending on the current behavior.

Anyway, please test this manually yourselves. The easiest way I've found is changing `/etc/hosts` since there's no way to mock this currently (and also why the tests I mentioned in the description are useless).

File: lib/options.go [hunk 2]
```diff
@@ -44,6 +45,79 @@ const DefaultScenarioName = "default"
...
+	Strategy NullDNSStrategy `json:"strategy"`
+}
+
+//go:generate enumer -type=DNSStrategy -transform=kebab -trimprefix DNS -output dns_strategy_gen.go
+type DNSStrategy uint8
+
+type NullDNSStrategy struct {
+	DNSStrategy
+	Valid bool
+}
```
Comment (imiric) [inline lib/options.go:59]: This is awful, but I needed a nullable type to work with the `Apply()` mechanism... It seems any config item needs to have this logic for the overriding to work. :-/

File: lib/netext/dialer.go [hunk 3]
```diff
@@ -33,34 +35,96 @@ import (
...
+		r.m.Lock()
+		defer func() {
+			r.roundRobin[host]++
+			r.m.Unlock()
+		}()
+		// TODO: The index approach is not stable and we'll need to track
+		// individual IPs... Do we really want to implement an additional cache
+		// for this, since dnscache does not expose its internal one? If so, we
+		// should scrap dnscache entirely and re-implement it here.
+		return ips[int(r.roundRobin[host])%len(ips)]
```
Comment (MStoykov) [inline lib/netext/dialer.go:106]: Given the size of the dnscache ... code ... I am all for just implementing our own

File: lib/netext/dialer.go [hunk 4]
```diff
@@ -265,3 +321,7 @@ func (c *Conn) Write(b []byte) (int, error) {
 	}
 	return n, err
 }
+
+func init() {
+	rand.Seed(time.Now().UTC().UnixNano())
+}
```
Comment (MStoykov) [inline lib/netext/dialer.go:327]: I would prefer if the resolver has a random generator, and given that it needs to be concurrently called (http.batch) that will be a little more code :( 
So maybe in the next PR

File: lib/options.go [hunk 5]
```diff
@@ -44,6 +45,79 @@ const DefaultScenarioName = "default"
...
+	DNSRoundRobin
+	DNSRandom
+)
+
+// nolint: gochecknoglobals
+var DefaultDNSConfig = DNSConfig{
+	TTL:      null.StringFrom("inf"),
+	Strategy: NullDNSStrategy{DNSFirst, true},
+}
+
```
Comment (MStoykov) [inline lib/options.go:72]: I would prefer this to be a getter/generator/construct like ... most other such ones which just returns a new instance.

I do worry a lot with this kind of pointer heavy structures that someone will copy the value but the value will have a pointer inside and then they will just change the value to which the pointer points instead of the pointer. 
I don't think this happens here (or is even possible), but in the future, it might be and those kind of bugs are hard to see usually

File: lib/options.go [hunk 6]
```diff
@@ -44,6 +45,79 @@ const DefaultScenarioName = "default"
...
+	}
+	c.Strategy = DefaultDNSConfig.Strategy
+	if strat, ok := params["strategy"]; ok {
+		if s, err := DNSStrategyString(strat.(string)); err != nil {
+			return err
+		} else {
+			c.Strategy.DNSStrategy = s
+			c.Strategy.Valid = true
+		}
+	}
```
Comment (MStoykov) [inline lib/options.go:101]: can we error out on unknown fields as well?

File: lib/options.go [hunk 7]
```diff
@@ -44,6 +45,79 @@ const DefaultScenarioName = "default"
...
+func (s *NullDNSStrategy) UnmarshalJSON(data []byte) error {
+	var str string
+	if err := json.Unmarshal(data, &str); err != nil {
+		return err
+	}
+	var err error
+	if s.DNSStrategy, err = DNSStrategyString(str); err == nil {
+		s.Valid = true
+	}
+	return err
```
Comment (MStoykov) [inline lib/options.go:118]: it is usually better to return `nil` directly for [when it will go through a variable just in case it returns an error](https://yourbasic.org/golang/gotcha-why-nil-error-not-equal-nil/) that isn't just the interface `error`

Also, I find the code ... strange, which I noticed it

p.s. Isn't the unmarshalling of this just `string(data)` ? or does it include the quotes around it? I guess it includes the quote ... probably better to just use `json.Unsmarshal` then :thinking:

File: lib/options.go [hunk 8]
```diff
@@ -521,6 +598,20 @@ func (o Options) Apply(opts Options) Options {
 		o.ConsoleOutput = opts.ConsoleOutput
 	}
 
+	// FIXME: This should really be in applyDefault(), but in some tests
+	// o.DNS hasn't been initialized yet...
+	if o.DNS == nil {
+		o.DNS = &DefaultDNSConfig
+	}
```
Comment (MStoykov) [inline lib/options.go:605]: so ... here we get the address of the default DNS config and then ... change it(the config, not the address)? This doesn't seem like a good idea and will likely break with tests ... especially parallel ones

File: lib/options.go (hunk 1 above)
Comment (MStoykov) [reply lib/options.go]: well, we definitely need to be able to put it in the `metadata.json` and back out when making the archive and then running it ;)

File: core/local/local_test.go [hunk 9]
```diff
@@ -974,6 +974,98 @@ func TestExecutionSchedulerIsRunning(t *testing.T) {
...
+				for {
+					select {
+					case err := <-errCh:
+						require.NoError(t, err)
+						return
+					case <-time.After(6 * time.Second):
+						t.Fatal("timed out")
+						return
+					}
+				}
```
[the remark this answers is not in the document]
Comment (imiric) [reply core/local/local_test.go:1063]: Yeah, as I mentioned in the description, these tests are half-baked / useless right now without properly mocking the DNS server. The idea of this and the other `TestVUIntegrationDNS` test was to start the execution scheduler with a valid IP of the httpmultibin server, then update the IP to a failing one and assert on what the behavior should be with the different TTL/strategy options. But since I wasn't able to mock it properly, I left them here purely for reference.

But thanks for mentioning mocking of `Resolver.Dial`. If we bring in dnscache internally then this test would be possible, so I'll see what I can do.

File: cmd/options.go [hunk 10]
```diff
@@ -235,6 +236,18 @@ func getOptions(flags *pflag.FlagSet) (lib.Options, error) {
...
+	if dns, err := flags.GetString("dns"); err != nil {
+		return opts, err
+	} else if dns != "" {
+		if err := opts.DNS.UnmarshalText([]byte(dns)); err != nil {
+			return opts, err
+		}
+		// TODO: This obviously can't work for neither option...
+		opts.DNS.TTL.Valid = flags.Changed("dns")
+		opts.DNS.Strategy.Valid = flags.Changed("dns")
+	}
```
Comment (MStoykov) [inline cmd/options.go:249]: I think you could try to implement [pflag.Value](https://godoc.org/github.com/spf13/pflag#Value) for example see [here](https://github.com/spf13/pflag/blob/81378bbcd8a1005f72b1e8d7579e5dd7b2d612ab/bytes.go#L11-L34)

File: lib/options.go (hunk 5 above)
Comment (imiric) [reply lib/options.go]: Resolved by 7578a411 ?

File: lib/testutils/resolver.go [hunk 11]
```diff
@@ -0,0 +1,228 @@
...
+		n, err := s.Read(b)
+		if err != nil {
+			return
+		}
+
+		var msg dnsmessage.Message
+		// FIXME: This returns the error `unpacking Question.Name: segment prefix is reserved`
+		// https://github.com/golang/net/blob/62affa334b73ec65ed44a326519ac12c421905e3/dns/dnsmessage/message.go#L1999
+		if err := msg.Unpack(b[:n]); err != nil {
+			spew.Dump(err)
```
Comment (imiric) [inline lib/testutils/resolver.go:70]: @na-- This is the test issue I'm having. I'm not sure why a wrong "segment prefix" is received here. I think it refers to the subnet prefix `/64` or `/128`, but a) the tests should be doing an IPv4 lookup not IPv6, and b) I don't see where this prefix is set in the request or what's actually wrong with the payload. :-/

File: js/runner.go [hunk 12]
```diff
@@ -318,9 +321,50 @@ func (r *Runner) SetOptions(opts lib.Options) error {
...
+	ttl := types.NewNullDuration(0, false)
+	switch ttlS {
+	case "", "inf":
+		// cache indefinitely
+		ttl.Valid = true
+	case "0":
+		// disable cache
+	default:
+		origTTLs := ttlS
+		// Treat unitless values as seconds
```
Comment (na--) [inline js/runner.go:355]: Given https://github.com/loadimpact/k6/issues/1305, I'd prefer to have be milliseconds, not seconds. Even though it makes less sense for this particular context, the real UX benefit would be to treat duration configurations the same everywhere in k6, we shouldn't introduce any more special cases

File: lib/testutils/resolver.go (hunk 11 above)
Comment (na--) [reply lib/testutils/resolver.go:70]: I'm missing big chunks of the background knowledge, but to be fair, I don't think this test is required for releasing the feature. I can be releases together with the rest of the DNS changes in v0.29.0

File: cmd/config_consolidation_test.go [hunk 13]
```diff
@@ -375,6 +375,70 @@ func getConfigConsolidationTestCases() []configConsolidationTestCase {
...
+			},
+			exp{}, func(t *testing.T, c Config) {
+				assert.Equal(t, &lib.DNSConfig{
+					TTL:      null.StringFrom("30"),
+					Strategy: lib.NullDNSStrategy{DNSStrategy: lib.DNSFirst, Valid: true},
+				}, c.Options.DNS)
+			},
+		},
+		{
+			// FIXME: CLI arg *should* override all
```
Comment (na--) [inline cmd/config_consolidation_test.go:428]: if you have a pointer, for `lib.Options.DNSConfig`, this is going to be nightmarishly difficult to fix with envconfig, so I suggest we just set it to `ignored:"true"` for now, i.e. unable to be configured by environment variables

Comment (na--) [reply cmd/config_consolidation_test.go:428]: Hmm yeah, wouldn't having `NullDNSConfig` also solve of having `NullDNSStrategy`? A "higher" DNS setting will simply overwrite all "lower" DNS options with its own or the default.

File: lib/netext/dialer.go [hunk 14]
```diff
@@ -33,34 +35,96 @@ import (
...
-// about a given address.
-type dnsResolver interface {
-	FetchOne(address string) (net.IP, error)
+// DNSResolver is an interface that fetches DNS information about a given host.
+type DNSResolver interface {
+	Fetch(host string) (net.IP, error)
+}
+
+type resolver struct {
+	cache      *dnscache.Resolver
```
Comment (na--) [inline lib/netext/dialer.go:48]: I don't think we should continue to use this library, at all. It's way of handling TTL is... not good: https://github.com/viki-org/dnscache/blob/c70c1f23c5d84ab39054ec6b418a5ed0fa51cade/dnscache.go#L46-L60

File: js/runner.go (hunk 12 above)
Comment (imiric) [reply js/runner.go:355]: Hhmm I agree with not introducing special cases, but in this case treating them as milliseconds would be counter-intuitive, especially since we don't log what the interpreted value is (maybe we should?). But OK, will change it.

File: core/local/local_test.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (imiric) [reply core/local/local_test.go]: The test is fixed in the latest changes, though I still want to get rid of the global var mocking, and the timings might be flaky, but I don't see a way around that.

File: js/runner_test.go [hunk 15]
```diff
@@ -1349,6 +1349,73 @@ func TestVUIntegrationClientCerts(t *testing.T) {
...
+	}{
+		"inf_cache": { // IPs are cached indefinitely
+			lib.Options{},
+		},
+		"no_cache": { // every request does a DNS lookup
+			lib.Options{DNS: &lib.DNSConfig{TTL: null.StringFrom("0")}},
+		},
+		"2s_cache": {
+			lib.Options{DNS: &lib.DNSConfig{TTL: null.StringFrom("2s")}},
+		},
```
[the remark this answers is not in the document]
Comment (imiric) [reply js/runner_test.go]: I added a test for "1000" in the latest changes, which is now interpreted as 1s.

File: lib/netext/dialer.go (hunk 3 above)
Comment (imiric) [reply lib/netext/dialer.go]: In the latest changes I re-implemented the caching with an approach I discussed with Ned, so `viki-org/dnscache` is officially gone 🎉 . It doesn't use a goroutine to update all hosts when the TTL expires globally, and instead keeps track of the last lookup time per host and refreshes when that is over the TTL. There's no cache eviction, but I'm not sure it's needed since it wasn't done before either. Let me know.

File: lib/options.go (hunk 8 above)
Comment (imiric) [reply lib/options.go]: Not an issue anymore since I switched to using a struct value for `Options.DNSConfig` and not a pointer.

File: cmd/options.go (hunk 10 above)
Comment (imiric) [reply cmd/options.go]: Don't think this is needed anymore, since it seems to work now after switching to a struct value instead of a pointer for `DNSConfig`.

File: lib/testutils/resolver.go (hunk 11 above)
Comment (imiric) [reply lib/testutils/resolver.go]: Not an issue anymore since I abandoned this whole DNS mock server approach, as discussed.

File: js/runner.go (hunk 12 above)
Comment (imiric) [reply js/runner.go]: Resolved in the latest changes.

File: cmd/config_consolidation_test.go (hunk 13 above)
Comment (imiric) [reply cmd/config_consolidation_test.go]: Yup, I abandoned the pointer approach... It was actually more nightmarish to deal with our insane `Apply()` mechanism than envconfig, but it seems to work now with a struct value, after a frustrating amount of trial and error. 🙈

File: lib/netext/dialer.go (hunk 14 above)
Comment (imiric) [reply lib/netext/dialer.go]: `viki-org/dnscache` is gone in the latest changes, let me know how it looks.

**Comment by imiric** [comment]
All major issues with the configuration and tests should now be resolved, and the current test failure is because of the global `netext.LookupIP` override I'm doing. This was the simplest way to mock the stdlib call in tests, as all other attempts I tried involved changing the `netext.Resolver` interface. I don't like this approach as it changes the implementation too much simply for testing purposes, while mocking `Runner.Resolver` is messy, so suggestions are welcome. :) A possible approach could be to pass the `LookupIP` function to `NewResolver()` or another constructor, but that could also be problematic.

File: lib/options.go (hunk 7 above)
Comment (imiric) [reply lib/options.go]: Thanks about the `err` tip. I removed this unmarshal method in the latest changes, and strategy is now unmarshalled in the `DNSConfig` one.

File: lib/options.go [hunk 16]
```diff
@@ -44,6 +45,86 @@ const DefaultScenarioName = "default"
...
+		return nil
+	}
+	params, err := strvals.Parse(string(text))
+	if err != nil {
+		return err
+	}
+	return c.unmarshalDNSConfig(params)
+}
+
+func (c *DNSConfig) unmarshalDNSConfig(params map[string]interface{}) error {
```
Comment (imiric) [inline lib/options.go:113]:
```suggestion
func (c *DNSConfig) unmarshal(params map[string]interface{}) error {
```

File: lib/options.go [hunk 17]
```diff
@@ -44,6 +45,86 @@ const DefaultScenarioName = "default"
...
+	Valid bool
+}
+
+const (
+	DNSFirst DNSStrategy = iota + 1
+	DNSRoundRobin
+	DNSRandom
+)
+
+const DefaultDNSConfigText = "ttl=inf,strategy=first"
```
Comment (imiric) [inline lib/options.go:70]: I was lazy about it, but this should probably be returned by `DNSConfig.MarshalText()`, right?

File: js/runner_test.go [hunk 18]
```diff
@@ -1664,3 +1664,50 @@ func TestSystemTags(t *testing.T) {
 		})
 	}
 }
+
+// Test DNS configuration validation and that the correct resolver is initialized.
+func TestResolverConfig(t *testing.T) {
```
Comment (imiric) [inline js/runner_test.go:1669]: Reminder to remove this test, it's not needed anymore.

File: lib/netext/resolver.go [hunk 19]
```diff
@@ -0,0 +1,135 @@
...
+			resolver: res,
+			ttl:      time.Duration(ttl.Duration),
+			cm:       &sync.Mutex{},
+			cache:    make(map[string]cacheRecord),
+		}
+	} else {
+		r = &res
+	}
+
+	return r
```
Comment (na--) [inline lib/netext/resolver.go:81]:
```suggestion
	res := resolver{
		strategy:   strategy,
		rrm:        &sync.Mutex{},
		roundRobin: make(map[string]uint8),
	}
	if !ttl.Valid || ttl.Duration == 0 {
		return &res
	}
	return &cacheResolver{
		resolver: res,
		ttl:      time.Duration(ttl.Duration),
		cm:       &sync.Mutex{},
		cache:    make(map[string]cacheRecord),
	}
```

**Review by na-- — COMMENTED** [review]
Haven't completely finished looking through the code, will mention anything else as individual comments

File: lib/netext/resolver.go [hunk 20]
```diff
@@ -0,0 +1,135 @@
...
+	r.cm.Lock()
+	defer r.cm.Unlock()
+
+	var ips []net.IP
+	// TODO: Invalidate? When?
+	if d, ok := r.cache[host]; ok && time.Now().UTC().Before(d.lastLookup.Add(r.ttl)) {
+		ips = r.cache[host].ips
+	} else {
+		var err error
+		ips, err = LookupIP(host)
```
Comment (na--) [inline lib/netext/resolver.go:108]: You should unlock the mutex before you do the lookup, since that can take a long time, and only lock it again when you're updating the index.

File: lib/options.go [hunk 21]
```diff
@@ -44,6 +45,86 @@ const DefaultScenarioName = "default"
...
+		return err
+	}
+	return c.unmarshalDNSConfig(params)
+}
+
+func (c *DNSConfig) UnmarshalText(text []byte) error {
+	if string(text) == DefaultDNSConfigText {
+		*c = DefaultDNSConfig()
+		return nil
+	}
```
[the remark this answers is not in the document]
Comment (imiric) [reply lib/options.go:105]: It wasn't meant as an optimization, but a way to avoid more complex logic for setting default values. I'd argue this shouldn't even be in `UnmarshalText()`, but it was one of those quick workarounds for when the exact default string is used, so the order didn't matter. I'll see if I can get rid of it.

File: lib/options.go (hunk 17 above)
Comment (imiric) [reply lib/options.go:70]: Sure, implementing `String()` sounds better, thanks.

File: lib/netext/resolver.go (hunk 19 above)
Comment (imiric) [reply lib/netext/resolver.go:81]: Hhmm yeah, that looks cleaner, and I could just pass `time.Duration` instead of our `types.NullDuration`.

File: lib/netext/resolver.go (hunk 20 above)
Comment (imiric) [reply lib/netext/resolver.go:108]: Good idea, done in 6c4d8fd1.

File: lib/netext/resolver.go (hunk 19 above)
Comment (imiric) [reply lib/netext/resolver.go]: Done in cf9bbb2a, thanks.

File: lib/options.go [hunk 22]
```diff
@@ -44,6 +45,86 @@ const DefaultScenarioName = "default"
...
+	DNSFirst DNSStrategy = iota + 1
+	DNSRoundRobin
+	DNSRandom
+)
+
+const DefaultDNSConfigText = "ttl=inf,strategy=first"
+
+func DefaultDNSConfig() DNSConfig {
+	return DNSConfig{
+		TTL:      null.NewString("inf", false),
```
[the remark this answers is not in the document]
Comment (imiric) [reply lib/options.go]: Resolved by 1c2396d0.

File: lib/options.go (hunk 17 above)
Comment (imiric) [reply lib/options.go]: Resolved by 53c94b92.

File: lib/options.go (hunk 16 above)
Comment (imiric) [reply lib/options.go]: Yeah, but this isn't really making it worse. We'd likely need 90% of it even if we had a sane config system, as this is just marshalling code for the internal representation, which should handle both JSON and the strvals format.

Anyway, shortened the method name in f06ad67d.

File: lib/options.go (hunk 6 above)
Comment (imiric) [reply lib/options.go:156]: I was refactoring `unmarshal()` anyway to see if I can get rid of the `*c = DefaultDNSConfig()` thing, so this was trivial to add. See acdf402b.

File: lib/netext/dialer.go (hunk 4 above)
Comment (imiric) [reply lib/netext/dialer.go]: Why would it be a problem with `http.batch()`? I made it internal to `resolver` in f80540fa, and I haven't seen any panics. Let me know if we need something else.

File: lib/options.go (hunk 1 above)
Comment (imiric) [reply lib/options.go]: This is resolved now.

Comment (na--) [reply lib/options.go]: Because there is no `Decoder` interface in the Go standard library AFAIK. The convention is that if your type can be encoded as text or decoded from text, you can implement the `ecnoding.TextMarshaler` or `ecnoding.TextUnmarshaler` and different things will now know to work with your type. For example, [envconfig](https://github.com/kelseyhightower/envconfig/#supported-struct-field-types) and even JSON: https://golang.org/pkg/encoding/json/#example__textMarshalJSON

File: lib/options.go (hunk 21 above)
[the remark this answers is not in the document]
Comment (imiric) [reply lib/options.go]: Yeah, so I wasn't able to remove this easily, as it causes `TestConfigConsolidation` to fail 😭 Try it for yourself, comment out this block, run the test and see all the issues... (I have an intense hatred for that specific test 😆, having seen it fail so many times. It's huge and makes it difficult to parse the errors and go to the source.)

To fix it I'd need to manually handle the default values for both fields plus their `Valid` values, which is tricky to get right without messing up some fallback logic. So I'd chalk this one up as another `TODO` for #883. Let me know if you want a comment for it or have another suggestion.

File: lib/options.go (hunk 1 above)
Comment (imiric) [reply lib/options.go]: Ah right, for some reason I was thinking [`json.Decoder`](https://golang.org/pkg/encoding/json/#Decoder) was an interface. Yeah, better to use an interface in this case for sure.

**Review by na-- — COMMENTED** [review]
Hmm I don't like the global `var LookupIP = net.LookupIP`, at all. It should be injected as a dependency, I'll try to write some code to see if that would work.

**Comment by imiric** [comment]
@na-- Agreed, we need to get rid of it, but I can't think of a simple approach.

We can't simply replace all of `Resolver` with a mock as that would replace the caching and strategy logic which is precisely what we want to test. :) Something like changing the `NewResolver` initializer to take a `LookupIP` function would also be tricky to mock as `js.Runner` initializes it in a couple of places.

Only thing I can think of is adding something like a `SetLookupIP()` function to the `Resolver` interface and calling that in tests, but it seems messy for just making tests work.

Thanks for the help, I'm trying some things myself.

**Comment by na--** [comment]
I think I have a workable idea, will try to push a PR in a bit

**Comment by na--** [comment]
@imiric, take a look at https://github.com/loadimpact/k6/pull/1627 - not sure this _exactly_ has to be the solution, but it seems reasonably fine as an alternative

File: js/runner.go [hunk 23]
```diff
@@ -318,9 +322,55 @@ func (r *Runner) SetOptions(opts lib.Options) error {
...
+
 	return nil
 }
 
+func parseTTL(ttlS string) (time.Duration, error) {
+	ttl := time.Duration(0)
+	switch ttlS {
+	case "inf":
+		// cache "indefinitely"
+		ttl = time.Duration(math.MaxInt64)
```
Comment (na--) [inline js/runner.go:353]: Hmm, this might be a problem :sweat_smile: In the check for cache freshness, you have `d.lastLookup.Add(r.ttl)`. But if `ttl` is already `math.MaxInt64`, then this will wrap around and become a negative number, so `time.Now().UTC()` will never be less than it, so we'll never use the cache. 

I think we should just use 1 year or something like that here, not `math.MaxInt64`

Comment (imiric) [reply js/runner.go:353]: Indeed, great catch, will change.

File: lib/netext/resolver.go [hunk 24]
```diff
@@ -0,0 +1,140 @@
...
+	ttl   time.Duration
+	cm    *sync.Mutex
+	cache map[string]cacheRecord
+}
+
+// NewResolver returns a new DNS resolver. If ttl is not 0, responses
+// will be cached per host for the specified period. The IP returned from
+// LookupIP() will be selected based on the given strategy.
+func NewResolver(actRes MultiResolver, ttl time.Duration, strategy lib.DNSStrategy) Resolver {
+	r := rand.New(rand.NewSource(time.Now().UnixNano())) // nolint: gosec
```
Comment (na--) [inline lib/netext/resolver.go:64]: This wouldn't be safe to use from multiple goroutines concurrently, see https://golang.org/pkg/math/rand/#NewSource
> Unlike the default Source used by top-level functions, this source is not safe for concurrent use by multiple goroutines.

Comment (imiric) [reply lib/netext/resolver.go:64]: So I guess it wasn't panicking because the resolver is used globally?

Anyway, I reused the same mutex for `r.roundRobin` in 3149b4d9. Let me know if this is sufficient.

File: js/runner.go (hunk 23 above)
Comment (imiric) [reply js/runner.go]: Resolved by a825a9c4.

File: lib/netext/resolver.go [hunk 25]
```diff
@@ -0,0 +1,140 @@
...
+		ips = r.cache[host].ips
+	} else {
+		r.cm.Unlock() // The lookup could take some time, so unlock momentarily.
+		var err error
+		ips, err = r.resolve(host)
+		if err != nil {
+			return nil, err
+		}
+		r.cm.Lock()
+		r.cache[host] = cacheRecord{ips: ips, lastLookup: time.Now().UTC()}
```
Comment (na--) [inline lib/netext/resolver.go:112]: I don't think you need `.UTC()` here
```suggestion
		r.cache[host] = cacheRecord{ips: ips, lastLookup: time.Now()}
```

File: lib/netext/resolver.go [hunk 26]
```diff
@@ -0,0 +1,140 @@
...
+// LookupIP returns a single IP resolved for host, selected by the configured
+// strategy. Results are cached per host and will be refreshed if the last
+// lookup time exceeds the configured TTL (not the TTL returned in the DNS
+// record).
+func (r *cacheResolver) LookupIP(host string) (net.IP, error) {
+	r.cm.Lock()
+
+	var ips []net.IP
+	// TODO: Invalidate? When?
+	if d, ok := r.cache[host]; ok && time.Now().UTC().Before(d.lastLookup.Add(r.ttl)) {
```
Comment (na--) [inline lib/netext/resolver.go:102]:
```suggestion
	if d, ok := r.cache[host]; ok && time.Now().Before(d.lastLookup.Add(r.ttl)) {
```
and here

**Review by na-- — COMMENTED** [review]
I don't see any other major issues in the code, but a more thorough look and testing is definitely required.

I noticed a potential minor issue with the configuration: `k6 archive 'github.com/loadimpact/k6/samples/http_get.js'  && (tar xfO archive.tar metadata.json | jq '.options.dns')` will result in
```json
{
  "ttl": "5m",
  "strategy": "random"
}
```
Which means that the default values are encoded in the `metadata.json` `options` map not as `null` values, like other unchanged filed (i.e. ones with `Valid == false`) are, but with their actual values. This is a bit problematic, since it will mean re-runs of old cloud tests will execute with the current default DNS options, even if we change them to new defaults in the future, e.g. when we have a proper DNS resolver.

File: lib/netext/resolver.go (hunk 25 above)
Comment (imiric) [reply lib/netext/resolver.go]: Sure, resolved by 96def6c0.

File: lib/netext/resolver.go (hunk 26 above)
Comment (imiric) [reply lib/netext/resolver.go]: Resolved by 96def6c0.

**Comment by imiric** [comment]
@na-- Yeah, that behavior is a side-effect of setting the default value with envconfig. :-/ I wouldn't say it's envconfig's fault though, as this works as expected with `k6 run`. I'll see if I can set `ignored:"true"` and handle it manually.

**Comment by MStoykov** [comment]
@imiric I would argue it will be better if their a `null` and we don't support env variable for a version or two than having the env variable support but having them in the metadata.json

File: lib/netext/resolver.go [hunk 27]
```diff
@@ -0,0 +1,140 @@
...
+	switch r.strategy {
+	case lib.DNSFirst:
+		return ip
+	case lib.DNSRoundRobin:
+		r.rrm.Lock()
+		// NOTE: This index approach is not stable and might result in returning
+		// repeated or skipped IPs if the records change during a test run.
+		ip = ips[int(r.roundRobin[host])%len(ips)]
+		r.roundRobin[host]++
+		r.rrm.Unlock()
```
Comment (MStoykov) [inline lib/netext/resolver.go:133]: I would argue this map should have a struct with the ... counter and a lock so you only lock one hosts roundRobin ... but given that I think you will need a lock on the outside map ... there might not be a performance improvement at all.

We should probably benchmark it still for the next iteration

**Review by MStoykov — COMMENTED** [review]
LGTM. I would still prefer it if we make it so that it doesn't save the current default values in the archive before merging it. Again, even if we can't make it be configurable from the env variable for now, that IMO isn't that big of a problem, we can fix it in the next release or a PR after that before the release if it's encapsulated enough

File: lib/options.go [hunk 28]
```diff
@@ -44,6 +46,117 @@ const DefaultScenarioName = "default"
...
+	return c.unmarshal(params)
+}
+
+func (c *DNSConfig) unmarshal(params map[string]interface{}) error {
+	for k, v := range params {
+		switch k {
+		case "strategy":
+			if v == "" {
+				continue
+			}
```
[the remark this answers is not in the document]
Comment (imiric) [reply lib/options.go:141]: Mainly because of [this test](https://github.com/loadimpact/k6/blob/96def6c0b7dcd90ccb90346b8c5621fd91b0d0eb/lib/options_test.go#L342-L348).

File: lib/options.go [hunk 29]
```diff
@@ -44,6 +46,117 @@ const DefaultScenarioName = "default"
...
+			if s, err := DNSStrategyString(v.(string)); err != nil {
+				return err
+			} else { // nolint: golint
+				c.Strategy.DNSStrategy = s
+				c.Strategy.Valid = true
+			}
```
[the remark this answers is not in the document]
Comment (imiric) [reply lib/options.go:147]: Since `s` is used in the `else` block, declaring it outside "pollutes" the outer scope, IMO. This is a moot point in this case, but in general I think this is an edge case that `golint` doesn't detect properly. See https://github.com/golang/lint/issues/202 .

But sure, I can switch to that style if you think it's more readable, even though I dislike that it has functional implications in the code and shouldn't be linted...

File: lib/options.go [hunk 30]
```diff
@@ -44,6 +46,117 @@ const DefaultScenarioName = "default"
...
+		case "ttl":
+			ttlv := fmt.Sprintf("%v", v)
+			if ttlv != "" {
```
[the remark this answers is not in the document]
Comment (imiric) [reply lib/options.go:150]: > maybe you can just check that v is a string ... I am pretty sure it should be

It's not guaranteed actually, since something like `3000` would be interpreted as int, so type casting would be messier.

And see my other comment about not erroring out on empty values.

File: lib/netext/resolver.go [hunk 31]
```diff
@@ -0,0 +1,140 @@
...
+}
+
+func (r *resolver) selectOne(host string, ips []net.IP) net.IP {
+	if len(ips) == 0 {
+		return nil
+	}
+	ip := ips[0]
+	switch r.strategy {
+	case lib.DNSFirst:
+		return ip
```
[the remark this answers is not in the document]
Comment (imiric) [reply lib/netext/resolver.go:126]: Yeah, this is wrong... The idea was to use at least some sane default since if `r.strategy` is empty (i.e. it doesn't match any `case`), then we at least return an IP instead of `nil`. This was mostly done to pass some test scenarios where the option isn't properly set.

Since the default was changed to `random`, this should probably fallback to that instead. I'll see if I can get rid of it though, since `r.strategy` should be valid here...

File: lib/netext/resolver.go [hunk 32]
```diff
@@ -0,0 +1,140 @@
...
+	} else {
+		r.cm.Unlock() // The lookup could take some time, so unlock momentarily.
+		var err error
+		ips, err = r.resolve(host)
+		if err != nil {
+			return nil, err
+		}
+		r.cm.Lock()
+		r.cache[host] = cacheRecord{ips: ips, lastLookup: time.Now()}
+	}
```
[the remark this answers is not in the document]
Comment (imiric) [reply lib/netext/resolver.go:113]: > This will mean that we will make only 1 lookup request for each host on each ttl expire instead of ... 5k if there 5k VUs making the same request and the dns server isn't really fast

Hhmm but there wouldn't be 5k lookups of the same host with 5k VUs, since the first lookup that returns will write to the cache, and the rest will read it from there, that's the whole point of it :D You can confirm this with Wireshark: there's only one lookup regardless of the number of VUs, since the resolver is used globally.

Unless I'm misunderstanding your proposal, leaving the `CacheRecord` locked while a lookup is in progress would pause all requests that could've just used the cache in the meantime. But agree that we need more tests and benchmarks for this, which I'm inclined to leave for when the custom resolver is added.

[the remark this answers is not in the document]
Comment (MStoykov) [reply lib/netext/resolver.go:113]: Maybe your resolve is really fast ... (and maybe most resolves will be really fast and my proposal wouldn't do much). 
But in the current scenario because you unlock during the resolve other VUs could come see that there is nothing in the cache/it has expired and start doing the resolve as well.
My proposal basically moves this so, we unlock the cache manager so other VUs can come and either get another record from it or get blocked on the record's lock that is being currently resolved.
P.s. I have a mistake in the algorithm above that will lead to a dead lock, will fix it in a second

File: lib/netext/resolver.go (hunk 27 above)
Comment (imiric) [reply lib/netext/resolver.go:133]: Yeah, that would be interesting to benchmark, but in general I'd like to avoid more mutexes :D 

I can add some benchmarks if you think they're required for this PR, otherwise I'd rather leave them for the proper resolver PR to avoid delaying the release further.

File: lib/options.go [hunk 33]
```diff
@@ -44,6 +46,117 @@ const DefaultScenarioName = "default"
...
+	return c.unmarshal(params)
+}
+
+// UnmarshalText implements encoding.TextUnmarshaler.
+func (c *DNSConfig) UnmarshalText(text []byte) error {
+	if string(text) == DefaultDNSConfig().String() {
+		*c = DefaultDNSConfig()
+		return nil
+	}
+	params, err := strvals.Parse(string(text))
```
[the remark this answers is not in the document]
Comment (imiric) [reply lib/options.go:128]: Maybe... But I don't want to introduce any potential parsing issues if `strvals` already handles it. Plus `strvals` is already used in the Kafka and InfluxDB configs, so it's not like we're adding a new dependency with this.

So I'd rather do this once we remove `strvals` with that bespoke version you guys were considering.

File: lib/netext/resolver.go (hunk 32 above)
[the remark this answers is not in the document]
Comment (imiric) [reply lib/netext/resolver.go:113]: Hhmm right, I see. Would you say this is a blocker then?

File: lib/options.go (hunk 33 above)
[the remark this answers is not in the document]
Comment (MStoykov) [reply lib/options.go:128]: > any potential parsing issues if strvals already handles it. 

you are hitting the potential parsing issues ... because you have an `interface{}` instead of a string ... but w/e
> Plus strvals is already used in the Kafka and InfluxDB configs, so it's not like we're adding a new dependency with this.

yes ... and using it in one more place makes it that much harder to remove it ;) 

again this is nitpicking, I am not saying this is a required thing ... just pointing out that the usage of `strvals` in this concrete example makes other code necessary that wouldn't have been and arguably adds zero value IMO

File: lib/options.go (hunk 28 above)
[the remark this answers is not in the document]
Comment (MStoykov) [reply lib/options.go:141]: I would consider ... that `--dns strategy=,ttl=12` should be an error ;) And the problem you've "fixed" here should be fixed in the UnmarshalJSON instead

File: lib/netext/resolver.go (hunk 27 above)
Comment (MStoykov) [reply lib/netext/resolver.go:133]: No ... the only blocker for me is the fact we write the default values in the metadata.json ... you can ignore everything else until that is fixed :D

Comment (MStoykov) [reply lib/netext/resolver.go:133]: Mostly everything else is what I have seen can be improved but arguably half of those will need benchmarking and should be left for another PR if at all

File: lib/options.go (hunk 28 above)
[the remark this answers is not in the document]
Comment (imiric) [reply lib/options.go:141]: I would consider that too :) But I can't fix this without breaking or changing the assumptions made in some config tests, and I don't want to introduce other potential issues by doing that.

> the problem you've "fixed" here should be fixed in the UnmarshalJSON instead

Why? `unmarshal()` handles both JSON and text unmarshalling, so it makes sense to keep this consistent. If anything `unmarshal()` shouldn't do any validation and the error should be returned by an eventual `Validate()` method, but I'm not sure how to easily hook that up in the current config state.

So I'd rather leave this as is and fix it once we get to #883.

File: lib/netext/resolver.go (hunk 31 above)
[the remark this answers is not in the document]
Comment (imiric) [reply lib/netext/resolver.go]: Resolved by dbf6cad1. An empty `r.strategy` isn't the case anymore...

File: lib/options.go (hunk 29 above)
[the remark this answers is not in the document]
Comment (imiric) [reply lib/options.go]: Resolved by 8662aa9c.

File: lib/options.go (hunk 28 above)
[the remark this answers is not in the document]
Comment (imiric) [reply lib/options.go]: Resolved by 6a3a315c, thanks!

File: lib/options.go (hunk 30 above)
[the remark this answers is not in the document]
Comment (imiric) [reply lib/options.go]: Resolved by 6a3a315c, thanks!

File: js/runner.go [hunk 34]
```diff
@@ -318,9 +321,55 @@ func (r *Runner) SetOptions(opts lib.Options) error {
...
+	r.Resolver = netext.NewResolver(r.ActualResolver, ttl, strategy)
+
 	return nil
 }
 
+func parseTTL(ttlS string) (time.Duration, error) {
+	ttl := time.Duration(0)
+	switch ttlS {
+	case "inf":
+		// cache "indefinitely"
```
[the remark this answers is not in the document]
Comment (imiric) [reply js/runner.go:351]: 😄 I purposely used "indefinitely" since it implies a duration/time, whereas "infinitely" can be used in other contexts. Even though "inf" is a common constant used for this purpose, and makes sense here. And the quotes are because it's not really infinite/indefinite, just a long duration.

Anyway, sure, if you think it's confusing I'll change it to `"infinitely"`, although at that point the comment is kind of redundant. :)

File: cmd/options.go [hunk 35]
```diff
@@ -91,6 +91,11 @@ func optionFlagSet() *pflag.FlagSet {
 	flags.StringSlice("tag", nil, "add a `tag` to be applied to all samples, as `[name]=[value]`")
 	flags.String("console-output", "", "redirects the console logging to the provided output file")
 	flags.Bool("discard-response-bodies", false, "Read but don't process or save HTTP response bodies")
+	flags.String("dns", lib.DefaultDNSConfig().String(), "DNS configuration. Possible ttl values are: 'inf' "+
+		"for a persistent cache, '0' to disable the cache,\nor a positive duration, e.g. '1s', '1m', etc. "+
+		"Milliseconds are assumed if no unit is provided.\n"+
+		"Possible select values to return a single IP are: 'first', 'random' or 'round-robin'.\n"+
+		"Possible policy values are: 'preferIPv4', 'preferIPv6', 'onlyIPv4', 'onlyIPv6' or 'any'.\n")
```
Comment (imiric) [inline cmd/options.go:98]: The mixed kebab-case and camelCase for these options is bothering me 😄

Should we rename `policy` to `ip` (short for "IP version preference") and the values to `4`, `6`, `4only`, `6only` and `any`?

File: lib/options.go [hunk 36]
```diff
@@ -44,6 +47,238 @@ const DefaultScenarioName = "default"
...
+}
+
+// MarshalJSON returns the JSON representation of d
+func (d DNSPolicy) MarshalJSON() ([]byte, error) {
+	return json.Marshal(d.String())
+}
+
+// NullDNSPolicy is a nullable wrapper around DNSPolicy, required for the
+// current configuration system.
+type NullDNSPolicy struct {
```
Comment (imiric) [inline lib/options.go:107]: Should we move some of these DNS config types to `lib/types`, like Mihail did in 46d7dd0c?

File: lib/options.go [hunk 37]
```diff
@@ -44,6 +47,238 @@ const DefaultScenarioName = "default"
...
+	DNSPolicy
+	Valid bool
+}
+
+// UnmarshalJSON converts JSON data to a valid NullDNSStratey
+func (d *NullDNSPolicy) UnmarshalJSON(data []byte) error {
```
Comment (imiric) [inline lib/options.go:113]: These marshalling methods were copied from the `DNSSelect` implementations, just with changed types. Should we DRY it up?

File: js/runner.go [hunk 38]
```diff
@@ -318,9 +323,59 @@ func (r *Runner) SetOptions(opts lib.Options) error {
...
+	dnsSel := opts.DNS.Select.DNSSelect
+	if !dnsSel.IsADNSSelect() {
+		dnsSel = lib.DefaultDNSConfig().Select.DNSSelect
+	}
+	dnsPol := opts.DNS.Policy.DNSPolicy
+	if !dnsPol.IsADNSPolicy() {
+		dnsPol = lib.DefaultDNSConfig().Policy.DNSPolicy
+	}
+	r.Resolver = netext.NewResolver(r.ActualResolver, ttl, dnsSel, dnsPol)
+
```
Comment (MStoykov) [inline js/runner.go:349]: nit: 
I would really prefer if this whole logic was in a separate function somewhere ... 
it looks strange as it is ... I do thin `IsADNSPolicy` should be `.Valid` as in null types ?

File: js/runner.go [hunk 39]
```diff
@@ -318,9 +323,59 @@ func (r *Runner) SetOptions(opts lib.Options) error {
...
+		// Treat unitless values as milliseconds
+		if t, err := strconv.ParseFloat(ttlS, 32); err == nil {
+			ttlS = fmt.Sprintf("%.2fms", t)
+		}
+		var err error
+		ttl, err = types.ParseExtendedDuration(ttlS)
+		if ttl < 0 || err != nil {
+			return ttl, fmt.Errorf("invalid DNS TTL: %s", origTTLs)
+		}
+	}
```
Comment (MStoykov) [inline js/runner.go:375]: Can we get this as a separate function in `lib.types` ? so we can use it wherever we need number to duration functionality (where the duration is ms if no unit is given)

File: lib/options.go (hunk 36 above)
Comment (MStoykov) [reply lib/options.go:107]: Ideally ... but I would argue this can be done in a second PR or at least as the last step, but if you have time - go for it

File: lib/options.go (hunk 37 above)
Comment (MStoykov) [reply lib/options.go:113]: Given that drying this up ... currently means much harder to read code I would .. go with "no". 
But maybe try it in another PR and we can see how it goes ?

File: lib/options.go [hunk 40]
```diff
@@ -44,6 +47,238 @@ const DefaultScenarioName = "default"
...
+	}
+}
+
+// String implements fmt.Stringer.
+func (c DNSConfig) String() string {
+	out := make([]string, 0, 2)
+	out = append(out, fmt.Sprintf("ttl=%s", c.TTL.String))
+	out = append(out, fmt.Sprintf("select=%s", c.Select.String()))
+	out = append(out, fmt.Sprintf("policy=%s", c.Policy.String()))
+	return strings.Join(out, ",")
```
Comment (MStoykov) [inline lib/options.go:210]: nit: Why ... just not a single fmt.Sprintf ?
Also .. the 2 should be 3 ;)

File: lib/options.go [hunk 41]
```diff
@@ -44,6 +47,238 @@ const DefaultScenarioName = "default"
...
+	return json.Marshal(struct {
+		TTL    null.String   `json:"ttl"`
+		Select NullDNSSelect `json:"select"`
+		Policy NullDNSPolicy `json:"policy"`
+	}{
+		TTL:    c.TTL,
+		Select: c.Select,
+		Policy: c.Policy,
+	})
+}
```
Comment (MStoykov) [inline lib/options.go:224]: Why ... just not setting `json:"-"` on Valid ? 
Also ... hm ... I do think you should be using NullDNSConfig so that you don't actually save the default settings in `metadata.json` ?

File: lib/netext/resolver.go [hunk 42]
```diff
@@ -0,0 +1,195 @@
...
+		var err error
+		ips, err = r.resolve(host)
+		if err != nil {
+			return nil, err
+		}
+		ip4, ip6 = groupByVersion(ips)
+		r.cm.Lock()
+		r.cache[host] = cacheRecord{ip4: ip4, ip6: ip6, lastLookup: time.Now()}
+	}
+
```
Comment (MStoykov) [inline lib/netext/resolver.go:128]: As we discussed with @na-- previously the "policy" can be implemented here:
if you have `prefer<version>` if there are IPs from that version *only* they should be saved ... if not only the other ones,
In the case of `only<version>` you only look at .. well that one version
in case of `any` ... you just don't separate them.

This current code might come in handy once we have multiple IPs support as it looks (currently) that each VU will just have 1 IP that will have for it's whole time so you could get 1 VU with ipv4 and another with IPv6 and in the case of `preferIPv4` the second one ... still needs to get IPv6 (otherwise it will just not work ;) ) ... but I would argue that then ... the policy should be changed to an `only<version>` given that the VU in question can't actually make other requests

File: lib/options.go (hunk 37 above)
Comment (imiric) [reply lib/options.go:113]: Nah, don't think it's a big deal either, but I'll see if I have some time for it.

And I just noticed the comment typo 🤦

File: cmd/config_consolidation_test.go [hunk 43]
```diff
@@ -375,6 +382,86 @@ func getConfigConsolidationTestCases() []configConsolidationTestCase {
...
+				env: []string{"K6_DNS=ttl=30,select=random,policy=any"},
+				cli: []string{"--dns", "ttl=5"},
+			},
+			exp{},
+			func(t *testing.T, c Config) {
+				assert.Equal(t, lib.DNSConfig{
+					TTL:    null.StringFrom("5"),
+					Select: lib.NullDNSSelect{DNSSelect: lib.DNSRandom, Valid: true},
+					Policy: lib.NullDNSPolicy{DNSPolicy: lib.DNSany, Valid: true},
+				}, c.Options.DNS)
```
[the remark this answers is not in the document]
Comment (imiric) [reply cmd/config_consolidation_test.go:461]: Yeah, I can see how it could be confusing. But still think the flexibility outweighs any chance of confusion. It would be useful to e.g. have a base configuration in the script, but then be able to override a single sub-option via the env or CLI, instead of having to redefine everything.

Besides, the only reason `dns` is composite is to avoid adding a bunch of top-level options to our messy config system, but otherwise having them separated with a prefix (e.g. `--dns-ttl`, `--dns-policy`, etc.) would be more preferable IMO. These would also map cleanly to env vars as `K6_DNS_TTL`, etc., if we had a sane config system.

File: js/runner.go (hunk 38 above)
Comment (imiric) [reply js/runner.go:349]: Sure, I'll give it a try.

File: lib/options.go (hunk 40 above)
Comment (imiric) [reply lib/options.go:210]: 🤦  I find this pattern more readable, but sure, I'll change it, especially to avoid the array. :)

File: lib/options.go (hunk 41 above)
Comment (imiric) [reply lib/options.go:224]: It hadn't occurred to me 😄 I'll give it a try, thanks.

File: lib/netext/resolver.go (hunk 42 above)
Comment (imiric) [reply lib/netext/resolver.go:128]: I didn't get the scenario in your second paragraph, but agree that it can be simplified. Will change.

File: cmd/options.go (hunk 35 above)
Comment (imiric) [reply cmd/options.go:98]: True, but the mixed casing is still annoying...

File: lib/netext/resolver.go (hunk 42 above)
Comment (MStoykov) [reply lib/netext/resolver.go:128]: after https://github.com/loadimpact/k6/pull/1658 (or anything like it) each VU will have an IP that it will use (unless we completely redesign it ... but having multiple IPs have ... problems). So it is possible that you will have VUs that have an ipv4 and VUs which have ipv6 addresses in the same run. But obviously if you have a VU which will use ipv4 .. it should *not* get an ipv6 address even if `preferIPv6` is configured ... 

But this case IMO will be better fixed in v0.30.0

File: js/runner.go (hunk 38 above)
Comment (imiric) [reply js/runner.go]: Resolved by 3f3f454b.

File: js/runner.go (hunk 39 above)
Comment (imiric) [reply js/runner.go]: Instead of adding a new function, I added the ms logic to `types.ParseExtendedDuration` in 2dc9f1af, which seems to work fine.

File: lib/options.go (hunk 40 above)
Comment (imiric) [reply lib/options.go]: Fixed by 401961f3.

File: lib/options.go (hunk 41 above)
Comment (imiric) [reply lib/options.go]: Resolved by 54290d8c.

Though not sure what you mean with `NullDNSConfig`, as the current `DNSConfig` is essentially that except for the name :) So the default settings aren't saved in `metadata.json` if they're not specified:

```
> go run main.go archive 'github.com/loadimpact/k6/samples/http_get.js' && (tar xfO archive.tar metadata.json | jq '.options.dns')
{
  "ttl": null,
  "select": null,
  "policy": null
}
```

File: lib/netext/resolver.go (hunk 42 above)
Comment (imiric) [reply lib/netext/resolver.go]: Let me know if e0480405 resolves this.

The changes in #1658 will indeed need to be reconciled with the DNS `policy` option. There's also the case if `onlyIPv6` is specified, then it doesn't make sense for the VU to use an outgoing IPv4 interface. But yeah, let's leave that for a follow-up PR.

File: lib/options.go (hunk 36 above)
Comment (imiric) [reply lib/options.go]: Resolved by caf82ab9.

**Review by na-- — DISMISSED** [review]
LGTM! :tada: I am not sure if `local.TestDNSResolver` wouldn't prove to be flaky in the future, but :crossed_fingers:, we'll address it then

File: lib/netext/resolver.go [hunk 44]
```diff
@@ -162,21 +149,26 @@ func (r *resolver) selectOne(host string, ips []net.IP) net.IP {
...
 }
 
-func (r *resolver) applyPolicy(host string, ip4, ip6 []net.IP) (ip net.IP, ips []net.IP) {
-	switch r.policy {
+func (r *resolver) applyPolicy(ips []net.IP) (retIPs []net.IP) {
+	if r.policy == lib.DNSany {
+		return ips
+	}
+	ip4, ip6 := groupByVersion(ips)
+	switch r.policy { //nolint: exhaustive
```
Comment (MStoykov) [inline lib/netext/resolver.go:157]: nit: Can you just have the exhaustive option and ... welll panic if we get to it? This way if we add another one it won't suddenly not be detected

File: lib/netext/resolver.go [hunk 45]
```diff
@@ -162,21 +149,26 @@ func (r *resolver) selectOne(host string, ips []net.IP) net.IP {
...
 	case lib.DNSpreferIPv4:
-		ip = r.selectOne(host, ip4)
-		ips = ip6
+		retIPs = ip6
+		if len(ip4) > 0 {
+			retIPs = ip4
+		}
```
Comment (MStoykov) [inline lib/netext/resolver.go:162]: nit: I find it strange that preferIPv4 first doesn't  set retIPs to ipv4 and then if retIPs is empty to ... actually set it to ipv6

File: lib/types/types.go [hunk 46]
```diff
@@ -95,8 +95,12 @@ func (d Duration) String() string {
 }
 
 // ParseExtendedDuration is a helper function that allows for string duration
-// values containing days.
+// values containing days. If no units are provided, milliseconds are assumed.
```
Comment (MStoykov) [inline lib/types/types.go:98]: This also applies to other configurations such as:
- setup/teardownTimeout
- gracefulStop/rampdown
- timeunit
- duration
- starttime
... more 
I am not saying this is bad idea, I am just pointing out this is breaking change even if it's likely a welcome one
Also ... as far as I can see ... this is not used consistantly so some options will be unmarshalled from JSON to this but not from the cli flags for example `min-iteration-duration` will use time.ParseDuration as this is [what pflag says](https://github.com/spf13/pflag/blob/master/duration.go#L15-L18) or maybe .. not, not certain on whether there is somethign that will check for `UnmarshalText` before that. 

But I would argue this should've been another function in this PR and have this merging be another PR in which this is more tested and looked into
cc @na--

**Review by MStoykov — DISMISSED** [review]
LGTM, apart from my worries that the change to ParseExtentedDuration will break scripts.

I haven't tested it, but will try to get to it today.

File: lib/types/types.go (hunk 46 above)
Comment (na--) [reply lib/types/types.go:98]: hmm I think it's not going to be a big issue and we have to address https://github.com/loadimpact/k6/issues/1305 eventually... @MStoykov keep in mind that this won't actually be used for integer JS/JSON values because of https://github.com/loadimpact/k6/blob/caf82ab98ec3b5dc581519a5269c276ca05a2306/lib/types/types.go#L154-L160
So I'm not sure how much effect this will actually have

Comment (na--) [reply lib/types/types.go:98]: but yeah, maybe we shouldn't make half-measures... so I'm fine if we use a separate function this time, with a `TODO` to switch completely to it and address #1305 in another PR

Comment (MStoykov) [reply lib/types/types.go:98]: Looking in the code that you just linked ... I am even more of the opinion that this should be a separate functio now ... as this seems to make things ... worse :D

Comment (na--) [reply lib/types/types.go:98]: fair enough - I can't think of an example how to break it, but it'd definitely be cleaner, so :+1: from me

File: cmd/options.go (hunk 35 above)
Comment (imiric) [reply cmd/options.go:100]: OK, I made the `select` options camel case as well, so it's `roundRobin` now, but I don't see that enumer feature you mentioned @na--. `-ignorecase` seems to have been added in [a couple of PRs](https://github.com/alvaroloes/enumer/search?q=ignorecase&type=issues), but they weren't merged. Unless you're talking about a different fork, of which there are several.

We might be able to hack around it, but I'd rather leave it as is, even though I prefer lower/kebab case values.

File: lib/types/types.go (hunk 46 above)
Comment (imiric) [reply lib/types/types.go]: Hey, thanks for the heads up, I agree that it's safer to use a different function. I changed it in the recent push, along with some squashing since I had to fix the merge conflicts anyway.

File: lib/netext/resolver.go (hunk 45 above)
Comment (imiric) [reply lib/netext/resolver.go]: Sure, fixed in the latest push.

File: lib/netext/resolver.go (hunk 44 above)
Comment (imiric) [reply lib/netext/resolver.go]: Fixed in the latest push, though I'm not panicking but just doing the fallback assignment.

File: cmd/options.go (hunk 35 above)
Comment (na--) [reply cmd/options.go:100]: https://github.com/dmarkham/enumer/pull/22 and https://github.com/dmarkham/enumer/pull/38 seem to have been the PRs and they are merged

Comment (na--) [reply cmd/options.go:100]: but in any case, this can happen in a separate PR, since we use enumer in other places as well

**Review by na-- — APPROVED** [review]
LGTM :tada:

**Review by MStoykov — APPROVED** [review]
