### PR TITLE
fix(js): fail check if an error is thrown

### LINKED ISSUE #1054: Checks should fail if an exception is thrown inside of them
```javascript
import {check} from "k6";

export default function() {
    check("true", {"throw exception": (s) => {throw "bad"}});
}
```
produces 
```

          /\      |‾‾|  /‾‾/  /‾/
     /\  /  \     |  |_/  /  / /
    /  \/    \    |      |  /  ‾‾\
   /          \   |  |‾\  \ | (_) |
  / __________ \  |__|  \__\ \___/ .io

  execution: local
     output: -
     script: bad.js

    duration: -,  iterations: 1
         vus: 1, max: 1

ERRO[0000] bad
        at throwException (/home/mstoykov/.gvm/pkgsets/go1.12.1/global/src/github.com/loadimpact/k6/bad.js:4:82(4))
        at native
        at /home/mstoykov/.gvm/pkgsets/go1.12.1/global/src/github.com/loadimpact/k6/bad.js:4:27(7)
    done [==========================================================] 1 / 1

    ✓ throw exception

    data_received........: 0 B 0 B/s
    data_sent............: 0 B 0 B/s
    iteration_duration...: avg=126.62µs min=126.62µs med=126.62µs max=126.62µs p(90)=126.62µs p(95)=126.62µs
    iterations...........: 1   0/s
    vus..................: 1   min=1 max=1
    vus_max..............: 1   min=1 max=1

```
:man_facepalming:

### PR DESCRIPTION
**Pull request by imiric**
This fix ensures the check metric is failed if an error occurs inside the check function, while still allowing an unhandled error to be thrown and interrupt the test, keeping backwards compatibility.

Closes #1054

### CODE REVIEW

File: js/modules/k6/k6.go [hunk 1]
```diff
@@ -161,9 +162,11 @@ func (*K6) Check(ctx context.Context, arg0, checks goja.Value, extras ...goja.Va
 		if ok {
 			tmpVal, err := fn(goja.Undefined(), arg0)
 			if err != nil {
-				return false, err
```
Comment (cuonglm) [inline js/modules/k6/k6.go]: I would rather rewrite to:

```
tmpVal, err := fn(goja.Undefined(), arg0)
val = tmpVal
if err != nil {
                val = rt.ToValue(false)
                exc = err
}
```

Comment (imiric) [reply js/modules/k6/k6.go]: Thanks, it avoids a branch, not sure how I missed it. Changed.

File: js/modules/k6/k6.go [hunk 2]
```diff
@@ -182,6 +184,13 @@ func (*K6) Check(ctx context.Context, arg0, checks goja.Value, extras ...goja.Va
 				succ = false
 			}
 		}
+
+		// Fail if a single iteration caused an error
```
Comment (na--) [inline js/modules/k6/k6.go]: `iteration` is not the correct term here, it might be confused with a script iteration - `check callback` is probably a better term.

File: js/modules/k6/k6.go [hunk 3]
```diff
@@ -182,6 +184,13 @@ func (*K6) Check(ctx context.Context, arg0, checks goja.Value, extras ...goja.Va
...
+		// This is kept for backwards compatibility, but should be removed
```
Comment (na--) [inline js/modules/k6/k6.go]: I don't think this comment is needed here, that new `check()` API would be something completely separate, likely with a completely different name and/or import path, so this comment would probably end up stale and forgotten in time :smile:

File: js/modules/k6/k6.go [hunk 4]
```diff
@@ -160,10 +161,11 @@ func (*K6) Check(ctx context.Context, arg0, checks goja.Value, extras ...goja.Va
 		fn, ok := goja.AssertFunction(val)
 		if ok {
 			tmpVal, err := fn(goja.Undefined(), arg0)
+			val = tmpVal
 			if err != nil {
-				return false, err
+				val = rt.ToValue(false)
+				exc = err
```
Comment (na--) [inline js/modules/k6/k6.go]: Hmm I'm not sure this is the correct behavior we're looking for. For one, it is actually a minor breaking change... Currently, as soon as one of the callbacks throws an error, the execution will be aborted and the other callbacks won't be called. This changes that - even if a callback throws an error, that error will be suppressed until the other callbacks are also executed. What's worse, if one of the other callbacks also throws an error, that error will overwrite the first error.

File: js/modules/k6/k6.go (hunk 3 above)
Comment (imiric) [reply js/modules/k6/k6.go]: OK, I'll remove it.

File: js/modules/k6/k6.go (hunk 4 above)
Comment (imiric) [reply js/modules/k6/k6.go]: I'm not sure you're right, but correct me if I'm wrong... :)

Take a look at the [changed test](https://github.com/loadimpact/k6/blob/af0b23d320f98ed544415d33a2953942e7803914/js/modules/k6/k6_test.go#L248-L273). I only added the metrics check to ensure the failure is correctly emmitted (which fails without this change), but the assertion is still that it returns `Error: error A at a (<eval>:3:27(6))`, i.e. the first error seen in the order the checks are executed, so this doesn't change that.

Comment (na--) [reply js/modules/k6/k6.go]: hmm I see the test, but I'm still not convinced... I don't know how goja iterates over maps and if the order of the `Object.Keys()` result is constant, so the test passing might just be a fluke. Looking at the new code here, it seems subtly wrong to me, but I might be wrong :confused:

Comment (na--) [reply js/modules/k6/k6.go]: ah, sorry, my mistake - didn't see that the `return` is still in the `for` loop, everything is fine :smile:

File: js/modules/k6/k6.go (hunk 2 above)
Comment (imiric) [reply js/modules/k6/k6.go]: I removed this comment as well, it's self-explanatory really.
