### PR TITLE
Don't panic on http requests in init context fix #699

### LINKED ISSUE #699: http.get() in init context causes nil pointer dereference panic
Running this script:
```js
import http from 'k6/http';

http.get("http://test.loadimpact.com");

export default function () {
	console.log("test");
}
```
panics with:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at 40: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at 40: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x120 pc=0xaa5915]
...
```
Not sure if we should allow http function calls in the init context at all, but either we have to show a nice error message or it should work.

### PR DESCRIPTION
**Pull request by MStoykov**
instead return an error telling you this is not supported

### CODE REVIEW

File: js/modules/k6/k6.go [hunk 1]
```diff
@@ -36,6 +36,12 @@ import (
 
 type K6 struct{}
 
+// ErrGroupInInitContext is returned when group are using in init context
+var ErrGroupInInitContext = errors.New("Using group in init context is not supported")
```
Comment (na--) [inline js/modules/k6/k6.go]: Missing `the` - `in the init context` sounds better. Also, `group` should probably be `group()`.

File: js/modules/k6/k6.go [hunk 2]
```diff
@@ -36,6 +36,12 @@ import (
...
+
+// ErrCheckInInitContext is returned when check are using in init context
+var ErrCheckInInitContext = errors.New("Using check in init context is not supported")
```
Comment (na--) [inline js/modules/k6/k6.go]: Missing `the` and brackets again

File: js/modules/k6/http/http_request.go [hunk 3]
```diff
@@ -50,6 +51,12 @@ import (
 	null "gopkg.in/guregu/null.v3"
 )
 
+// ErrHTTPForbiddenInInitContext is used when a http requests was made in the init context
+var ErrHTTPForbiddenInInitContext = errors.New("Making http requests in the init context is not supported")
+
+// ErrBatchForbiddenInInitContext is used when batch was made in the init context
+var ErrBatchForbiddenInInitContext = errors.New("Using batch in the init context is not supported")
```
Comment (na--) [inline js/modules/k6/http/http_request.go]: Not sure if it's worth it to distinguish between `http.batch()` and `http.request()` errors, reusing the first errors should be fine, after all it will be used for `http.get()`, `http.post()` and all of the rest as well.

File: js/modules/k6/http/http.go [hunk 4]
```diff
@@ -43,6 +44,9 @@ const (
 	HTTP_METHOD_OPTIONS = "OPTIONS"
 )
 
+// ErrJarForbiddenInInitContext is used when a cookie jar was made in the init context
+var ErrJarForbiddenInInitContext = errors.New("Making cookie jars in the init context is not supported")
```
Comment (na--) [inline js/modules/k6/http/http.go]: I like the distinct messages and error values, but `errors.New()` will make checking for init errors as a group (so we can use an appropriate exit code for example) very difficult. Can you create a new custom error type (`InitError` or something like that) that we can later use to group check all of those errors?

File: js/modules/k6/http/http_request.go (hunk 3 above)
Comment (MStoykov) [reply js/modules/k6/http/http_request.go]: I was wondering the same thing but decided that batch is different enough, although I am not so sure now

File: release notes/upcoming.md [hunk 5]
```diff
@@ -116,3 +116,6 @@ Thanks to @AndriiChuzhynov for implementing this! (#766)
 * Setup data: Distinguish between `undefined` (when there is no `setup()` function or when it doesn't return anything) and `null` (when `setup()` explicitly returns `null`) values for the setup `data` that's passed to the default function and `teardown()` (#799)
 * Setup data: Prevent data races by having each VU have its own independent copy of the setup data (#799)
 * HAR converter: Support HAR files that don't have a `pages` array (#806)
+* UX: Instead of panicing on some operations in the init context we not return an error that the given
```
Comment (na--) [inline release notes/upcoming.md]: typos
- `panicing` -> `panicking`
- `we not return` -> `we now return`
- `requests(batched or not)` -> `requests (batched or not)`
also (#811) should be at the end, see the other messages
