### PR TITLE
Fixing negative http_req_sending values

### LINKED ISSUE #588: Negative http_req_sending values
Peter Thompson [reported in the Slack channel ](https://k6io.slack.com/archives/C3E688J8Z/p1524046923000425) that in some cases he gets negative values for `http_req_sending`:
```
    data_received..............: 57 MB  204 kB/s
    data_sent..................: 5.7 MB 20 kB/s
    group_duration.............: avg=37.44s      min=8.22s      med=32.05s  max=1m28s  p(90)=1m8s     p(95)=1m13s
    http_req_blocked...........: avg=46.02ms     min=0s         med=0s      max=2.27s  p(90)=165.91ms p(95)=245.17ms
    http_req_connecting........: avg=4.3ms       min=0s         med=0s      max=1.03s  p(90)=8ms      p(95)=9ms
    http_req_duration..........: avg=568.81ms    min=0s         med=92.06ms max=31.53s p(90)=1.16s    p(95)=2.73s
    http_req_receiving.........: avg=56.23ms     min=0s         med=0s      max=6.71s  p(90)=6.9ms    p(95)=130.94ms
    http_req_sending...........: avg=-1.184572ms min=-1.263895s med=0s      max=1.11s  p(90)=3ms      p(95)=105ms
    http_req_tls_handshaking...: avg=42.82ms     min=0s         med=0s      max=2.26s  p(90)=135.09ms p(95)=269.01ms
    http_req_waiting...........: avg=513.76ms    min=5ms        med=74.05ms max=31.53s p(90)=987.02ms p(95)=2.4s
    http_reqs..................: 2432   8.685693/s
    iteration_duration.........: avg=1m7s        min=57.55s     med=1m5s    max=1m28s  p(90)=1m19s    p(95)=1m26s
    iterations.................: 93     0.332142/s
    vus........................: 1      min=1  max=50
    vus_max....................: 50     min=50 max=50
```

Other details:
- bug occurs in both v0.20.0 and the v0.20.0-dev-dccb254 release (containing the data race fixes in `netext.Tracer`)
- https tests only
- network interruptions or timeouts may play a role

My working hypothesis is that we shouldn't save the timestamps when there's an error in all of the [`netext.Tracer`](https://github.com/loadimpact/k6/blob/master/lib/netext/tracer.go) hooks that have potential errors.

### PR DESCRIPTION
**Pull request by luizbafilho**
When an error happened on the connection write in a TLS connection, k6 was reporting negative `http_req_sending` values in the summary, this PR fixes this problem.

fixes #588

### CODE REVIEW

File: lib/netext/tracer_test.go [hunk 1]
```diff
@@ -122,6 +123,65 @@ func TestTracer(t *testing.T) {
...
+	{
+		tracer := &Tracer{}
+		res, err := transport.RoundTrip(req.WithContext(WithTracer(context.Background(), tracer)))
+		require.NoError(t, err)
+		_, err = io.Copy(ioutil.Discard, res.Body)
+		assert.NoError(t, err)
+		assert.NoError(t, res.Body.Close())
+		tracer.Done()
+	}
+	// wait before making the request, so it fails on wrinting the request
```
Comment (na--) [inline lib/netext/tracer_test.go]: `wrinting` -> `writing`
