### PR TITLE
Fix js map causes wrong return type

### LINKED ISSUE #1195: Issues using k6/html
I am having a lot of trouble using the k6/html module where the documentation doesn't seem to match reality. 

A couple of examples of issues:

1) Using the .attr (https://docs.k6.io/docs/selectionattrname) says that it should return a string but actually returns an array

2) Attempting to reading the data from an item says that the method doesn't exist, yet is listed in the docs https://docs.k6.io/docs/selectiondatakey

Are those not the correct docs?

Thanks.

### PR DESCRIPTION
**Pull request by cuonglm**
Selection.map currently calls the underlying goquery.Selection Map. It
causes problem when running inside goja runtime, all the nodes inside
the function body is treated as goquery.Selection instead of our wrapper
Selection, thus lead to wrong calling methods.

To fix it, we wrap goquery.Selection to Selection before passing to goja.

Fixes #1195

### CODE REVIEW

File: js/modules/k6/html/html.go [hunk 1]
```diff
@@ -373,20 +373,28 @@ func (s Selection) Is(v goja.Value) bool {
 	}
 }
 
-func (s Selection) Map(v goja.Value) (result []string) {
+func (s Selection) Map(v goja.Value) []string {
```
Comment (golangcibot) [inline js/modules/k6/html/html.go]: exported method `Selection.Map` should have comment or be unexported (from `golint`)

File: js/modules/k6/html/html.go [hunk 2]
```diff
@@ -373,20 +373,28 @@ func (s Selection) Is(v goja.Value) bool {
...
 	gojaFn, isFn := goja.AssertFunction(v)
 	if !isFn {
 		common.Throw(s.rt, errors.New("Argument to map() must be a function"))
 	}
 
-	fn := func(idx int, sel *goquery.Selection) string {
+	fn := func(idx int, sel *Selection) string {
 		if fnRes, fnErr := gojaFn(v, s.rt.ToValue(idx), s.rt.ToValue(sel)); fnErr == nil {
```
Comment (MStoykov) [inline js/modules/k6/html/html.go]: Why didn't you just changed the `s.rt.ToValue(sel)` to be `s.rt.ToValue(&Selection{rt: s.rt, sel: sel, URL: s.URL}))`

Comment (MStoykov) [reply js/modules/k6/html/html.go]: Not so certain about the URL, but everything else should work as now :) without reimplementing (albeit a simple) function from goquery

Comment (cuonglm) [reply js/modules/k6/html/html.go]: Ah right, let me try.

File: js/modules/k6/html/html.go [hunk 3]
```diff
@@ -373,14 +373,15 @@ func (s Selection) Is(v goja.Value) bool {
...
+// Map implements ES5 Array.prototype.map
+func (s Selection) Map(v goja.Value) []string {
 	gojaFn, isFn := goja.AssertFunction(v)
 	if !isFn {
 		common.Throw(s.rt, errors.New("Argument to map() must be a function"))
 	}
 
 	fn := func(idx int, sel *goquery.Selection) string {
-		if fnRes, fnErr := gojaFn(v, s.rt.ToValue(idx), s.rt.ToValue(sel)); fnErr == nil {
+		if fnRes, fnErr := gojaFn(v, s.rt.ToValue(idx), s.rt.ToValue(&Selection{sel: sel, URL: s.URL, rt: s.rt})); fnErr == nil {
```
Comment (golangcibot) [inline js/modules/k6/html/html.go]: line is 123 characters (from `lll`)

**Comment by cuonglm** [comment]
> I think the fix is fine, but I would like you to add a test. There is already one for `Map` so just add one more case for example :)

Ah, I add test in separated file, cause it is not added to git. I see exiting tests now.
