### PR TITLE
Run imports once per VU

### LINKED ISSUE #659: ES6 modules instantiation works incorrectly
K6 handles E6 modules in such a way that multiple 'import' clause creates multiple instances of imported module.
To illustrate the issue I created a minimal test scenario (attached).
These is a 'i1_common' module exporting a 'context' object.
These are also additional 'i1_module' module and 'i1_main' - main test script module.
'context' object from 'i1_common' module is exported both in 'i1_module' and in 'i1_main' module.
This must be handled so that inside 'i1_main' module and inside 'i1_module' we work with the same instance of imported 'context' object, But as we see in the output this is not what happens.
When executing by k6 engine 'common' module is instantiated twice and 'i1_main' module and 'i1_module' get each its own separate instance of imported 'context' object.
As a reference implementation I created i1_index.html (attached) to run the same set of modules in browser. The below is the output from browser execution:
main 1:initial
module1_func 1:initial
module1_func 2:set_by_module1
main 2:set_by_module1   <<<< HERE IS THE DIFFERENCE
main 3:set_by_main
Here is the output from K6 execution:
main 1:initial
module1_func 1:initial
module1_func 2:set_by_module1
main 2:initial      <<<< HERE IS THE DIFFERENCE
main 3:set_by_main

This is tested with K6 executible version k6-v0.21.0-win64

[es6_modules_issue.zip](https://github.com/loadimpact/k6/files/2052574/es6_modules_issue.zip)

### LINKED ISSUE #969: Init context creates multiple instances of global variable
I've run into a nasty issue (k6 V0.23.1) which can demonstrated by using 3 js files. The main test file (test.js) refers to two other files: engine.js and common.js. engine.js also refers to common.js.

The problem in brief is that common.js has a global variable, but there are actually two instances of it: One created and accessible from test.js and one created and accessible from engine.js. I have added these 3 code files (and a support file to create UUIDs) that are as simple as possible for demonstration purposes.

The code of common.js is

```
import { uuidV4 } from "./uuid-v4.js";

var globalId;

export function initMetric(metricName) {
    if (!globalId) { 
        globalId = uuidV4();
    }    
}

initMetric("Common");

export function listMetrics() {
    console.log("globalId: " + globalId);
}
```
Now, the globalId is not unique. It's one if listMetrics is called from test.js and another if called from engine.js. Actual output:

INFO[0000] globalId: edd33b60-c51e-4e6a-bef3-20654b09d469
INFO[0000] globalId: 489d0e75-5bde-4a07-9d84-b96186c14df3

[init-test.zip](https://github.com/loadimpact/k6/files/2991270/init-test.zip)

### PR DESCRIPTION
**Pull request by MStoykov**
Previously scripts would've been ran for each time they were imported
this is both slower and not how it works in most(all?) interpreters
so we are changing the behavious to be more compliant.

Just like in c3d3fa5cff4b60e4839298643052bb3e77f1f15e , but now we clear
the cached exports when we copy the programs when making new VUs.

This is needed because otherwise:
1. We share exports between VUs so there are race conditions
2. The exports from the initial compilation without context are used
(when not running from archive) and this leads to not being able to call
functions that need context inside imported scripts.

Closes #659 and fixes #969

### CODE REVIEW

File: js/module_loading_test.go [hunk 1]
```diff
@@ -0,0 +1,303 @@
...
+	r1, err := New(&lib.SourceData{
+		Filename: "/script.js",
+		Data: []byte(`
+			import { A } from "./A.js";
+
+			export default function(data) {
+				let resp = A();
+				if (resp.status != 200) {
+				throw new Error(JSON.stringify(resp));
+					throw new Error("wrong status "+ resp.status);
```
Comment (na--) [inline js/module_loading_test.go]: Copy-paste error?

File: js/module_loading_test.go [hunk 2]
```diff
@@ -0,0 +1,303 @@
...
+			vu, err := r.NewVU(ch)
+			require.NoError(t, err)
+			err = vu.RunOnce(context.Background())
+			require.NoError(t, err)
+		})
+	}
+}
+
+func TestLoadGlobalVarsAreNotSharedBetweenVUs(t *testing.T) {
+	// This test that functions such as http.get which require context still work if they are called
```
Comment (na--) [inline js/module_loading_test.go]: Copy-paste error?

**Comment by na--** [comment]
btw I'm guessing that the module resolution function suffers from some of the same file path issues that `open()` did. It probably should be in a separate issue/PR, but just mentioning it here as something work looking into

**Comment by MStoykov** [comment]
Oh ... definitely although here it seems it was very deliberate. 
My opinion on the matter is that we should probably do as browsers have [supposedly agreed](https://stackoverflow.com/a/44931370/5427244) to do it. In our case this will mean requiring remote imports to have `https://` and everything that doesn't start with `/` `./` `../` to be considered a k6 module :) 
But definitely a different PR
