### PR TITLE
Don't log an error we are going to throw

### LINKED ISSUE #1199: Warnings for failed HTTP requests even when the "throw" option is enabled
The following code:
```js
import http from "k6/http";

export let options = {
    throw: true,
};

export default function () {
    http.get("wat://asdgasdg");
}
```

would emit both a warning, and it would throw an error:
```
WARN[0000] Request Failed                                error="Get wat://asdgasdg: unsupported protocol scheme \"wat\""
ERRO[0000] GoError: Get wat://asdgasdg: unsupported protocol scheme "wat"
	at native
	at file:///path/to/script.js:8:24(5) 
```

I think the warning message shouldn't be shown, given that users would either handle the thrown error themselves, or it would bubble up and be logged as an error anyway.

### PR DESCRIPTION
**Pull request by MStoykov**
fixes #1199

### CODE REVIEW

File: js/modules/k6/http/request_test.go [hunk 1]
```diff
@@ -485,18 +481,14 @@ func TestRequestAndBatch(t *testing.T) {
...
+		assert.Nil(t, logEntry)
 
 		t.Run("throw=false", func(t *testing.T) {
 			hook := logtest.NewLocal(state.Logger)
 			defer hook.Reset()
 
 			_, err := common.RunString(rt, `
-				var res = http.request("", "", { throw: false });
+				var res = http.request("GET", "some://example.com", null, { throw: false });
 				throw new Error(res.error);
```
Comment (na--) [inline js/modules/k6/http/request_test.go:492]: I think you should `throw` some other error here and check for it below. Right now the `assert.Contains(t, err.Error(), "unsupported protocol scheme")` check below will be satisfied even if `throw` was `true`.

Comment (MStoykov) [reply js/modules/k6/http/request_test.go:492]: hm... yeah... it wasn't working previously ... so I guess it will be nice if we now check it ... more strictly ;)

File: js/modules/k6/http/request_test.go [hunk 2]
```diff
@@ -485,22 +481,21 @@ func TestRequestAndBatch(t *testing.T) {
...
 		t.Run("throw=false", func(t *testing.T) {
 			hook := logtest.NewLocal(state.Logger)
 			defer hook.Reset()
 
 			_, err := common.RunString(rt, `
-				var res = http.request("", "", { throw: false });
-				throw new Error(res.error);
+				var res = http.request("GET", "some://example.com", null, { throw: false });
+				if (res.error.search('unsupported protocol scheme "some"')  == -1) {
+					throw new Error("wront error:"+ res.error);
```
Comment (imiric) [inline js/modules/k6/http/request_test.go:493]:
```suggestion
					throw new Error("wrong error:" + res.error);
```
