### PR TITLE
Fix duplicated error messages

### LINKED ISSUE #702: Better error messages for setup and teardown timeouts
Currently when the `setup()` or `teardown()` function times out, users see a very uninformative error message, something like:
```
ERRO[0010] Engine error                                  error="setup: context cancelled at setup (script.js:11:224(6))"
```

We should explicitly state that this error is because of a timeout and we should probably mention the `setupTimeout` or `teardownTimeout` option that would allow users to increase the allowed execution time for the particular function that timed out.

### PR DESCRIPTION
**Pull request by cuonglm**
If RootCmd.Execute returns any error, we always log that error. So
removing log from child command before returning to prevent duplicated
error message printed.

This PR also adds Hint field to ExitCode, to provide hint/details for
the underlying error. It helps the logger keep the semantic and provide
meaningful error message to user.

Updates #994
Fixes #702

### CODE REVIEW

File: cmd/cloud.go [hunk 1]
```diff
@@ -231,13 +231,15 @@ This will execute the test on the Load Impact cloud service. Use "k6 login cloud
 		}
 
 		if testProgress == nil {
-			return ExitCode{errors.New("Test progress error"), 98}
+			//nolint:golint
```
Comment (MStoykov) [inline cmd/cloud.go]: what is golint saying here ? I would've guessed it saying to you that you can use the names of the fields and skip the last one ... and I agree with that. I would also want this to be the case everywhere as otherwise someone reading this has no idea what `98` is :) 
Also I would argue `98` should be a constant somewhere

Comment (cuonglm) [reply cmd/cloud.go]: It said error message should not be capitalized.

Comment (MStoykov) [reply cmd/cloud.go]: I would argue that it would've been easier to ... not capitalize the error, also my comment still stands ;). 

For the sake of the argument how does it look capitalized and not capitalized in the terminal ?

Comment (cuonglm) [reply cmd/cloud.go]: I think it's not how it look, but golint follows https://github.com/golang/go/wiki/CodeReviewComments#error-strings

Comment (cuonglm) [reply cmd/cloud.go]: @MStoykov Yes, I'm the same side with out about constant. But it's better to do it in other PR, it's out of context for the purpose of this PR.

(I myself does not know what `98` means)

Comment (cuonglm) [reply cmd/cloud.go]: Anyway, if any of you can provide the meaning of the literal code (98, 99 ...) I can make the changes @na-- @MStoykov

File: cmd/run.go [hunk 2]
```diff
@@ -407,18 +407,15 @@ a commandline interface for interacting with it.`,
...
-						return ExitCode{errors.New("Setup timeout"), setupTimeoutErrorCode}
+						return ExitCode{err, setupTimeoutErrorCode, e.Hint()}
 					case "teardown":
-						logrus.WithField("hint", e.Hint()).Error(err)
-						return ExitCode{errors.New("Teardown timeout"), teardownTimeoutErrorCode}
+						return ExitCode{err, teardownTimeoutErrorCode, e.Hint()}
 					default:
-						logrus.WithError(err).Error("Engine timeout")
-						return ExitCode{errors.New("Engine timeout"), genericTimeoutErrorCode}
+						return ExitCode{err, genericTimeoutErrorCode, ""}
```
Comment (MStoykov) [inline cmd/run.go]: I am starting to think that it will be a good idea if we have errors that both have `ErrorCode` and `Hint` maybe as two different interfaces/implmentations. And a `ExitCodeFromError` function that gets those and just generates the `ExitCode` based on the `ErrorCode` in the error and a possible `Hint`. 
At the moment this code is pretty okay but once we start adding more possible `ExitCodeError`s it will grow and it will probably not only be here

File: cmd/root.go [hunk 3]
```diff
@@ -86,11 +86,16 @@ var RootCmd = &cobra.Command{
...
 		if e, ok := err.(ExitCode); ok {
-			os.Exit(e.Code)
+			code = e.Code
+			if e.Message != "" {
+				logger = logger.WithField("error", e.Message)
+			}
 		}
-		os.Exit(-1)
+		logger.Error(err)
+		os.Exit(code)
```
Comment (MStoykov) [inline cmd/root.go]: what was previously called internally and externally `hint` is now called `Message` here but is shown as `error` to the user. I would highly prefer it continues to be called `hint` everywhere as it's basically that .. us trying to hint to the user what went wrong

File: cmd/run.go (hunk 2 above)
Comment (cuonglm) [reply cmd/run.go]: Our current `ExitCode` does have the underlying error already, not sure why we need more.

File: cmd/root.go (hunk 3 above)
Comment (cuonglm) [reply cmd/root.go]: Fixed

File: cmd/run.go (hunk 2 above)
Comment (MStoykov) [reply cmd/run.go]: Well than probably we should extend it to use the provided `error` to determine the `ErrorCode` and `Hint` from it. 
So in this code:
https://github.com/loadimpact/k6/blob/724b72acc84c8b3d4f4101473f3237594a13f6e1/cmd/root.go#L87-L100
we can do something like 
```golang
		code := -1
		var logger logrus.FieldLogger = logrus.StandardLogger()
		if e, ok := err.(ExitCode); ok {
                        if codeErr, ok := e.(GetCoderIntrerface); ok {
			    code = codeErr.GetErrorCode()
                        }
                        if hintErr, ok := e.(GetHintInterface); ok {
				logger = logger.WithField("hint", hintErr.GetHint())
			}
		}
		logger.Error(err)
		os.Exit(code)
```
Obviously the names of the interfaces are terrible :), but I hope this is better explained. 
And then we just make all the errors that we want to make it to ExitCode implement both interfaces or ... not :)

Comment (cuonglm) [reply cmd/run.go]: @MStoykov I'm not sure it's worth to do it, as we only use `ExitCode` as the entrypoint for reporting meaningful error to user. Any other kind of errors seem to be for internal.

Comment (cuonglm) [reply cmd/run.go]: Any idea @na-- @imiric

File: cmd/root.go [hunk 4]
```diff
@@ -86,11 +86,16 @@ var RootCmd = &cobra.Command{
 // This is called by main.main(). It only needs to happen once to the rootCmd.
 func Execute() {
 	if err := RootCmd.Execute(); err != nil {
-		logrus.Error(err.Error())
+		code := -1
+		var logger logrus.FieldLogger = logrus.StandardLogger()
```
Comment (golangcibot) [inline cmd/root.go]: declarations should never be cuddled (from `wsl`)

File: cmd/root.go [hunk 5]
```diff
@@ -86,11 +86,16 @@ var RootCmd = &cobra.Command{
...
 		if e, ok := err.(ExitCode); ok {
-			os.Exit(e.Code)
+			code = e.Code
+			if e.Message != "" {
```
Comment (golangcibot) [inline cmd/root.go]: if statements should only be cuddled with assignments used in the if statement itself (from `wsl`)

File: cmd/root.go [hunk 6]
```diff
@@ -86,11 +86,16 @@ var RootCmd = &cobra.Command{
...
+				logger = logger.WithField("hint", e.Message)
+			}
 		}
-		os.Exit(-1)
+		logger.Error(err)
```
Comment (golangcibot) [inline cmd/root.go]: expressions should not be cuddled with blocks (from `wsl`)

**Comment by cuonglm** [comment]
`wsl` seems to be annoyed.

**Comment by na--** [comment]
> `wsl` seems to be annoyed.

 merge or rebase your branch on `master`

File: cmd/cloud.go (hunk 1 above)
Comment (MStoykov) [reply cmd/cloud.go]: cc @na--

Comment (cuonglm) [reply cmd/cloud.go]: @MStoykov Fixed

File: cmd/root.go (hunk 3 above)
Comment (MStoykov) [reply cmd/root.go]: Can you also name name the struct field `Hint` instead of `Message`

Comment (cuonglm) [reply cmd/root.go]: Fixed

File: cmd/common.go [hunk 7]
```diff
@@ -45,10 +45,12 @@ func must(err error) {
 	}
 }
 
-// Silently set an exit code.
+// ExitCode uses to silently set an exit code.
```
[the remark this answers is not in the document]
Comment (cuonglm) [reply cmd/common.go]: Fixed

File: lib/types/types_test.go [hunk 8]
```diff
@@ -90,7 +90,7 @@ func TestNullDecoder(t *testing.T) {
 	}
 
 	for k, v := range input {
-		t.Run("Error Message/"+k, func(t *testing.T) {
```
Comment (MStoykov) [inline lib/types/types_test.go]: This seems to have nothing to do with this PR ?

Comment (cuonglm) [reply lib/types/types_test.go]: Yes, seems Goland sucks when doing rename.

Comment (cuonglm) [reply lib/types/types_test.go]: Fixed
