### PR TITLE
bug/1560 tlsCipherSuites and tlsVersion marshaling

### LINKED ISSUE #1560: tlsCipherSuites and tlsVersion aren't properly marshalled in archives
If we have a script like this:
```
export let options = {
    tlsCipherSuites: [
        "TLS_RSA_WITH_RC4_128_SHA",
        "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
    ],
    tlsVersion: {
        min: "tls1.0",
        max: "tls1.2"
    }
};
```
and we archive it with `k6 archive`, we'd get something like this for the options :sob: 
```
    "tlsCipherSuites": [
      5,
      49162
    ],
    "tlsVersion": {
      "min": "",
      "max": ""
    },
```

Another way to test it:
```
$ k6 inspect 'github.com/loadimpact/k6/samples/tlsconfig.js' | jq '.tlsCipherSuites,.tlsVersion' 
[
  5,
  156
]
{
  "min": "ssl3.0",
  "max": "tls1.2"
}

$ k6 archive 'github.com/loadimpact/k6/samples/tlsconfig.js'  && (tar xfO archive.tar metadata.json | jq '.options.tlsCipherSuites,.options.tlsVersion') 
[
  5,
  156
]
{
  "min": "",
  "max": ""
}
```

notice how `tlsVersion` was reasonably ok with `k6 inspect`, there are probably 2 different bugs here...

### PR DESCRIPTION
**Pull request by berndhartzer**
Closes #1560

### CODE REVIEW

**Comment by berndhartzer** [comment]
> Hi @berndhartzer, thanks for the PR !!! 🎉
> 
> We have fixed the `lint` to not get wrong files (or at least for your case) so please just rebase on top of the current master and force-push in order to get the [fix](https://github.com/loadimpact/k6/commit/4920d5371f01f1ec3fed761f52bc05ed4a9b73a5)

Thanks @MStoykov I've fixed it now 🙂

**Review by MStoykov — APPROVED** [review]

File: lib/options.go [hunk 1]
```diff
@@ -96,9 +96,24 @@ func (v *TLSVersions) isTLS13() bool {
...
+		if suiteName, ok := SupportedTLSCipherSuitesToString[id]; ok {
+			suiteNames = append(suiteNames, suiteName)
+		} else {
+			return nil, errors.Errorf("Unknown cipher suite id: %d", id)
+		}
+	}
+
+	marshaled, _ := json.Marshal(suiteNames)
+
+	return marshaled, nil
```
Comment (imiric) [inline lib/options.go:114]: Why not just `return json.Marshal(suiteNames)`?

File: lib/options.go [hunk 2]
```diff
@@ -235,7 +250,7 @@ type Options struct {
 
 	// Specify TLS versions and cipher suites, and present client certificates.
 	TLSCipherSuites *TLSCipherSuites `json:"tlsCipherSuites" envconfig:"K6_TLS_CIPHER_SUITES"`
-	TLSVersion      *TLSVersions     `json:"tlsVersion" envconfig:"K6_TLS_VERSION"`
+	TLSVersion      *TLSVersions     `json:"tlsVersion" ignored:"true"`
```
Comment (imiric) [inline lib/options.go:253]: FWIW I think we could fix the envconfig issue with a [custom decoder](https://github.com/kelseyhightower/envconfig#custom-decoders) and keep the `K6_TLS_VERSION` env var, but since it's not documented in the k6 docs, and making it work is tricky in general because of #883, I'm OK with ignoring it.

**Review by imiric — APPROVED** [review]
LGTM, just a nitpick and a comment.

File: lib/options.go (hunk 1 above)
Comment (berndhartzer) [reply lib/options.go:114]: Good question, no reason not to! Will update this now

File: lib/options.go (hunk 2 above)
Comment (na--) [reply lib/options.go:253]: We can't keep delaying the envconfig removal, so let's ignore this for now and fix it properly everywhere soon.

**Review by na-- — APPROVED** [review]

**Review by imiric — APPROVED** [review]
Thanks for your work!
