### PR TITLE
fix(httpext): remove user credentials from metric tags

### LINKED ISSUE #1103: Credentials leak in HTTP metric tags
If you run the following script with `k6 run -o json`:
```js
import http from "k6/http";

export default function () {
    http.get("https://testuser1:testpwd1@httpbingo.org/basic-auth/testuser1/testpwd1");
    http.get("https://testuser2:testpwd2@httpbingo.org/digest-auth/auth/testuser2/testpwd2", { auth: "digest" });
}
```

you'd currently get metrics like these:
```json
{"type":"Point","data":{"time":"2019-08-06T10:52:01.259896979+03:00","value":164.589459,"tags":{"group":"","method":"GET","name":"https://testuser1:testpwd1@httpbingo.org/basic-auth/testuser1/testpwd1","proto":"HTTP/2.0","status":"200","tls_version":"tls1.2","url":"https://testuser1:testpwd1@httpbingo.org/basic-auth/testuser1/testpwd1"}},"metric":"http_req_duration"}
{"type":"Point","data":{"time":"2019-08-06T10:52:01.568763642+03:00","value":153.52556,"tags":{"group":"","method":"GET","name":"https://testuser2:testpwd2@httpbingo.org/digest-auth/auth/testuser2/testpwd2","proto":"HTTP/2.0","status":"200","tls_version":"tls1.2","url":"https://httpbingo.org/digest-auth/auth/testuser2/testpwd2"}},"metric":"http_req_duration"}
```

The `name` and `url` tags for these metrics leak the credentials, which is not what most users would want. And if they want to distinguish between the metrics based on the credentials, they can always manually set the `name` tag or any other custom one.

### PR DESCRIPTION
**Pull request by imiric**
This fixes the credential leak in HTTP metric tags.

Closes #1103

### CODE REVIEW

File: lib/netext/httpext/request.go [hunk 1]
```diff
@@ -66,6 +67,20 @@ func (u URL) GetURL() *url.URL {
...
+// Return a sanitized URL, clean of e.g. user credentials
+func cleanURL(urlString string) string {
+	idxEnd := strings.Index(urlString, "@")
+	if idxEnd == -1 {
+		return urlString
+	}
+	idxStart := strings.Index(urlString[:idxEnd], "/")
+	if idxStart != -1 {
+		return fmt.Sprintf("%s%s", urlString[0:idxStart+2], urlString[idxEnd+1:])
+	} else {
```
Comment (golangcibot) [inline lib/netext/httpext/request.go]: `if` block ends with a `return` statement, so drop this `else` and outdent its block (from `golint`)

File: lib/netext/httpext/request_test.go [hunk 2]
```diff
@@ -82,3 +82,25 @@ func TestMakeRequestError(t *testing.T) {
...
+		{"https://user:pass@example.com/", "https://example.com/"},
+		{"https://user:pass@example.com/path?a=1&b=2", "https://example.com/path?a=1&b=2"},
+		{"https://user:pass@example.com/${}", "https://example.com/${}"},
+		{"@malformed/url", "@malformed/url"},
+		{"not a url", "not a url"},
+	}
+
+	for _, tc := range testCases {
+		t.Run(tc.url, func(t *testing.T) {
+			res := cleanURL(tc.url)
```
Comment (golangcibot) [inline lib/netext/httpext/request_test.go]: Using the variable on range scope `tc` in function literal (from `scopelint`)

File: lib/netext/httpext/request_test.go [hunk 3]
```diff
@@ -82,3 +82,25 @@ func TestMakeRequestError(t *testing.T) {
...
+			require.Equal(t, tc.expected, res)
```
Comment (golangcibot) [inline lib/netext/httpext/request_test.go]: Using the variable on range scope `tc` in function literal (from `scopelint`)

File: js/modules/k6/http/request_test.go [hunk 4]
```diff
@@ -770,8 +772,8 @@ func TestRequestAndBatch(t *testing.T) {
 					assert.NoError(t, err)
 
 					sampleContainers := stats.GetBufferedSamples(samples)
-					assertRequestMetricsEmitted(t, sampleContainers[0:1], "GET", sr("HTTPBIN_IP_URL/digest-auth/auth/bob/pass"), url, 401, "")
-					assertRequestMetricsEmitted(t, sampleContainers[1:2], "GET", sr("HTTPBIN_IP_URL/digest-auth/auth/bob/pass"), url, 200, "")
+					assertRequestMetricsEmitted(t, sampleContainers[0:1], "GET", sr("HTTPBIN_IP_URL/digest-auth/auth/bob/pass"), urlExpected, 401, "")
```
Comment (golangcibot) [inline js/modules/k6/http/request_test.go]: line is 135 characters (from `lll`)

File: js/modules/k6/http/request_test.go [hunk 5]
```diff
@@ -770,8 +772,8 @@ func TestRequestAndBatch(t *testing.T) {
...
+					assertRequestMetricsEmitted(t, sampleContainers[1:2], "GET", sr("HTTPBIN_IP_URL/digest-auth/auth/bob/pass"), urlExpected, 200, "")
```
Comment (golangcibot) [inline js/modules/k6/http/request_test.go]: line is 135 characters (from `lll`)

File: lib/netext/httpext/request.go (hunk 1 above)
Comment (cuonglm) [inline lib/netext/httpext/request.go]: This `else` is redundant.

File: lib/netext/httpext/request.go [hunk 6]
```diff
@@ -66,6 +67,20 @@ func (u URL) GetURL() *url.URL {
...
+		return urlString
+	}
+}
```
Comment (imiric) [inline lib/netext/httpext/request.go]: I don't like this implementation, but it was the easiest way to clean both the `url` and `name` tags.

Initially I tried `url.Parse()`-ing, setting `User = nil` and returning `String()`, which is much cleaner, but this has the risk of mangling non-URL `name` tags, which would need escaping, etc. and it gets messy quickly as well. I also didn't make it a method on `httpext.URL`, since we use `url.URL` directly in `transport.go:114`, and that needs to be cleaned also.

Let me know if you have a better idea of doing this.

Also, note that this removes the credentials entirely, but we might want to consider masking them instead, e.g. "https://******:******@example.com/", in case that is more useful to see.

Comment (cuonglm) [reply lib/netext/httpext/request.go]: I mean you can do:

```
if {
    return x
}

return y
```
instead of:

```
if {
    return x
else {
    return y
}
```

Comment (imiric) [reply lib/netext/httpext/request.go]: Yeah, @golangcibot pointed that out as well, d'oh!

But I mean more from a design perspective, if it's fine that were parsing strings like this. It makes me feel uneasy that we might miss an edge case :)

Comment (na--) [reply lib/netext/httpext/request.go]: Yeah, I don't like this stringy approach as well, but I'm not sure how exactly you should implement something better... Though I'm also not sure that the current way (`strings.Index(urlString, "@")`) won't result in any false-positives - can't you have `@` in the query parameters for example?

I'd suggest investigating how our custom `httpext.URL` type works and is how and where it's used, because it may actually give us an opportunity to sanitize the credentials in its constructor. That way we can then use their sanitized versions when we get to constructing the metric tags. In my head, we have the following requirements for this task:
- any specified credentials shoudn't be visible in the system metric tags `url` and `name`
- however, if the user manually specifies the `name` tag, then that shouldn't ever be modified, even if it contains credentials
- any specified credentials should still be present in the `url` property of the JS `Response` object: https://docs.k6.io/docs/response-k6http
- ideally (see below), it would be good to still distinguish between metrics from authenticated and non-authenticated URLs

> Also, note that this removes the credentials entirely, but we might want to consider masking them instead, e.g. `https://******:******@example.com/`, in case that is more useful to see.

I personally like that idea very much - it will help users distinguish which metrics come from an authenticated URL without exposing the credentials.

Comment (imiric) [reply lib/netext/httpext/request.go]: > can't you have @ in the query parameters for example?

I was relying on "@" being a reserved character, and that users would escape it as `%40` in the path or query string. :) But yeah, far from ideal.

I like your suggestions, thanks. I'll go through the flow of how `httpext.URL` is used again and think about a nicer solution, while incorporating the masking feature.

Comment (imiric) [reply lib/netext/httpext/request.go]: @na-- take a look at the latest commit 599112f (I'll squash it before merging).

I think the implementation is more robust now, I took inspiration from `http.stripPassword()`. :)

I preferred to leave it as a standalone function instead of coupling it with `httpext.URL`, since that struct is not used everywhere, and the cleaning is only done where needed, so it doesn't change how URLs are handled internally, so less chance for bugs.

I also considered cleaning the WebSocket URL tag, and even though [the spec mentions HTTP auth as possible](https://tools.ietf.org/html/rfc6455#section-10.5), `gorilla/websocket` [doesn't support passing credentials in the URI](https://github.com/gorilla/websocket/blob/483fb8d7c32fcb4b5636cd293a92e3935932e2f4/client.go#L173-L176) (though it does support manually setting the `Authorization` header), so that wouldn't work for this use case anyway.

One small note, though: this is currently deviating from:

> however, if the user manually specifies the `name` tag, then that shouldn't ever be modified, even if it contains credentials

That is, if the name tag looks like a URL and it has credentials, it will be cleaned regardless if the user set it or not. In general, I think this is a good idea in order to protect users against inadvertently leaking credentials, but it also keeps this implementation simpler, so win=win? :)

Let me know what you think.

Comment (na--) [reply lib/netext/httpext/request.go]: > One small note, though: this is currently deviating from:
>  >  however, if the user manually specifies the name tag, then that shouldn't ever be modified, even if it contains credentials
>
> That is, if the name tag looks like a URL and it has credentials, it will be cleaned regardless if the user set it or not. In general, I think this is a good idea in order to protect users against inadvertently leaking credentials, but it also keeps this implementation simpler, so win=win? :)

Actually, I'm not sure this is currently deviating from it. Looking at the `if _, ok := tags["name"]; !ok && state.Options.SystemTags["name"]` check below, any manually specified `name` tag won't be modified. And I strongly feel that users should be able to manually specify whatever `name` tag they desire, even if it contains credentials. I feel like automagically sanitizing user-specified values would just annoy users, or at least it will annoy me as a user, given that I can just choose to set another tag k6 wouldn't care about...

Comment (imiric) [reply lib/netext/httpext/request.go]: Ah, you're right, I misread and didn't test that. A manually set `name` tag doesn't get cleaned.

I see your point about it possibly being annoying, and stand corrected. :)

Let me know if there's anything pending here.

File: lib/netext/httpext/request.go [hunk 7]
```diff
@@ -66,6 +67,24 @@ func (u URL) GetURL() *url.URL {
...
+		// it's a proper URL, mask credentials
+		old := fmt.Sprintf("%s@", u.User.String())
+		new := "****@"
+		_, passSet := u.User.Password()
+		if passSet {
+			new = fmt.Sprintf("****:%s", new)
+		}
+		clean := strings.Replace(u.String(), old, new, 1)
+		// Replace back any literal `${}` placeholders escaped by `u.String()`
+		return strings.Replace(clean, `$%7B%7D`, `${}`, -1)
```
Comment (na--) [inline lib/netext/httpext/request.go]: This seems like a bit of a nasty hack :smile: In general, I slightly dislike that we're having to parse the previously parsed URL here and do a bunch of shifty string operations to sanitize it. This shouldn't noticeably affect performance, even when we do it twice for each URL in the script, bit it just seems like a waste, especially given the fact that most URLs probably won't have credentials... 

Why are you reluctant to mess with the `NewURL()` constructor https://github.com/loadimpact/k6/blob/d385166a821a8cd98a4ab2c158b3982d87ee61a5/lib/netext/httpext/request.go#L59-L62
It seems like it would be relatively easy to just add another `SanitizedURL` property or something like that, which can just be the same string as the URL if there's no authentication, and sanitized from the already parsed URL if there is. In my head that won't be more difficult to trace than the current implementation, so I don't think it's a case of premature optimization, but I might be wrong :smile: @MStoykov, thoughts?

Comment (MStoykov) [reply lib/netext/httpext/request.go]: I am of the opinion that given the amount of strings that the above  code will generate I am pretty sure it will have performance impact if we do it for ALL urls. IMHO we should at least check if we need to do anything at all before we even parse it back from string to URL ... given that we already have it as a URL. 
Also given that .. I am pretty sure it would be better if we just copy the URL , change the user and password and string it back ... 
And ... isn't Name supposed to stay if it's set by the user and if it's not it's the same as the URL so we don't need to do the work twice ? 
As a whole I think that maybe taking a step back and working directly with the URLs will be better than what you are currently trying to do

Comment (imiric) [reply lib/netext/httpext/request.go]: > Why are you reluctant to mess with the NewURL() constructor

I guess I was trying to introduce the least amount of changes while I'm getting familiar, but you're both right that it would be more efficient to create a clean URL in the constructor once and avoid parsing it every time the tags are set.

I'll refactor this again, thanks for the feedback.

Comment (imiric) [reply lib/netext/httpext/request.go]: @na-- @MStoykov Take a look at the latest commit 6ab3603b. I suppose it's cleaner and more efficient, but I don't like that `httpext.URL` now wraps 4 representations of potentially the same URL. It's a bit messy to me, but I'm not familiar enough with the codebase to make a concrete suggestion for fixing it.

File: lib/netext/httpext/request.go [hunk 8]
```diff
@@ -49,16 +50,44 @@ type HTTPRequestCookie struct {
...
 
 // NewURL returns a new URL for the provided url and name. The error is returned if the url provided
 // can't be parsed
 func NewURL(urlString, name string) (URL, error) {
 	u, err := url.Parse(urlString)
-	return URL{u: u, Name: name, URL: urlString}, err
+	newURL := URL{u: u, Name: name, URL: urlString}
+	newURL.CleanURL = newURL.Clean()
+	if urlString == name {
+		newURL.Name = newURL.CleanURL
```
Comment (imiric) [inline lib/netext/httpext/request.go]: This handles [this use case](https://github.com/loadimpact/k6/blob/6ab3603bbe84509e1cd37fabc5c45b3e7c527429/js/modules/k6/http/http_url.go#L38).

**Comment by MStoykov** [comment]
Again I did some [benchmarking](https://gist.github.com/MStoykov/280f527fdf0834d275d40b5133064e4b): 
```
$ go test -v -bench=. -benchmem
goos: linux
goarch: amd64
pkg: github.com/loadimpact/k6/b
BenchmarkA-4     3000000               546 ns/op             144 B/op          7 allocs/op
BenchmarkB-4     5000000               318 ns/op              56 B/op          3 allocs/op
PASS
ok      github.com/loadimpact/k6/b      4.188s
```

Here `B` is my implementation where ... I set URL.User to `USER@PASS` and than let URL.String() does what it does and revert the change. 
Unfortunately `*` gets escaped but given the performance difference and that this will be a hot path in tests with credentials ... I would argue it's worth it. 
I haven't tested if this is threadsafe but it looks like it ;) though I would recommend testing it ;)

**Comment by imiric** [comment]
@MStoykov Unfortunately, the implementation can't be that simple. We can use `-` instead of `*` for masking symbols, so that's not a problem, but if we use `URL.String()` directly our `${}` placeholders also get escaped:

```
        Error:          Not equal:
                        expected: "https://----:----@example.com/${}/${}"
                        actual  : "https://----:----@example.com/$%7B%7D/$%7B%7D"
        Test:           TestURL/Clean/https://user:pass@example.com/${}/${}
```

And dealing with that issue also gets messy and expensive:

```
	if u.u != nil && u.u.User != nil {
		tmpU := *u.u
		tmpU.User = maskUserInfo
		tmpU.Path = ""
		q := ""
		if tmpU.RawQuery != "" {
			q = "?" + tmpU.RawQuery
			tmpU.RawQuery = ""
		}
		out = fmt.Sprintf("%s%s%s", tmpU.String(), u.u.Path, q)
	}
```

There might be a more performant way of doing the above, but on my machine it's only a marginal improvement over the original stringified approach (BenchmarkC):

```
BenchmarkA-12           10000000               198 ns/op             144 B/op          7 allocs/op
BenchmarkB-12           20000000                97.5 ns/op            56 B/op          3 allocs/op
BenchmarkC-12           10000000               172 ns/op             104 B/op          5 allocs/op
```

... and more things could go wrong in this version, since it's re-assembling the URL.

I'm not sure. Let me know if you have any suggestions.

**Comment by MStoykov** [comment]
@imiric I published a new version which is even faster ;) : 
```
BenchmarkA-4     5000000               348 ns/op             144 B/op          7 allocs/op
BenchmarkA-4     3000000               443 ns/op             144 B/op          7 allocs/op
BenchmarkA-4     3000000               464 ns/op             144 B/op          7 allocs/op
BenchmarkA-4     3000000               551 ns/op             144 B/op          7 allocs/op
BenchmarkA-4     5000000               359 ns/op             144 B/op          7 allocs/op
BenchmarkB-4    10000000               248 ns/op              56 B/op          3 allocs/op
BenchmarkB-4     3000000               369 ns/op              56 B/op          3 allocs/op
BenchmarkB-4    10000000               327 ns/op              56 B/op          3 allocs/op
BenchmarkB-4     5000000               229 ns/op              56 B/op          3 allocs/op
BenchmarkB-4    10000000               251 ns/op              56 B/op          3 allocs/op
BenchmarkC-4    20000000                74.4 ns/op            32 B/op          1 allocs/op
BenchmarkC-4    20000000                57.8 ns/op            32 B/op          1 allocs/op
BenchmarkC-4    20000000                56.7 ns/op            32 B/op          1 allocs/op
BenchmarkC-4    30000000                61.8 ns/op            32 B/op          1 allocs/op
BenchmarkC-4    30000000                71.8 ns/op            32 B/op          1 allocs/op
```

**Comment by imiric** [comment]
@MStoykov That's great, but we can't rely on `strings.Index(out, "@")`, as "@" can technically be unescaped elsewhere.

I'm all for improving the performance here, but I'm not sure we can escape the penalty if credentials are defined and we want to do this safely.

@na-- @cuonglm Thoughts?

**Comment by MStoykov** [comment]
@imiric but the first one will be the one we care about ;) (also not sure if you can have an unescaped one but am too lazy to go and read the RFC to check, but it doesn't matter) Also I happen to like my code ...more ;)

**Comment by cuonglm** [comment]
> @MStoykov That's great, but we can't rely on `strings.Index(out, "@")`, as "@" can technically be unescaped elsewhere.
> 
> I'm all for improving the performance here, but I'm not sure we can escape the penalty if credentials are defined and we want to do this safely.
> 
> @na-- @cuonglm Thoughts?

I would agree with @MStoykov, `strings.Index(out, "@")` is good enough. We should go with the most simple and fastest. If the url input has `@` escaped, then it's probably not a normal user 😄
