### PR TITLE
Re-enable the usage report

### LINKED ISSUE #1301: Fix the usage report
The usage report in #1007 is currently broken and disabled. Because we want to maximally preserve user privacy and not send any potentially sensitive data, we can't just package the new `execution` option and send that, since it could contain sensitive data we don't want to know.

Instead, we need to move the sending of the usage report from before the start of the script to the end of the execution and send only a rough summary of what was actually executed. So:
- the `k6_version`, `goos` and `goarch` JSON fields remain unchanged
- `vus_max`, `iterations` and `duration` would get their values from the [`ExecutionState`](https://github.com/loadimpact/k6/blob/f6be35cfa006c56954d6821e0f94f4863f063e45/lib/execution.go#L123)
- `st_duration` will be removed, since it doesn't make a lot of sense
- we might want to also add a field for the used executor types, but only their types and number, no names or any other details

### PR DESCRIPTION
**Pull request by imiric**
Closes #1301

This re-enables the usage report, and updates its payload to include executor types and number of them used.

Example of payload:

```json
{
  "duration": "1m0.029405562s",
  "executors": {
    "constant-arrival-rate": 1,
    "constant-looping-vus": 2,
    "externally-controlled": 1,
    "per-vu-iterations": 1,
    "shared-iterations": 1,
    "variable-arrival-rate": 1,
    "variable-looping-vus": 2
  },
  "goarch": "amd64",
  "goos": "linux",
  "iterations": 2175,
  "k6_version": "0.26.0",
  "vus_max": 130
}
```

Note that currently this POST to https://reports.k6.io/ fails with a `502 Bad Gateway`, which I'm assuming is because of the change in schema and the backend will have to be updated to match. The differences are minor: this drops `duration_st` and adds `executors`.

### CODE REVIEW

File: cmd/run.go [hunk 1]
```diff
@@ -369,6 +339,10 @@ a commandline interface for interacting with it.`,
 			logger.Warn("No data generated, because no script iterations finished, consider making the test duration longer")
 		}
 
+		if !conf.NoUsageReport.Bool {
+			_ = reportUsage(execScheduler)
```
Comment (imiric) [inline cmd/run.go]: This is not done in a goroutine anymore because it's done after the end of execution, and unless we manually synchronize it, the process will exit before the report is submitted.

So currently this adds a slight delay before the summary report is shown, which might be annoying, but then there's always `K6_NO_USAGE_REPORT`.

Also, I changed from using `panic()` to returning an error, but since it's never checked, maybe we shouldn't bother? The `panic` doesn't seem right for this, though. Let me know.

File: cmd/run.go [hunk 2]
```diff
@@ -414,6 +388,36 @@ a commandline interface for interacting with it.`,
...
+	executorConfigs := execScheduler.GetExecutorConfigs()
+	execState := execScheduler.GetState()
+
+	executors := make(map[string]int)
+	for _, ec := range executorConfigs {
+		executors[ec.GetType()]++
+	}
+
+	body, err := json.Marshal(map[string]interface{}{
+		"k6_version": consts.Version,
```
Comment (imiric) [inline cmd/run.go]: Should we use `consts.FullVersion()` here instead and remove the `goos`/`goarch` properties since they're in the full version? It might be handy to keep them apart, but the full version also includes the build info, which might be useful.

Comment (MStoykov) [reply cmd/run.go]: I am for using `consts.FullVersion()` and keeping `goos` and `goarch` separate

File: cmd/run.go [hunk 3]
```diff
@@ -414,6 +388,36 @@ a commandline interface for interacting with it.`,
...
+		"executors":  executors,
+		"vus_max":    lib.GetMaxPossibleVUs(execPlan),
```
Comment (MStoykov) [inline cmd/run.go]: I think we also would want to see what the actual initialized VU count is and how much it differs from the preallocated VU count.

File: cmd/run.go (hunk 1 above)
Comment (MStoykov) [reply cmd/run.go]: Could the summary take long enough time for there to be time for this to finish? 
I do know that on especially metric heavy tests it does take some time to show the end summary so maybe it is slow enough in which case I would argue simple sync.WaitGroup or chan struct{} will probably be simple enough and beneficial enough to offset the added code, otherwise -  no.
Can you run a couple of tests and see if it gets slower with the length of test?

I do agree that panicking is not a good idea but maybe log it as info?  or debug?

**Comment by MStoykov** [comment]
>  I'm not sure if that's what @na-- meant 

I would argue we want more :). I am pretty sure he meant everything but the name or as much as possible :).

File: cmd/run.go (hunk 1 above)
Comment (imiric) [reply cmd/run.go]: > Can you run a couple of tests and see if it gets slower with the length of test?

Yes, you're right. If the test is long or metric-heavy then the time to process the summary is enough for the usage report to be submitted.

But we can't rely on that, which would make the usage results even less useful.

So I added a `WaitGroup` in 03d027d0. There's still a slight delay at the end, but it doesn't impact the end summary, and it can always be disabled with the env var.

> I do agree that panicking is not a good idea but maybe log it as info? or debug?

We shouldn't log or output anything at this point since it could mangle the summary report, or be printed below it, which is a bit unsightly.

I left it as returning an error that is not checked. We could submit it to Sentry just to catch it failing, but then that would be another request to make, so not sure.

File: cmd/run.go (hunk 2 above)
Comment (imiric) [reply cmd/run.go]: It's a bit of duplication, but sure, I changed it in b0b153a2.

File: cmd/run.go (hunk 3 above)
Comment (imiric) [reply cmd/run.go]: I added the initialized VU count in f271e476, but I'm wondering if we should add more data to this. The preallocated VU count is ony relevant for the arrival rate executors, no? And isn't this stateful information that will change throughout the test? What I mean is, why does it matter how many initialized/preallocated VUs there were at the end of the test? That value is not that useful by itself, unlike `MaxVUs`, which remains constant.

I find even the executor count as too much detail, though that at least would give an idea which executors are most widely used. Anything more starts to resemble analytics-level of reporting, which could be too intrusive for comfort.

Anyway, if you guys feel strongly about it, please post an example payload or schema of what you have in mind.

File: cmd/run.go (hunk 2 above)
Comment (imiric) [reply cmd/run.go]: Actually, we should probably avoid using composite strings here. Otherwise aggregating the results would become a parsing nightmare...

So I'll revert this to `const.Version` and if we need additional info let's add it in separate fields.

File: cmd/run.go [hunk 4]
```diff
@@ -407,13 +385,47 @@ a commandline interface for interacting with it.`,
...
+		"iterations": execState.GetFullIterationCount(),
+		"duration":   execState.GetCurrentTestRunDuration().String(),
+		"goos":       runtime.GOOS,
+		"goarch":     runtime.GOARCH,
+	})
+	if err != nil {
+		return err
+	}
+
+	res, err := http.Post("https://reports.k6.io/", "application/json", bytes.NewBuffer(body))
```
Comment (imiric) [inline cmd/run.go]: This should probably timeout after, say, 1s?

File: cmd/run.go (hunk 1 above)
Comment (na--) [reply cmd/run.go]: No need to log or submit any failures. This is not critical, just an optional best-effort ping.

File: cmd/run.go (hunk 2 above)
Comment (na--) [reply cmd/run.go]: Yes, also we don't want to expose any potentially sensitive things like commit IDs/tag names from the full version information. Or break backwards compatibility (the same backend will receive pings from all sorts of k6 versions). :+1: for `consts.Version`

File: cmd/run.go (hunk 4 above)
Comment (na--) [reply cmd/run.go]: `1s` seems to short, but now that this is at the end of the test execution, we can't delay too much. So, say, `3s`?

**Comment by na--** [comment]
> > I'm not sure if that's what @na-- meant
> 
> I would argue we want more :). I am pretty sure he meant everything but the name or as much as possible :).

No, quite the opposite, I want as little as possible. I originally meant only a simple list of the executor types and their total count, but a count by executor type is also fine. We don't want any more details, considering they can contain sensitive names, environment variables, function names and who knows what else in the future.

File: cmd/run.go [hunk 5]
```diff
@@ -369,6 +339,14 @@ a commandline interface for interacting with it.`,
 			logger.Warn("No data generated, because no script iterations finished, consider making the test duration longer")
 		}
 
+		reportWg := &sync.WaitGroup{}
```
Comment (na--) [inline cmd/run.go]: Given that this is now a bit blocking, I think we should move it as early as possible. So, maybe right above `if quiet || !stdoutTTY {` ?

File: cmd/run.go (hunk 3 above)
Comment (na--) [reply cmd/run.go]: >  Anything more starts to resemble analytics-level of reporting, which could be too intrusive for comfort.

Fully agree, so as I said, as little information as possible. I don't even really think we should have `lib.GetMaxPossibleVUs(execPlan),`, rather `vus_max` can just be `execState.GetInitializedVUsCount()`. It's much more useful to know how many VUs were actually used...

**Comment by imiric** [comment]
@na-- @MStoykov I think all changes were addressed in the latest push. Please check again and let me know. I'll squash/rebase.

File: cmd/run.go [hunk 6]
```diff
@@ -407,13 +386,48 @@ a commandline interface for interacting with it.`,
 			<-sigC
 		}
 
+		reportWg.Wait()
```
Comment (MStoykov) [inline cmd/run.go]: I wonder if it won't be better if instead of having http timeout, we wait here for n seconds (let say 3 again) and if it doesn't end by then just to continue executing ....(this can be done with a simple `select` and `chan struct{}` that get closed by the report goroutine)
This will both mean that any bugs in how timeout works will be circumvented (although I just read the documentation and I think it takes into account all the things).
It also means that if the request would take 5 seconds, but also the summary will take 6, the report will actually finish ...

Comment (imiric) [reply cmd/run.go]: Sounds good, let me know if 963ca44c does what you had in mind.

Comment (MStoykov) [reply cmd/run.go]: mostly - yes, but I didn't want `reportUsage` to know about the channel, it can just be closed after the call to `reportUsage` :D

Comment (MStoykov) [reply cmd/run.go]: also I think this will make the user wait for 3 seconds *always* if they have disabled the report

Comment (imiric) [reply cmd/run.go]: D'oh, you're right about that last point. Please hold :)

Comment (imiric) [reply cmd/run.go]: OK, hopefully 3a89667b resolves all issues.
