### PR TITLE
Fix blacklistIPs JS configuration

### LINKED ISSUE #973: blacklistIPs JS configuration isn't parsed correctly
Running this script:

```js
import http from "k6/http";

export let options = {
    blacklistIPs: ["34.232.164.109/32"]
};

export default function () {
    http.get("http://34.232.164.109")
}
```
will fail with the error `ERRO[0000] json: cannot unmarshal string into Go struct field Options.blacklistIPs of type net.IPNet`

Another piece of https://github.com/loadimpact/k6/issues/883 I guess...

### PR DESCRIPTION
**Pull request by THoelzel**
Net.IPNet does not support JSON unmarshalling, causing the blacklistIPs
configuration to fail when set through JS.
Fixed by wrapping net.IPNet for the purpose of JSON unmarshalling.

Fixes #973

### CODE REVIEW

File: cmd/options.go [hunk 1]
```diff
@@ -122,7 +121,7 @@ func getOptions(flags *pflag.FlagSet) (lib.Options, error) {
 		return opts, err
 	}
 	for _, s := range blacklistIPStrings {
-		_, net, err := net.ParseCIDR(s)
+		net, err := lib.ParseCIDR(s)
```
Comment (golangcibot) [inline cmd/options.go]: shadow: declaration of "err" shadows declaration at line 119 (from `govet`)

File: lib/options.go [hunk 2]
```diff
@@ -205,6 +205,43 @@ func (c *TLSAuth) Certificate() (*tls.Certificate, error) {
...
 
+// IPNet is a wrapper around net.IPNet for JSON unmarshalling
+type IPNet struct {
+	net.IPNet
+}
+
+// UnmarshalJSON populates the IPNet from the given CIDR JSON
+func (ipnet *IPNet) UnmarshalJSON(b []byte) (err error) {
+	var cidr string
+	if err := json.Unmarshal(b, &cidr); err != nil {
```
Comment (golangcibot) [inline lib/options.go]: shadow: declaration of "err" shadows declaration at line 214 (from `govet`)

File: js/runner_test.go [hunk 3]
```diff
@@ -786,6 +786,43 @@ func TestVUIntegrationBlacklist(t *testing.T) {
...
+	r2, err := NewFromArchive(r1.MakeArchive(), lib.RuntimeOptions{})
+	if !assert.NoError(t, err) {
+		return
+	}
+
+	runners := map[string]*Runner{"Source": r1, "Archive": r2}
+
+	for name, r := range runners {
+		t.Run(name, func(t *testing.T) {
+			vu, err := r.NewVU(make(chan stats.SampleContainer, 100))
```
Comment (golangcibot) [inline js/runner_test.go]: Using the variable on range scope `r` in function literal (from `scopelint`)

File: lib/options_test.go [hunk 4]
```diff
@@ -513,3 +515,46 @@ func TestTagSetTextUnmarshal(t *testing.T) {
...
+		},
+		{"10.0.0.0", nil, true},
+		{"fc00:1234:5678::", nil, true},
+		{"fc00::1234::/48", nil, true},
+	}
+
+	for _, data := range testData {
+		t.Run(data.input, func(t *testing.T) {
+			actualIPNet := &IPNet{}
+			err := actualIPNet.UnmarshalJSON([]byte("\"" + data.input + "\""))
```
Comment (golangcibot) [inline lib/options_test.go]: Using the variable on range scope `data` in function literal (from `scopelint`)

File: lib/options_test.go [hunk 5]
```diff
@@ -513,3 +515,46 @@ func TestTagSetTextUnmarshal(t *testing.T) {
...
+
+			if data.expactFailure {
```
Comment (golangcibot) [inline lib/options_test.go]: Using the variable on range scope `data` in function literal (from `scopelint`)

File: lib/options_test.go [hunk 6]
```diff
@@ -513,3 +515,46 @@ func TestTagSetTextUnmarshal(t *testing.T) {
...
+				require.EqualError(t, err, "Failed to parse CIDR: invalid CIDR address: "+data.input)
```
Comment (golangcibot) [inline lib/options_test.go]: Using the variable on range scope `data` in function literal (from `scopelint`)

File: lib/options_test.go [hunk 7]
```diff
@@ -513,3 +515,46 @@ func TestTagSetTextUnmarshal(t *testing.T) {
...
+			} else {
+				require.NoError(t, err)
+				assert.Equal(t, data.expectedOutput, actualIPNet)
```
Comment (golangcibot) [inline lib/options_test.go]: Using the variable on range scope `data` in function literal (from `scopelint`)

File: lib/options.go [hunk 8]
```diff
@@ -205,6 +205,43 @@ func (c *TLSAuth) Certificate() (*tls.Certificate, error) {
 	return c.certificate, nil
 }
 
+// IPNet is a wrapper around net.IPNet for JSON unmarshalling
+type IPNet struct {
+	net.IPNet
+}
+
+// UnmarshalJSON populates the IPNet from the given CIDR JSON
+func (ipnet *IPNet) UnmarshalJSON(b []byte) (error) {
```
Comment (golangcibot) [inline lib/options.go]: File is not `gofmt`-ed with `-s` (from `gofmt`)

**Comment by na--** [comment]
@MStoykov I'm not sure if we need to support the previous (unintentional) ways of encoding and decoding values... I'm not sure if anyone used it, since this bug wasn't reported before I accidentally found it. And in the [docs](https://docs.k6.io/docs/options) we clearly state that blacklisted IPs have the following JS config format:
```js
export let options = {
    blacklistIPs: ["10.0.0.0/8"]
};
```

So that was definitely a bug. My only concern is that someone could have used the CLI `--blacklist-ip` flag and then executed `k6 cloud` (which bundles the script and all options in a `.tar` archive like `k6 archive`). In that case, the tar archive's `metadata.json` file would have contained something like this:
```js
{
  // ...
  blacklistIPs: [
    {"IP":"10.0.0.0","Mask":"/wAAAA=="}
  ],
  //...
}
```

Which could have actually worked: https://play.golang.org/p/ZHq6_Rs6YsZ
