### PR TITLE
Fix memory leak after stop sending metrics to cloud

### LINKED ISSUE #1187: Memory leak in the cloud output
https://github.com/loadimpact/k6/pull/1130 caused a regression - when the Load Impact cloud sends this the [limit reached error](https://github.com/loadimpact/k6/blob/1d6fb7f668aa089b374ee8ca35de2a34d77d29ce/stats/cloud/collector.go#L460-L470), k6 would stop sending metrics to the cloud, but it would still continue to accept them in `Collect()` and [store them in the buffer slices](https://github.com/loadimpact/k6/blob/1d6fb7f668aa089b374ee8ca35de2a34d77d29ce/stats/cloud/collector.go#L308-L313), thus rapidly exploding the memory usage.

### PR DESCRIPTION
**Pull request by cuonglm**
In #1130, we stop sending metrics to cloud when limit reached. However,
after stop sending metrics, collector still collects data, causing the
memory usage quickly increase.

To fix it, do not collect data if stop sending metrics triggered.

While at it, also remove some useless condition checking that slice
length is greater than 0 before looping.

Fixes #1187

### CODE REVIEW

File: core/engine.go [hunk 1]
```diff
@@ -226,10 +220,8 @@ func (e *Engine) Run(ctx context.Context) error {
 	for {
 		select {
 		case <-ticker.C:
-			if len(sampleContainers) > 0 {
-				e.processSamples(sampleContainers)
-				sampleContainers = []stats.SampleContainer{}
-			}
+			e.processSamples(sampleContainers)
+			sampleContainers = []stats.SampleContainer{}
```
Comment (na--) [inline core/engine.go]: I agree with the removals of `if` clauses above, when they're immediately followed by a `for ... range` loop, but in this case I think the `if` should stay, given that it would save us a function call and an allocation

File: stats/cloud/collector.go [hunk 2]
```diff
@@ -253,6 +253,12 @@ func (c *Collector) Run(ctx context.Context) {
 // Collect receives a set of samples. This method is never called concurrently, and only while
 // the context for Run() is valid, but should defer as much work as possible to Run().
 func (c *Collector) Collect(sampleContainers []stats.SampleContainer) {
+	select {
+	case <-c.stopSendingMetricsCh:
+		return
+	default:
+	}
+
```
Comment (na--) [inline stats/cloud/collector.go]: This `select` probably should be under the `if` below, though TBH I'm not 100% sure that `if` is actually necessary...

File: core/engine.go (hunk 1 above)
Comment (cuonglm) [reply core/engine.go]: Agree.

File: stats/cloud/collector.go (hunk 2 above)
Comment (cuonglm) [reply stats/cloud/collector.go]: I think regardless of their position, the functionality is the same. I place the select above because it looks like `If we stopped sending metrics already, return. Otherwise, execute Collect data logic`.

Comment (na--) [reply stats/cloud/collector.go]: Fair enough, and as you say, it doesn't really matter. In my mind "have we stopped sending metrics" is just another early return condition for a method that already had one, and since the `if referenceID... ` condition was here before it, we should put the new one after it.
