### PR TITLE
Better error message when script/module can't be found

### LINKED ISSUE #528: Better error message when script/module file can't be found
The script/module loading logic [1] in k6 tries to find files in several places before giving up and displaying an error message. However, to interpret this error message requires understanding of the way k6 tries to load modules, which shouldn't be a requirement.

Currently if you happen to specify the wrong path to the main script when running k6 (`k6 run some-path-that-doesnt-exist.js`), it will first try to load the file from the local disk and then try to load it over the network by prepending "https://". If that doesn't work, as it won't in most cases when you've just mistyped the path to a local file you'll get an error message like this:

`
ERRO[0000] Get https://some-path-that-doesnt-exist.js?_k6=1: dial tcp: lookup some-path-that-doesnt-exist.js: no such host
`

We should instead say something along the lines of:

`The file "some-path-that-doesnt-exist.js" couldn't be found on local disk, and trying to retrieve it from https://some-path-that-doesnt-exist.js failed as well. Make sure that you've specified the right path to the file. If you're running k6 using the Docker image make sure you have mounted the local directory (-v /local/path/:/inside/docker/path) containing your script and modules so that they're accessible by k6 from inside of the container, see https://docs.k6.io/v1.0/docs/modules#section-using-local-modules-with-docker.`

[1] - https://github.com/loadimpact/k6/blob/master/loader/loader.go#L64

### PR DESCRIPTION
**Pull request by antekresic**
Closes #528 

I added some checks for URL parsing and valid hostnames but I guess this would work without those. Let me know if we want to remove them.

### CODE REVIEW

File: loader/loader.go [hunk 1]
```diff
@@ -106,9 +118,20 @@ func Load(fs afero.Fs, pwd, name string) (*lib.SourceData, error) {
 		return &lib.SourceData{Filename: name, Data: data}, nil
 	}
 
-	// If not, load it and have a look. HTTPS is enforced, because it's 2017, HTTPS is easy,
+	// If its not a file, check is it a remote location. HTTPS is enforced, because it's 2017, HTTPS is easy,
```
Comment (na--) [inline loader/loader.go]: minor typo: `its` -> `it's`

Comment (antekresic) [reply loader/loader.go]: Fixed, thanks!
