### PR TITLE
Fix handling cli options default value

### LINKED ISSUE #1010: systemTags is ignored when specified in the JS or JSON options
Running `k6 run -o json script.js` with the following script:
```js
import http from "k6/http";

export let options = {
    systemTags: ["proto", "url"],
};

export default function (data) {
    http.get("https://httpbin.org/anything");
}
```

produces results like 
```
{"type":"Point","data":{"time":"...","value":116.683163,"tags":{"group":"","method":"GET","name":"https://httpbin.org/anything","proto":"HTTP/1.1","status":"200","tls_version":"tls1.2","url":"https://httpbin.org/anything"}},"metric":"http_req_duration"}`
```
while running the same script with CLI options (`k6 run --system-tags=url,proto -o json script.js`) works as expected. 

This was first [reported](https://community.k6.io/t/defects-for-counter-and-systemtags/106) in the community forum by VladT. Somewhat connected issues: https://github.com/loadimpact/k6/issues/768, https://github.com/loadimpact/k6/issues/755

### PR DESCRIPTION
**Pull request by cuonglm**
CLI options have the highest priority, so the cli options which have a
default value will always override options of other mechanisms.

To fix it, we only set default value after consolidated config process.

Close #1010

### CODE REVIEW

File: cmd/options.go [hunk 1]
```diff
@@ -65,7 +65,9 @@ func optionFlagSet() *pflag.FlagSet {
 	flags.StringSlice("blacklist-ip", nil, "blacklist an `ip range` from being called")
 	flags.StringSlice("summary-trend-stats", nil, "define `stats` for trend metrics (response times), one or more as 'avg,p(95),...'")
 	flags.String("summary-time-unit", "", "define the time unit used to display the trend stats. Possible units are: 's', 'ms' and 'us'")
-	flags.StringSlice("system-tags", lib.DefaultSystemTagList, "only include these system tags in metrics")
+	// system-tags must have a default value, but we can't specify it here, otherwiese, it will always override others.
+	// set it to nil here, and add the default in applyDefault() instead.
+	flags.StringSlice("system-tags", nil, fmt.Sprintf("only include these system tags in metrics (default %s)", lib.DefaultSystemTagList))
```
Comment (golangcibot) [inline cmd/options.go]: line is 135 characters (from `lll`)

**Comment by cuonglm** [comment]
@MStoykov I did look for other flags, but sounds like only `--system-tags` needs this treatment.

**Comment by MStoykov** [comment]
This seems like low risk commit to me so I okay with that

**Comment by MStoykov** [comment]
@cuonglm I haven't looked at them, so if there are no others I am fine, and @na--  yeah we would've definitely done it in different PR except if it was ... like one other option
