### PR TITLE
Fix wrong context is used to decide pushing metrics or not.

### LINKED ISSUE #1260: Request context is passed to PushIfNotCancelled instead of VU context
This script fails with current go master:

```
import http from "k6/http";
import { check } from "k6";
import { Counter } from "k6/metrics";

let statusCheck = { "status is 200": (r) => r.status === 200 }
let myCounter = new Counter("setup_teardown");

export let options = {
	iterations: 5,
	thresholds: {
		"setup_teardown": ["count == 2"],
		"iterations": ["count == 5"],
		"http_reqs": ["count == 7"],
	},
};

export function setup() {
	check(http.get("http://test.loadimpact.com"), statusCheck) && myCounter.add(1);
};

export default function () {
	check(http.get("http://test.loadimpact.com"), statusCheck);
};

export function teardown() {
	check(http.get("http://test.loadimpact.com"), statusCheck) && myCounter.add(1);
};
```

```
$ go run main.go run ./t.js

          /\      |‾‾|  /‾‾/  /‾/
     /\  /  \     |  |_/  /  / /
    /  \/    \    |      |  /  ‾‾\
   /          \   |  |‾\  \ | (_) |
  / __________ \  |__|  \__\ \___/ .io

  execution: local
     output: -
     script: ./t.js

    duration: -,  iterations: 5
         vus: 1, max: 1

    done [==========================================================] 5 / 5

    ✓ status is 200

    checks.....................: 100.00% ✓ 7   ✗ 0
    data_received..............: 9.7 kB  14 kB/s
    data_sent..................: 623 B   913 B/s
    http_req_blocked...........: avg=134.9ms  min=110.1ms  med=134.9ms  max=159.7ms  p(90)=154.74ms p(95)=157.22ms
    http_req_connecting........: avg=110.37ms min=110.05ms med=110.37ms max=110.7ms  p(90)=110.63ms p(95)=110.66ms
    http_req_duration..........: avg=112.33ms min=112.09ms med=112.33ms max=112.56ms p(90)=112.51ms p(95)=112.54ms
    http_req_receiving.........: avg=133µs    min=98µs     med=133µs    max=168µs    p(90)=161µs    p(95)=164.5µs
    http_req_sending...........: avg=62.5µs   min=60µs     med=62.5µs   max=65µs     p(90)=64.5µs   p(95)=64.75µs
    http_req_tls_handshaking...: avg=0s       min=0s       med=0s       max=0s       p(90)=0s       p(95)=0s
    http_req_waiting...........: avg=112.13ms min=111.93ms med=112.13ms max=112.33ms p(90)=112.29ms p(95)=112.31ms
  ✗ http_reqs..................: 2       2.931485/s
    iteration_duration.........: avg=168.24ms min=113.77ms med=114.05ms max=272.5ms  p(90)=245.25ms p(95)=258.87ms
  ✓ iterations.................: 5       7.328713/s
  ✓ setup_teardown.............: 2       2.931485/s
    vus........................: 1       min=1 max=1
    vus_max....................: 1       min=1 max=1
```

There are two problems for current code base:

 - Client.Timeout is set and intended to pass to request context, but it doesn't due to the bug in Go standard library. If we set the request context timeout explicitly, it leads to the second problem.
 - Currently, the request context is passed to PushIfNotCancelled, which is completely wrong, since when we want to use VU context instead.

### PR DESCRIPTION
**Pull request by cuonglm**
Go 1.13 and below has a bug that client timeout will not be propagated
to http request context. That bug was fixed already and will be present
in go1.14 (golang/go#31657).

With current go master, our TestSetupTeardownThresholds fails. The
reason is that we only push sample if the request context not done. When
the bug in Go stdlib was not fixed, our own http Client.Timeout is not
passed to request context, so when client makes request, it does not
aware about the request context, and always push the sample.

Now when Client.Timeout is passed to request context, as long as the
client finish the request, the request context is consider done, and we
do not push the sample anymore.

Further more, we are using the wrong context for PushIfNotCancelled.
It's intended to use with VU context instead of the request context.

In summary, to fix it:

 - We explicitly pass the timeout to request context, instead of setting in Client.Timeout.
 - Use VU context instead of request context for whether pushing metrics or not.

Fixed #1260

### CODE REVIEW

**Comment by cuonglm** [comment]
> LGTM, but let's not merge this just yet

Made it as v0.27.0

File: js/modules/k6/metrics/metrics.go [hunk 1]
```diff
@@ -89,7 +89,7 @@ func (m Metric) Add(ctx context.Context, v goja.Value, addTags ...map[string]str
 		vfloat = 1.0
 	}
 
-	stats.PushIfNotCancelled(ctx, state.Samples, stats.Sample{Time: time.Now(), Metric: m.metric, Value: vfloat, Tags: stats.IntoSampleTags(&tags)})
+	stats.PushIfNotDone(ctx, state.Samples, stats.Sample{Time: time.Now(), Metric: m.metric, Value: vfloat, Tags: stats.IntoSampleTags(&tags)})
```
Comment (golangcibot) [inline js/modules/k6/metrics/metrics.go]: line is 140 characters (from `lll`)
