### PR TITLE
Fixing tagging on submetrics

### LINKED ISSUE #590: Tagged thresholds are false negative
Expected all tagged thresholds (below) to be tainted, but they weren't.

Script: 
```
import http from "k6/http";
import { sleep } from "k6";

export let options = {
  stages: [
      { duration: "60s", target: 10 },
  ],
  thresholds: {
    "http_req_duration{system:main}": ["p(95)<50"],
    "http_req_duration{url:http://test.loadimpact.com}": ["p(95)<50"]
  }
};

export default function() {
  http.get("http://test.loadimpact.com", { tags: { system: "main" } });
  sleep(1);
};
```
Results:
```
k6 run -o cloud aws-elb/threshold_error.js 

          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /   
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io

  execution: local
     output: cloud (https://app.loadimpact.com/k6/runs/2387)
     script: aws-elb/threshold_error.js

    duration: -,  iterations: -
         vus: 1, max: 10

    done [==========================================================] 1m0s / 1m0s

    data_received..............: 375 kB 6.3 kB/s
    data_sent..................: 25 kB  421 B/s
    http_req_blocked...........: avg=1.5ms    min=5µs     med=10µs    max=49.49ms p(90)=16µs    p(95)=19.69µs
    http_req_connecting........: avg=1.49ms   min=0s      med=0s      max=49.38ms p(90)=0s      p(95)=0s     
    http_req_duration..........: avg=49.94ms  min=47.34ms med=48.2ms  max=78.64ms p(90)=52.88ms p(95)=56.1ms 
    http_req_receiving.........: avg=118.58µs min=43µs    med=115µs   max=284µs   p(90)=164.2µs p(95)=185µs  
    http_req_sending...........: avg=37.82µs  min=14µs    med=33µs    max=190µs   p(90)=51µs    p(95)=57.09µs
    http_req_tls_handshaking...: avg=0s       min=0s      med=0s      max=0s      p(90)=0s      p(95)=0s     
    http_req_waiting...........: avg=49.78ms  min=47.24ms med=48.04ms max=78.52ms p(90)=52.74ms p(95)=55.98ms
    http_reqs..................: 287    4.783315/s
    iteration_duration.........: avg=1.05s    min=1.04s   med=1.04s   max=1.1s    p(90)=1.05s   p(95)=1.06s  
    iterations.................: 281    4.683315/s
    vus........................: 9      min=1  max=9 
    vus_max....................: 10     min=10 max=10
```

### PR DESCRIPTION
**Pull request by luizbafilho**
Fixes #590 by validating that sub metric tags are included in the sample tags.

### CODE REVIEW

File: stats/stats.go [hunk 1]
```diff
@@ -197,6 +197,23 @@ func (st *SampleTags) IsEqual(other *SampleTags) bool {
 	return true
 }
 
+func (st *SampleTags) Contains(other *SampleTags) bool {
+	if st == other {
+		return true
+	}
+	if st == nil || other == nil || len(st.tags) < len(other.tags) {
```
Comment (na--) [inline stats/stats.go]: Ah, actually, I'm not sure, but I think that if `other == nil || len(other.tags) == 0`, then we should always return `true`, since every set contains the empty set.

Comment (na--) [reply stats/stats.go]: I have no idea what ruby does, but in the case of `SampleTags`, a `nil` pointer is basically the same as an empty tag set. I'm not very familiar with how tagging of submetrics is supposed to work and if this is the desired behaviour though, just that mathematically the empty set is a subset of all sets.

Comment (luizbafilho) [reply stats/stats.go]: I don't really care about that. Let's make that return `true` then.
