### PR TITLE
Fix the execution derivation bug and work around the k6 0.24.0 wrong tar metadata

### LINKED ISSUE #1058: Specifying both duration and iterations is deprecated and won't be supported in the future k6 versions
Hello,
I am getting such warnings if i put arguments for iterations, users or duration. Can i know what will it be in future iterations, I didn't find any docs about this change on the website.

### PR DESCRIPTION
**Pull request by na--**
This includes two minor improvements + refactoring and a bugfix:
- Include the k6 version in the tar archives' metadata.json 
- Do not include the derived execution options in tar archives
  
  Also, since those options were included by k6 v0.24.0, only emit a warning instead of an error if the derived execution options match any `execution` options that are "specified" by the user, since at that level we can't distinguish if we're executing an archive or a script...

-  Allow simultaneous use of `duration` and `iterations` execution shortcuts
  
    This would just produce a shared-iterations scheduler with the specified number of iterations and a `maxDuration` equal to the passed `duration`, similar to how it works in the current k6 execution. This should fix #1058.

### CODE REVIEW

**Comment by na--** [comment]
Seems that besides more tests, I'll have to make another change to the shortcut options, relating to this issue: https://github.com/loadimpact/k6/issues/1058

File: cmd/config_consolidation_test.go [hunk 1]
```diff
@@ -267,21 +265,27 @@ func getConfigConsolidationTestCases() []configConsolidationTestCase {
...
 		{opts{cli: []string{"-u", "3", "-d", "0"}}, exp{logWarning: true}, nil},
 		{
 			opts{runner: &lib.Options{
-				VUs:        null.IntFrom(5),
-				Duration:   types.NullDurationFrom(44 * time.Second),
-				Iterations: null.IntFrom(10),
+				VUs:      null.IntFrom(5),
+				Duration: types.NullDurationFrom(44 * time.Second),
+				Stages: []lib.Stage{
+					lib.Stage{Duration: types.NullDurationFrom(3 * time.Second), Target: I(20)},
```
Comment (golangcibot) [inline cmd/config_consolidation_test.go]: File is not `gofmt`-ed with `-s` (from `gofmt`)
```suggestion
					{Duration: types.NullDurationFrom(3 * time.Second), Target: I(20)},
```

**Comment by na--** [comment]
Just for posterity, here's an explanation why the bugfix part of this PR was insufficient: https://github.com/loadimpact/k6/pull/1007#issuecomment-509586983
