### PR TITLE
Fix cloud test progress status in CLI

### LINKED ISSUE #1488: k6 doesn't display all cloud test run statuses as expected
## Expected Behavior

Screenshot from 2020-06-05 14-06-54

`k6` should display cloud statuses according to response received from `/test-progress/ID` endpoint. This works as expected in `0.26`.

## Actual Behavior

Screenshot from 2020-06-05 14-07-36

Test run statuses like `INITIALIZING` and `QUEUED` are skipped and progress bar shows `Run ...` throughout several stages of test run's setup in cloud.

## Steps to Reproduce the Problem

1. Run `new-executors` build with `k6 cloud`.

### PR DESCRIPTION
**Pull request by imiric**
Closes #1488

It's still a bit janky, but at least it shows the status text in the same place as before. Please test it out locally and let me know.

### CODE REVIEW

**Comment by imiric** [comment]
@na-- Yeah, that might make more sense to bring it in line with the `k6 run` progressbars. See 66b0ad7a.

I added the elapsed/total time while the test is running, since showing `Run [==>--] Running` is not that useful. It's far from perfect, as it doesn't take into account the gracefulStop/gracefulRampDown, doesn't support `stages` right now, and the timings are way off because of the 2s ticker, but at least it shows an approximation.

[Here's what it looks like on 66b0ad7a](https://streamable.com/cu30c8). Let me know if this should be refined or if we should just hide "Running" on the right side and not bother with the time.

File: cmd/cloud.go [hunk 1]
```diff
@@ -211,20 +211,34 @@ This will execute the test on the Load Impact cloud service. Use "k6 login cloud
...
+		if derivedConf.Duration.Valid {
+			maxDuration = time.Duration(derivedConf.Duration.Duration)
+		} else if derivedConf.Stages != nil {
+			maxDuration = lib.SumStagesDuration(derivedConf.Stages)
+		} else if derivedConf.Execution != nil {
+			et, _ := lib.NewExecutionTuple(nil, nil)
+			execReqs := derivedConf.Execution.GetFullExecutionRequirements(et)
+			maxDuration, _ = lib.GetEndOffset(execReqs)
+		}
+
```
Comment (MStoykov) [inline cmd/cloud.go:241]: Given that we always have `Execution` (or don't we) is this necessary? Also .. given that we will rename and move stuff soon, moving stuff back just so you can skip 4 lines seems unnecessary ....

Comment (imiric) [reply cmd/cloud.go:241]: > Given that we always have Execution (or don't we) is this necessary?

True, I forgot that by this point we generate it by default anyway. I tested with just the `Execution` block, but since it takes the default `gracefulStop` of `30s` into account, the duration shown would be confusing to the user if they only specify the global `duration` or `stages` (it would show with an additional 30s). So I think handling the other cases makes sense to avoid this.

As for moving `SumStagesDuration` to lib, yeah, I'd like to avoid it because of the `Stage` renames, but umm wouldn't want to duplicate yet more code :D I don't think this will impact the renaming effort, but I'm fine with merging this afer that is done. Or just duplicating it, if you strongly prefer that. Though having identical `lib.Stage` and `executor.Stage` doesn't make much sense to me.

File: cmd/cloud.go [hunk 2]
```diff
@@ -209,22 +219,45 @@ This will execute the test on the Load Impact cloud service. Use "k6 login cloud
...
+		)
+		if derivedConf.Duration.Valid {
+			maxDuration = time.Duration(derivedConf.Duration.Duration)
+		} else if derivedConf.Stages != nil {
+			maxDuration = lib.SumStagesDuration(derivedConf.Stages)
+		} else if derivedConf.Scenarios != nil {
+			et, _ := lib.NewExecutionTuple(nil, nil)
+			execReqs := derivedConf.Scenarios.GetFullExecutionRequirements(et)
+			maxDuration, _ = lib.GetEndOffset(execReqs)
+		}
```
Comment (na--) [inline cmd/cloud.go:237]: The thing about the `derived` configuration is that it's always going to include `scenarios`, that's its purpose. So, you can confidently simply use `GetFullExecutionRequirements()` - see https://github.com/loadimpact/k6/blob/41a4f730ad5db5dfbe399a6384351565460e1100/core/local/local.go#L65-L70

Also, `lib.NewExecutionTuple(nil, nil)` probably doesn't really matter, since the script duration isn't changed by changing the execution segment, but it's technically incorrect. Users are perfectly able to run `k6 cloud --execution-segment=30% script.js`, so this should be something like `lib.NewExecutionTuple(derivedConf.ExecutionSegment, derivedConf.ExecutionSegmentSequence)`, like: https://github.com/loadimpact/k6/blob/41a4f730ad5db5dfbe399a6384351565460e1100/core/local/local.go#L61

File: core/local/local.go [hunk 3]
```diff
@@ -98,7 +98,7 @@ func NewExecutionScheduler(runner lib.Runner, logger *logrus.Logger) (*Execution
 		logger:  logger,
 		options: options,
 
-		initProgress:    pb.New(pb.WithConstLeft("Init")),
+		initProgress:    pb.New(pb.WithConstLeft(" Init")),
```
Comment (na--) [inline core/local/local.go:101]: hmm this extra space seems superfluous :confused: I thought the extra space before ` Run` was so it has exactly the same number of characters `Init` already has without padding? Though looking at how it looks like, even that seems superfluous?

File: core/local/local.go [hunk 4]
```diff
@@ -336,7 +336,7 @@ func (e *ExecutionScheduler) runExecutor(
 func (e *ExecutionScheduler) Run(globalCtx, runCtx context.Context, engineOut chan<- stats.SampleContainer) error {
 	executorsCount := len(e.executors)
 	logger := e.logger.WithField("phase", "local-execution-scheduler-run")
-	e.initProgress.Modify(pb.WithConstLeft("Run"))
+	e.initProgress.Modify(pb.WithConstLeft(" Run"))
```
Comment (na--) [inline core/local/local.go:339]: As I mention above, this looks strange when I run a script - try one with `sleep(1)` in the init phase and `setup()` to see it more slowly

File: lib/executor/ramping_vus.go [hunk 5]
```diff
@@ -49,18 +49,11 @@ func init() {
 	)
 }
 
-// Stage contains
-type Stage struct {
-	Duration types.NullDuration `json:"duration"`
-	Target   null.Int           `json:"target"` // TODO: maybe rename this to endVUs? something else?
-	// TODO: add a progression function?
```
Comment (na--) [inline lib/executor/ramping_vus.go:56]: Not sure why you decided to remove this - as this `TODO` says, we have a custom `stage` here, since we plan to add the possibility for non-linear progression functions (which won't be available in the simple `options.stages` configs), and maybe even things like custom tags. Also, `lib.Stage` has some extra cruft (see `lib.StageFields`) related to the CLI flags parsing that we simply don't need here...

It's not a big deal, we can always refactor it back and split it again, I just don't see the problem with such a simple type being defined locally in the executors.

File: cmd/cloud.go (hunk 1 above)
Comment (na--) [reply cmd/cloud.go]: Ah, sorry for the mostly duplicate comments, I missed this before making my review :man_facepalming: 

> but since it takes the default gracefulStop of 30s into account, the duration shown would be confusing to the user if they only specify the global duration or stages (it would show with an additional 30s). 

hmm maybe we should still print the same description we print in `k6 run` then? this will make it clearer what the total script time is, including `gracefulStop`... since right now, you'd show inconsistent times between when users use the shortcut options and when they use `scenarios`, despite k6 running the exact same test run... 

> Though having identical lib.Stage and executor.Stage doesn't make much sense to me.

As I mention in my review comment, they are currently not quite identical (`lib.Stage` has some cruft we don't need in the executors) and, in the future, we'd probably want to extend _only_ `executor.Stage` with extra features like non-linear ramping.

File: cmd/cloud.go [hunk 6]
```diff
@@ -67,8 +67,10 @@ This will execute the test on the Load Impact cloud service. Use "k6 login cloud
 		//TODO: disable in quiet mode?
 		_, _ = BannerColor.Fprintf(stdout, "\n%s\n\n", consts.Banner)
 
-		progressBar := pb.New(pb.WithConstLeft(" Init"))
-		printBar(progressBar, "Parsing script")
+		progressBar := pb.New(
+			pb.WithConstLeft(" Init"),
+			pb.WithConstProgress(0, "Parsing script"),
+		)
```
[the remark this answers is not in the document]
Comment (imiric) [reply cmd/cloud.go:75]: Resolved by 41f89e7b.

File: cmd/cloud.go [hunk 7]
```diff
@@ -88,13 +90,15 @@ This will execute the test on the Load Impact cloud service. Use "k6 login cloud
 			return err
 		}
 
-		printBar(progressBar, "Getting script options")
+		progressBar.Modify(pb.WithConstProgress(0, "Getting script options"))
+		printBar(progressBar)
```
[the remark this answers is not in the document]
Comment (imiric) [reply cmd/cloud.go]: I'm not a fan of this, as usually `And` in a function name is a code smell :), and it doesn't save us much overall, but this should be resolved in 028c46ee.

File: cmd/cloud.go (hunk 2 above)
Comment (imiric) [reply cmd/cloud.go]: OK, thanks for explaining. This should be resolved in 1c7f2ce5.

File: cmd/cloud.go (hunk 1 above)
Comment (imiric) [reply cmd/cloud.go]: > hmm maybe we should still print the same description we print in k6 run then?

I tried unifying the way this is printed for both `cloud` and `local` execution, see 1c7f2ce5. It's not ideal, we need better integration between local/cloud execution, and now `ExecutionRequirements` are calculated twice, though I could just pass the `maxVUs` and `maxDuration` to `printExecutionDescription()` to avoid it. Let me know.

File: cmd/cloud.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (na--) [reply cmd/cloud.go]: usually, I'd agree, but this simple 2-line helper seems to be much cleaner than the alternative

File: lib/executor/ramping_vus.go (hunk 5 above)
Comment (imiric) [reply lib/executor/ramping_vus.go]: I needed it to move `SumStagesDuration` to `lib`, and removing this duplication made sense, but I see your point, and I'm no longer calling `SumStagesDuration` from `cmd`, so I reverted this in cc01c16e.

File: core/local/local.go (hunk 3 above)
Comment (imiric) [reply core/local/local.go]: It was a few weeks since I changed this, but I think it was to make this consistent for both `cloud` and `run`, but you're right that it looks off.

Reverted in 20b988aa.

File: core/local/local.go (hunk 4 above)
Comment (imiric) [reply core/local/local.go]: Reverted in 20b988aa.
