### PR TITLE
Js package optimizaitons

### LINKED ISSUE #1426: Optimize the `js` package test by using compatibility mode `base`
For the most part most test execute extremely simple 1-2 line scripts which can be rewritten to not require babel or corejs and at this point run in `compatibility-mode=base`. 

This shouldn't really be a problem for finding bugs in the extended mode, but maybe I am wrong. 
As an example, I give `TestVURunInterruptDoesntPanic`, which is probably not the most representative, but still. The below are the first and second run of the same test (using -count):
without specifying compatibility-mode:base:
```
--- PASS: TestVURunInterruptDoesntPanic (13.89s)
    --- PASS: TestVURunInterruptDoesntPanic/Source (1.97s)
    --- PASS: TestVURunInterruptDoesntPanic/Archive (2.00s)
=== RUN   TestVURunInterruptDoesntPanic
=== RUN   TestVURunInterruptDoesntPanic/Source
=== RUN   TestVURunInterruptDoesntPanic/Archive
--- PASS: TestVURunInterruptDoesntPanic (4.93s)
    --- PASS: TestVURunInterruptDoesntPanic/Source (1.99s)
    --- PASS: TestVURunInterruptDoesntPanic/Archive (1.95s)
```
after speciying:
```
=== RUN   TestVURunInterruptDoesntPanic
=== RUN   TestVURunInterruptDoesntPanic/Source
=== RUN   TestVURunInterruptDoesntPanic/Archive
--- PASS: TestVURunInterruptDoesntPanic (3.48s)
    --- PASS: TestVURunInterruptDoesntPanic/Source (1.72s)
    --- PASS: TestVURunInterruptDoesntPanic/Archive (1.76s)
=== RUN   TestVURunInterruptDoesntPanic
=== RUN   TestVURunInterruptDoesntPanic/Source
=== RUN   TestVURunInterruptDoesntPanic/Archive
--- PASS: TestVURunInterruptDoesntPanic (3.55s)
    --- PASS: TestVURunInterruptDoesntPanic/Source (1.75s)
    --- PASS: TestVURunInterruptDoesntPanic/Archive (1.79s)
```
as you can see the difference is signifacant as the parsing of the code apperantly takes 10.5s more without specifying `base` and the execution combined takes like 0.5s less (the number vary but not more then 0.1s in my experiments).

All of the above is ran with `-race` and the code change is:
```patch
diff --git a/js/runner_test.go b/js/runner_test.go
index 15d24d1d..350db362 100644
--- a/js/runner_test.go
+++ b/js/runner_test.go
@@ -584,13 +584,15 @@ func TestVURunInterruptDoesntPanic(t *testing.T) {
                t.Skip()
        }

-       r1, err := getSimpleRunner("/script.js", `
-               export default function() { while(true) {} }
-               `)
+       rtOpts := lib.RuntimeOptions{CompatibilityMode: null.StringFrom("base")}
+       r1, err := getSimpleRunnerWithOptions("/script.js", `
+               exports.default = function() { while(true) {} }
+               `, rtOpts)
+
        require.NoError(t, err)
        require.NoError(t, r1.SetOptions(lib.Options{Throw: null.BoolFrom(true)}))

-       r2, err := NewFromArchive(r1.MakeArchive(), lib.RuntimeOptions{})
+       r2, err := NewFromArchive(r1.MakeArchive(), rtOpts)
        require.NoError(t, err)
        testdata := map[string]*Runner{"Source": r1, "Archive": r2}
        for name, r := range testdata {
```

### PR DESCRIPTION
**Pull request by MStoykov**
closes #1426

### CODE REVIEW

File: js/runner_test.go [hunk 1]
```diff
@@ -178,8 +178,9 @@ func TestOptionsSettingToScript(t *testing.T) {
 func TestOptionsPropagationToScript(t *testing.T) {
 	t.Parallel()
 	data := `
-			export let options = { setupTimeout: "1s", myOption: "test" };
-			export default function() {
+			var options = { setupTimeout: "1s", myOption: "test" };
+			exports.options = options;
```
Comment (MStoykov) [inline js/runner_test.go:182]: I once knew why this is required ... but not anymore I will need to go figure it out again :( 
It has something to do with the way we bind `exports`, but I decided to figure it out later

File: js/runner_test.go [hunk 2]
```diff
@@ -466,8 +468,8 @@ func TestRunnerIntegrationImports(t *testing.T) {
 			name, data := name, data
 			t.Run(name, func(t *testing.T) {
 				r1, err := getSimpleRunner(data.filename, fmt.Sprintf(`
-					import hi from "%s";
-					export default function() {
+					var hi = require("%s").default;
```
Comment (MStoykov) [inline js/runner_test.go:471]: I need to look into this ...

**Comment by MStoykov** [comment]
my local testing was from 300s->160s and from 360s->176s (depending on the machine). Both with `-race` but without `-cover`

File: js/runner_test.go (hunk 1 above)
Comment (MStoykov) [reply js/runner_test.go:182]: okay so if you just do:
`export.options = {}` you don't have any local variable `options`, but you should be able to just use `exports.options` but there was a bug https://github.com/loadimpact/k6/pull/1430 .

 I can rebase only the fix on top of new-schedulers/master ? if we aren't going to merge this soon

File: js/runner_test.go (hunk 2 above)
Comment (MStoykov) [reply js/runner_test.go:471]: okay so ... basically setting `default` to something only works if babel helps us otherwise we should just say `exports  = "hi!"` if we wont' be using babel.  
much better explanation [here](https://2ality.com/2015/12/babel-commonjs.html). I don't think we need to do anything until we start supporting import/export ouself or through goja :D
