### PR TITLE
fix(js): properly marshal lib.Options values to JS options

### LINKED ISSUE #886: Consolidated script options include the Go struct fields
Running the following script with k6, with or without specifying the `vus` via the CLI flag:
```js
export let options = {
    vus: 5,
};

export default function () {
    console.log("vus normal", options.vus);
    console.log("vus typeof", typeof options.vus);
    console.log("vus JSON.stringify", JSON.stringify(options.vus));
    console.log("vus properties", Object.getOwnPropertyNames(options.vus));
    console.log("vus .value()", options.vus.value());
}
```
will produce something like this:
```
INFO[0001] vus normal                                    0="[object Object]"
INFO[0001] vus typeof                                    0=object
INFO[0001] vus JSON.stringify                            0=5
INFO[0001] vus properties                                0="null_int64,int64,valid,isZero,marshalJSON,marshalText,ptr,value,valueOrZero"
INFO[0001] vus .value()                                  0=5
```

Instead, `vus` should be a plain number. This seems like a regression that likely was caused by https://github.com/loadimpact/k6/pull/681 or https://github.com/loadimpact/k6/pull/713, since [`k6 v0.22.1`](https://github.com/loadimpact/k6/blob/master/release%20notes/v0.22.1.md#ux) is the first k6 version that doesn't work as expected,  `k6 v0.22.0` produces the following correct result:
```
INFO[0000] vus normal                                    0=5
INFO[0000] vus typeof                                    0=number
INFO[0000] vus JSON.stringify                            0=5
INFO[0000] vus properties                                0=
ERRO[0000] TypeError: Object has no member 'value'
```

### PR DESCRIPTION
**Pull request by imiric**
This ensures any `guregu/null` values in `lib.Options` are correctly unpacked and saved as JS script options.

Closes #886

### CODE REVIEW

File: js/bundle.go [hunk 1]
```diff
@@ -217,6 +218,18 @@ func (b *Bundle) Instantiate() (bi *BundleInstance, instErr error) {
...
+		case null.Bool:
+			val = v.ValueOrZero()
+		case null.Float:
+			val = v.ValueOrZero()
+		case null.Int:
+			val = v.ValueOrZero()
+		case null.String:
+			val = v.ValueOrZero()
+		case null.Time:
+			val = v.ValueOrZero()
```
Comment (imiric) [inline js/bundle.go]: The repetition here is silly to me, but I didn't find a way to make it more generic (without using `reflect`). Is there a cleaner / more concise way of doing this?

Comment (na--) [reply js/bundle.go]: You can use go interfaces to check for all types that have a particular method, `ValueOrZero()` in this case. Add something like:
```go
type valueOrZeroer interface {
  ValueOrZero() time.Time
}
```
then you can check if the type is `valueOrZeroer` in the type switch

Comment (na--) [reply js/bundle.go]: Nevermind, the previous response didn't take into account the different return types

Comment (imiric) [reply js/bundle.go]: @na-- Sorry, so you're saying that this can't be DRY'd? :-/

I wish the switch with type assignment worked for `case null.Bool, null.Int, null.String, ...` so there could only be one `val = v.ValueOrZero()` expression, but I get why it doesn't. The repetition here is killing me, though... :)

Comment (imiric) [reply js/bundle.go]: @na-- Take a look at latest commit 0da876c6 (I'll squash it before merging).

Unfortunately, this pretty much moved where the `switch` happens, since we need to properly convert `reflect.Value`s, but I think I agree with you that it's cleaner here as it already deals with reflection and type checking.

It's also handling `types.NullDuration` properly now.

File: lib/options.go [hunk 2]
```diff
@@ -500,11 +500,38 @@ func (o Options) ForEachSpecified(structTag string, callback func(key string, va
...
 
 		shouldCall := false
 		switch fieldType.Type.Kind() {
 		case reflect.Struct:
+			// Unpack any guregu/null values
 			shouldCall = fieldVal.FieldByName("Valid").Bool()
+			valOrZero := fieldVal.MethodByName("ValueOrZero")
+			if shouldCall {
+				if valOrZero.IsValid() {
+					val := valOrZero.Call([]reflect.Value{})[0]
```
Comment (imiric) [inline lib/options.go]: Is `[0]` safe here or should we protect against `index out of range` errors?

File: lib/options.go [hunk 3]
```diff
@@ -500,11 +500,38 @@ func (o Options) ForEachSpecified(structTag string, callback func(key string, va
...
+						value = val.Int()
+					case reflect.Uint, reflect.Uintptr, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
+						value = val.Uint()
+					case reflect.Float32, reflect.Float64:
+						value = val.Float()
+					case reflect.String:
+						value = val.String()
+					default:
+						value = val.Interface()
+					}
```
Comment (imiric) [inline lib/options.go]: I'm not fond of the nested `switch` here, but didn't want to complicate things further.

Also, this is not an exhaustive `Kind` check, but it handles most of the `guregu` nullable types except `null.Time`, which we're not using.

Let me know if this can be improved.

File: lib/options.go [hunk 4]
```diff
@@ -500,11 +500,38 @@ func (o Options) ForEachSpecified(structTag string, callback func(key string, va
...
+				} else {
```
Comment (na--) [inline lib/options.go]: I think you can simply implement the `ValueOrZero` method for our own custom `types.Duration` type.

File: lib/options.go (hunk 2 above)
Comment (na--) [reply lib/options.go]: It should be fine, after all, we know that all `ValueOrZero()` calls return a result. If that changes in the future, it's better to panic instead of silencing the error.

File: lib/options.go (hunk 3 above)
Comment (na--) [reply lib/options.go]: I don't think we need this `switch` at all, since we're already calling the `callback` with an `interface{}` value, we don't really care what the type of the `ValueOrZero()` result it. So, I think we can simply use the [`reflect/Value.Interface()` method](https://golang.org/pkg/reflect/#Value.Interface)...

File: js/bundle_test.go [hunk 5]
```diff
@@ -588,6 +588,10 @@ func TestOpen(t *testing.T) {
 
 func TestBundleInstantiate(t *testing.T) {
 	b, err := getSimpleBundle("/script.js", `
+		export let options = {
```
Comment (na--) [inline js/bundle_test.go]: Not sure this is the best test for this feature. It doesn't hurt to have it, but it's not testing that options that are injected from outside in the JS runtime. In the real k6 execution, since CLI flags and environment variables have precedence over exported script `options`, once we consolidate them, we write them back in the JS runtimes, so the script can read their actual values: https://github.com/loadimpact/k6/blob/16b2a1ba2373c5a63d8a533eef788389c944c69c/cmd/run.go#L184-L187

Something like that isn't tested here

File: lib/options.go (hunk 3 above)
Comment (imiric) [reply lib/options.go]: :man_facepalming: Thanks, will fix.

File: js/bundle_test.go (hunk 5 above)
Comment (imiric) [reply js/bundle_test.go]: @na-- I meant the original test as a unit test since the change was in `Bundle.Instantiate()`, but then left it after the move to `ForEachSpecified` as an "indirect" unit test, but mostly out of laziness :smile:

I can add a higher level functional test for this, but I'm wondering if there's a need for it. If I'm interpreting `cmd/run.go` correctly, `getConsolidatedConfig()` is called on line 139, and both the Runner and the Engine receive the consolidated options, so by the time `Bundle.Instantiate()` is called the config hierarchy has already been resolved and we wouldn't need to test this resolution for this change.

Correct me if I'm wrong, and if so, what would be the best place for this higher level test (should we test at the Bundle or Runner level)?

Comment (na--) [reply js/bundle_test.go]: No need to go much higher level than this, you just need to test the proposition that changing the options in the `Bundle` will then be reflected in the actual `options` object in the running script. After all, that's what `SetOptions()` does: https://github.com/loadimpact/k6/blob/731e55be472895ffac6d5d77c218ffade98453e8/js/runner.go#L275

So, you should be able to do something like this at the end of this same test:
```
b.Options.VUs = 55 // or whatever, something to simulate call to the runner's SetOptions()
bi2, err := b.Instantiate() // make a new instance
// verify that bi2's `options` contains the externally updated value, not the one initially specified in the script
```
```

Comment (imiric) [reply js/bundle_test.go]: Thanks, I misunderstood your original comment. The test should be fixed now.
